### ISSUE TITLE
Add comment/forum functionality

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#15]
Could we embed Discus or Discourse or somehow use existing GitHub capabilities?

**Comment by rogers492** [comment]
From @6a6d74 
For the forum, I suggest migrating to "discourse". The W3C Web Incubator Community Group (http://wicg.io) provides an example which is similar to what we want to achieve. They use GH-Pages to manage the website (see repo http://github.com/WICG/wicg.io); provide links to GitHub where the coding is done (see http://github.com/WICG/ for a bunch of repositories) and use (self-hosted) Discourse, the "100% open source discussion platform [...]", for the open dialogue (see http://www.discourse.org and http://github.com/discourse/discourse). FYI, as open source, we could install Discourse ourselves (easy; less than 30-mins)- alternatively there's a US$100/month hosting option or a one-time US$99 fee to install in the cloud but for us to manage (see https://payments.discourse.org/buy/). Looking at the customer list, it seems that Discourse works for some large and/or trendy projects ...

**Comment by cassie-stearns** [comment]
Looking at Disqus versus Discourse, it looks like Discourse is the way to go if we are interested in a traditional forum format. Discourse requires the use of a server - we can't just install some code on the github pages we have. @solson-nws is working on installing Discourse on a server for a test, but we will have to decide where we want it to reside permenently.
Disqus is more of a comment-system than a traditional forum software. We would register the website with Disqus, and then we can install the code on the pages we want to allow comments on. This essentially is a plug-in system where we would not be responsible for hosting the content of the system (but also theoretically might not ultimately have full control over it, either).

**Comment by cassie-stearns** [comment]
Here are some comments from Marc: 
Just an FYI here, so you can better evaluate which direction you would
like to go:

1. DusQus is a Platform Service.  You subscribe to the DisQus platform
and then put customized (branded) JavaScript onto the target site that
intends to support a users forum.  The target site does not operate
the forum service, and there is no back-end code available.  Think
Google Ad Words.  This might work well for OpenWIS.

2. Discourse is a Software Bundle.  You can run an instance of the
software within a private data center.  However the software follows a
different distribution model.

Developers can download the code and stand-up a development platform
and tinker.  Website operators download a Docker VM image and deploy a
production ready instance.  There apparently is no middle ground.
Although the code is available, and with enough labor a production
ready instance can be crafted from the source, but the distribution
disavows support for this kind of deployment.  The problem with the
Docker platform VM bundle will be NIST 800-53.

**Comment by cassie-stearns** [comment]
We have test cases up for Discourse (https://discourse.dev2.openwis.io) and NodeBB (https://nodebb.dev2.openwis.io). If you need the login for the VM, please let me know. 

There is also a demo of the Discourse github plugin at: [https://cassie-stearns.github.io/test/discourse40.html](https://cassie-stearns.github.io/test/discourse40.html )(existing topic) and [https://cassie-stearns.github.io/test/discourse0.html](https://cassie-stearns.github.io/test/discourse0.html )(creating a new topic...although this will change when there is a new topic created, presumably.)

**Comment by rogers492** [comment]
Discourse has been selected - implementation is Issue #157
