### ISSUE TITLE
Action-TC-2017-02 Architecture docs

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#152]
Add the v3/v4 architecture docs to the wiki for on-boarding developers.

**Comment by rogers492** [comment]
@lmika-bom This was just the slide or two you showed at the Washington Dev Con. They might be useful even when discussing v5 (especially versus v4) - is this a quick job or harder than it looks?

**Comment by lmika-bom** [comment]
@rogers492, no problem.  This should be relatively easy to do.

**Comment by rogers492** [comment]
Am closing this since we are no-longer developing v4.
