### ISSUE TITLE
Action-TC-2017-05 Electronic CLA

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#155]
Investigate whether we could have an electronic CLA and whether it could be accessed through the Forum.

**Comment by rogers492** [comment]
The whole process of refining our CLA mgt is covered by a bunch of actions: #202 #201 #200 #190 #189 #156 #155 #98

**Comment by cassie-stearns** [comment]
I have been looking into this. There are basically 2 ways to go about this. I think 1) is the better of the two for now: 
1) Create a form-enabled PDF, and post that on our website. We can include a link to this in the Forum. (Possibly, I *might* be able to create a preview box, but I'm really not sure on that). People could sign digitally and email to the organization. (Or could print and sign traditionally, then scan and email back).  
2) Create a digital form on a webpage. I currently do not see a good way to do this on the Discourse Forum. (We could create a custom field when people create a user account, but that would be for the Discourse user account, not for the Github user account, which is what we really want.) It may be possible to do on the main webpage, but I have some concerns about the level of security we would need for something like a legal document, and whether Github pages can support the database software we would need.

**Comment by cassie-stearns** [comment]
Okay, I just stumbled accross this as a third possibility. Someone has been working on a tool to allow CLA to be put into a github project. I would want someone more familiar with github in general to take a look at this, and see it it might be viable. 
https://github.com/vmware/claportal

**Comment by rogers492** [comment]
Hi @cassie-stearns I looked at the [CLA project on github](https://github.com/vmware/claportal). It doesn't look finished and seems overkill to me.

**Comment by rogers492** [comment]
Hi @cassie-stearns While looking at how Discourse do their CLA, I noticed that they use [Google Forms](https://www.google.com/forms/about/?utm_source=product&utm_medium=forms_logo&utm_campaign=forms) to provide an electronic CLA facility. I've had a quick look and it looks really simple and easy. The form can be embedded into a webpage just by embedding a bit of html and the responses can be collected together into a Google Docs s/sheet. Please have a look and let me know what you think.

**Comment by cassie-stearns** [comment]
@rogers492 I looked at the Google Forms. Yes, I think that is a technically feasible option (although I can't speak to the legality of clicking a checkbox versus signing an item). I was able to make and embed a quick test form in my own github website without any problems. We would need to have a Google account which would be the owner of the spreadsheet (I think I could create it and then transfer ownership - I am testing that capability now). Making a spreadsheet from responses is also easy.

**Comment by rogers492** [comment]
Hi @cassie-stearns I could edit the form you sent me via Google - I assume that is what you intended?

**Comment by cassie-stearns** [comment]
@rogers492 That was the first part of the test. I wanted to see if I could share the document outside noaa.gov. Unfortunately, it appears I cannot change ownership to anyone who does not have a noaa.gov Google account. Are you able to make a copy of the form that you own? (I suppose I could try making a form with my personal google account and transferring ownership, if that fails.)

**Comment by rogers492** [comment]
@cassie-stearns Ok, just tried that; sent back to your NOAA email addr.

**Comment by cassie-stearns** [comment]
@rogers492 I tried filling it out. Did you get my response (in the form)?

**Comment by rogers492** [comment]
Closed after SC meeting Dec 2017. The SC decided to accept the CLA as-is.
