### ISSUE TITLE
Action-TC-2017-10 Establish how we could get off Discourse 

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#160]
Establish how we would get our data out of Discourse if, in a year from now, we decide to do something else or otherwise wish to discontinue the use of Discourse for the forum.

**Comment by rogers492** [comment]
Any progress @mgiannoni ? Can we export/import?

**Comment by mgiannoni** [comment]
Paul:

This appears fixed.  Build is working without any problem.

Cheers!

Marc Giannoni
Unix System Engineer
Phone: 301.427.9478
Cell: 301.915.5266

**Comment by rogers492** [comment]
Hi @mgiannoni I'm not sure that answers the question, which is: Are we able to export our forum topics from Discourse if we decide to use something else in a year?

**Comment by mgiannoni** [comment]
Paul:

My apologies, I must have been asleep when wrote my prior reply...

**Comment by rogers492** [comment]
Ok, so we could dump the database tables if we really wanted to. On reflection, I think we should just go with Discourse without worrying about this. Discourse is a modern forum that is still improving and with a very active community - it will last us a few years at least. We will most likely only outgrow it when something radically different comes along, and trying to export old topics to the new shiny thing won't make sense anyway - probably be easier to manually prune and copy the hot topics at the time. Anyway, @mgiannoni, we gave it some thought... action closed.
