### ISSUE TITLE
Action-TC-2017-13 Project summary for excel2wis

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#163]
Write an excel2wis project summary for the project page on the website and send to Cassie for publication.  If it is suitable, you may just want to link to whatever you have in the GitHub README.

**Comment by cassie-stearns** [comment]
Is what is on [http://openwis.github.io/openwis-documentation/projects/](http://openwis.github.io/openwis-documentation/projects/) and [http://openwis.github.io/openwis-documentation/projects/excel2wis/](http://openwis.github.io/openwis-documentation/projects/excel2wis/) good, or do we want more to be added to the summary?

**Comment by rogers492** [comment]
Done and published on the website: http://openwis.github.io/openwis-documentation/projects/excel2wis/
