### ISSUE TITLE
Action-SC-2016-13 Seek legal advice on shelter from litigation

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#171]
Seek legal advice (from Michael Robbins) on whether the Articles/Rules shelter the Contributors from litigation.

**Comment by 6a6d74** [comment]
Have requested update from Michael Robbins (Met Office Legal):

The key issue is whether the Articles provide legal protection for partners and contributors against litigation – e.g. if users of the software have some issue and they want to pursue a claim against the authors etc.

Article 21.1 [1] states:

> No Member may lay claim on the assets of the Organization, nor will any Member be held personally liable for the liabilities contracted by or action brought against the Organization.

Members are defined in Article 4.1 [2]:

> The Organization is composed of its signatory members and members that are subsequently admitted (together the “Members”).

Neither Partners, as defined in Articles 9.1 [3], nor Contributors, not defined in the Articles - only in Internal Rules 6.1, are not mentioned in Article 21.1.

So – questions:
(1)	Do we need to include a definition of Contributors in the Articles?
(2)	Do we need to amend Article 21.1 to refer to Members, Partners and Contributors? 

So far as I can see, the Contributor License Agreement (Annex A to the Internal Rules) [5] doesn’t mention indemnity; and Para 3 “intellectual property infringement” indicates that third parties may make claims against a Contributor in the case of intellectual property infringement.

[1]: http://openwis.github.io/openwis-documentation/articles/21-limited-liability.html#article-21.2 
[2]: http://openwis.github.io/openwis-documentation/articles/4-members.html#article-4.1
[3]: http://openwis.github.io/openwis-documentation/articles/9-organizational-partners-and-relationship-with-other-third-parties.html#article-9.1 
[4]: http://openwis.github.io/openwis-documentation/rules/6-membership-and-partnership-fees-rights-privileges-and-obligations.html#rule-6.1 
[5]: http://openwis.github.io/openwis-documentation/rules/A-contributor-license-agreement.html

**Comment by 6a6d74** [comment]
Leaving this issue open for discussion at the SC meeting.

**Comment by 6a6d74** [comment]
Discussed at SC-2018. No further comments.

Now closing this issue.
