### ISSUE TITLE
Action-SC-2017-01 Update Technical Rules to clarify roles

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#172]
Update the Technical Rules to clarify the roles in the development process - see the @6a6d74 doc from last year: http://openwis.github.io/openwis-documentation/assets/ATT-OWIS-SC-2016-6-governance_r4.pdf

**Comment by solson-nws** [comment]
The PMC will review the updated documentation in github and website to explicitly describe roles in the development process.  The process itself is well defined now, just needing to add roles surrounding the process.

**Comment by solson-nws** [comment]
Let's look at https://github.com/OpenWIS/openwis-deploy/wiki and spend some time in the upcoming scrum to discuss roles.  Let's create the roles and define what the area of responsibilities are so it's clear where the lines of delineation are.  Here are some obvious roles in the development process to start with:

1.  Developer
2.  lead developer
3.  CI lead
4.  Quality control lead
5.  Testing lead

**Comment by solson-nws** [comment]
Motion was approved, Steve is in the process of updating webpage to reflect these changes.

**Comment by jude2018** [comment]
Assigned to TC

**Comment by solson-nws** [comment]
github webpage has been updated with Roles in the Technical  Rules section

**Comment by jude2018** [comment]
@solson-nws - has a pull request been created or has teh web page been updated already?
