### ISSUE TITLE
Action-SC-2017-02 Update Technical Rules to define 'User'

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#173]
Update the Technical Rules to define the 'User' role.

**Comment by jude2018** [comment]
Assigned to TC

**Comment by solson-nws** [comment]
@benjaminsaclier proposes that this definition is obsolete now.  Users that contribute to community open source project like OpenWIS become a contributor, and therefore has been captured in definitions already defined in the Technical Rules section as a "**developer**".   How do others feel about this?

**Comment by solson-nws** [comment]
@SungsooDO  @remy-gibault  @wqu-bom @mvisa @kuldeep-sri @StephanSiemen :  Thoughts?

**Comment by solson-nws** [comment]
contributor and user are considered one in the same.  Closing ticket
