### ISSUE TITLE
Action-SC-2017-03 Define 'patchable'

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#174]
Ask the NWS Security team how they would define 'patchable'.

**Comment by mgiannoni** [comment]
Definition:

To be “patchable” means that corrections to software can be applied to the software without altering the expected application behavior or performance.

Explanation:

The OpenWIS application is most certainly “patchable”.  The entire development process and Continuous Integration environment contributes to the application’s “patchability”.   What actually occurred to prompt the question was a routine update cycle that changed the Java version on the platform, which subsequently caused unexpected OpenWIS application behavior.  Ultimately, National Weather Service submitted a “patch” that resolved the compatibility issue with the new Java version, proving that OpenWIS was in fact “patchable”.

Discussion:

OpenWIS software “patchability” is in and of its itself, a moot point.  When one thinks of “OpenWIS Software and the term patchable”, what’s of greater interest is Platform Support and how that is defined.   There are many platforms and certainly some such as MIPS R5900 (Playstation-2) should not receive support.  And beyond the platform architecture, lays the Operating System (OS) family (i.e. BSD, Linux, etc) and the OS distribution.  Full commitment to supporting the selected OS Distribution implies an ability to accommodate the update cycle practiced by the distribution’s community.   

Questions that still need to be clarified by OpenWIS TC include:

What OS Distributions would OpenWIS prefer to support?   
Our suggested OS Distributions, open for discussion, would include:
Debian
RedHat
Windows
What {workflow-cycle} is assigned to the OS update cycle?
Our suggested workflow cycle, open for discussion, would include:
Pull Request
Bug Report
Fork A Branch
Should OpenWIS become OS agnostic?  
The idea is that OpenWIS is Java, right?
Does platform support include the Developer's Environment?
Elaborate on this some more

**Comment by rogers492** [comment]
Ok, so we should state the software will be designed and developed in such a way that routine patches to the supported OS will rarely break the software and that the software will be fixed whenever we find that they do. 
But do we really want to support Windows - isn't a Linux stack sufficient?

**Comment by mgiannoni** [comment]
Paul

These are only suggestions for discussion, they're not intended to be
commitments.  Windows is certainly challenging.

The other area of discussion is the work-flow question.  How would OS
Platform Changes be managed?

For example, take the use-case where the CentOS/RedHat Java version update
caused an issue with National Weather Service....
Were we to pledge some form of OS support, what's the best way to handle
this event?
Should the Continuous Integration system schedule some routine upload of
the Platform Changes from the CentOS/RedHat distro?
If so, these changes would show up as either Integrated Testing success or
failures.  We could then submit issues or pull requests, or something
similar.

Are there better ways, to perform this routine task?

Cheers!

Marc Giannoni
Unix System Engineer
Phone: 301.427.9478
Cell: 301.915.5266

**Comment by rogers492** [comment]
We're meant to be adopting a quarterly routine OS patch strategy - so every 3 months our test servers would be patched and we would raise issues when it didn't work. Do you do something similar @mgiannoni / @lmika-bom ?

**Comment by mgiannoni** [comment]
Yes, that's what we do.

**Comment by lmika-bom** [comment]
We do not for the machines OpenWIS is currently running on.

**Comment by rogers492** [comment]
Ok, so long as at least one of us is doing these tests and reporting the outcomes amongst the Association then we are covered. We might at some point incorporate into CI, but I don't see that as essential from the start. How does that sound @mgiannoni @lmika-bom ?

**Comment by lmika-bom** [comment]
That sounds fine to me.

**Comment by woollattd** [comment]
Just my 2p... :-)
maybe a little simplistic though...but just me, thinking aloud

I would suggest that anything is patchable. 
It's the level of success that needs to be demonstrated/measured. Patches can break things, occaisionally.

I would disagree slightly with the concept that "corrections to the software can be applied without altering expected application behaviour or performance." as many patches are created to do just that. - fixing and improving

Each of the middleware components is patchable - that is looked after by their respective owners/creators. 
The OpenWIS code is what we look after - the glue that binds this middleware together to produce the result we need.
We need to make sure that changes to the middleware still allows our system to function as required. And where issues arise - try and fix them in our code. teh middleware is out side of our control, whcich adds risk to the patching process.

I believe that seeking the "definition of patchable" isn't raelly what we should be looking for. 
We just need to be able to demonstrate that we can patch the OpenWIS system successfully - that we can update, fix, and/or improve it.
To demonstrate that we need to have the resource available, whether form the OpenSource Community and/or within the OpenWIS Consortium, and produce regular patches to handle the issues that are raised as well as dealing with changes in middleware.

**Comment by jude2018** [comment]
I think patching or patchability needs a specific sub heading under 'Technical Rules' on the website

**Comment by solson-nws** [comment]
@woollattd :  Please update the definition for patchable for November TC review

**Comment by jude2018** [comment]
Assigned to TC

**Comment by solson-nws** [comment]
This has been updated under Technical Rules portion of github webpage.  Closing this issue

**Comment by jude2018** [comment]
@solson-nws - has this been done via a Pull Request or updated diectly?
