### ISSUE TITLE
Action-SC-2017-05 Add software quality statement to Technical Rules

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#176]
Develop a software quality statement and add into the Technical Rules.

**Comment by solson-nws** [comment]
Update https://docs.google.com/document/d/16YSoYOpwPxfnvLm7GtIGfKyWtZKTKvYPU0gLUiZ22hs/edit into technical rules and close

**Comment by solson-nws** [comment]
Opening **Software Quality Statement** ready for comment

OpenWIS follows an Agile Development Model and supports a full [Continuous Integration Environment](https://github.com/OpenWIS/openwis-deploy/wiki).  The code resides on [GitHub](https://openwis.github.io/openwis/) and follows the traditional GitHub  revision process.  The Continuous Integration Environment performs automated [Testing](https://github.com/OpenWIS/openwis-automated-tests/wiki) using [Jenkins and Cloudbees](https://github.com/OpenWIS/openwis/wiki/OpenWIS-Testing-Regime) tooling.

**Comment by jude2018** [comment]
Per TC discussion in September 2018 ALL to comment on the word document to enable Steve to update document for approval at the next TC meeting.
@solson-nws @woollattd @benjaminsaclier @wqu-bom @SungsooDO @StephanSiemen @remy-gibault

**Comment by jude2018** [comment]
Assigned to TC

**Comment by solson-nws** [comment]
A software quality statement has been added to the Technical Rules section of the github webpate.  Closing this issue.

**Comment by jude2018** [comment]
@solson-nws - has this been done via a Pull Request or udpdated directly?
