### ISSUE TITLE
Action-SC-2017-14 Improve processes for managing new projects

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#185]
In light of the discussion around new projects (eg: FMI's smartmet - https://github.com/fmidev/) and the uncertainties this has surfaced around the roles of PMC/TC/SC, review the Articles, Internal Rules and Technical Rules and propose any improvements.

**Comment by 6a6d74** [comment]
Outline of responsibilities...

    - Board
        - Ensure the purpose of the Association is clear
        - Ensure that the governance framework is fit for purpose for the Association to meet its goals
        - Ensure that risks to the Association are being adequately managed; intervene where necessary
        - Approval of Association policy - including amendments to Articles and Internal Rules 
        - Approve annual budget, budget amendments and extraordinary expenditure; set membership fees
        - Approve initiation of Projects and amendments to Project Charters recommended by SC 
        - Approve appointment of new Partners and Members
        - Appoint Managing Directors
    - Steering Committee
        - Determine if proposed Partners and Members meet the joining criteria for the Association
        - Conduct out-reach to encourage organisations to join as Partners?
        - Coordinate initiation of new Projects (determine if proposed projects fit the purpose of the Association; review Project Charters; establish the PMC for the Project; appoint Project Leader; help determine the License under which the Project will operate; commission technical resources (from TC) required by the Project etc.)
        - Hold Projects accountable for delivering to their schedule and quality plan (PMC must agree release criteria with SC); assess whether they are ready to move from Incubation to Mature phase
        - Review Project’s requests to amend their Charter
        - Recommend amendments to Articles and Internal Rules to Board
        - Arbitrate where Project-level issues cannot be resolved by the PMC or TC
        - Review Project requests for financial support; approve where these requests are within existing budget
        - Coordinate legal & financial issues for portfolio of OpenWIS projects (e.g. contributor license agreement [framework])
        - Ensure compliance with Association processes
        - Manage risks to the Association; act as point of escalation for Project-level risks
        - Appoint SC Chair and Vice-chair
        - Appoint TC Chair and Vice-chair
    - Technical Committee **> may need a change to Article 14 as some of the responsibilities listed therein are now pushed to the PMC (unless we treat this as delegated authority, and TC must ensure that the items indicated in Article 14.1 are adequately done) (also see Rule 7.8 defining role of TC)**
        - Plan, manage & operate the technical infrastructure and resources required to support portfolio of OpenWIS projects
        - Manage CLAs from Contributors
        - Define, and ensure compliance with, the Development Process
        - Define, and ensure compliance with, the Code of Conduct
        - Define, and ensure compliance with, the general Technical Rules applying to all Projects (coding standards, [software] packaging policy etc.)
        - Provide architectural oversight for Projects (e.g. “design authority” providing technical oversight)
        - Provide release management oversight for Projects
        - Mentor Projects in Incubation phase
        - Defines technical standards that Projects must adhere to; verifies compliance
    - PMC
        - Run the projects, approve work-packages, collect requirements, set milestones, define quality criteria / release criteria, ensure contributors have completed a CLA etc.
        - Define, and ensure compliance with, Technical Rules for the Project (**or should this be done at the TC level for _all_ projects?**)
        - Appoint PMC members and elect new Project Leaders

**Comment by 6a6d74** [comment]
Check who is responsible for appointing SC Chair and Vice-chair

**Comment by 6a6d74** [comment]
Clarify how the PMC reports up to the SC

**Comment by 6a6d74** [comment]
TC is the PMC for OpenWIS Core

**Comment by 6a6d74** [comment]
Increases autonomy for PMC ... based on the scope and objectives as set out in their Charter

SC & TC are there to hold the PMC accountable to governance 

Need to introduce (yearly) reporting from PMC to SC mention milestones, release criteria ... which then enables SC to endorse what they’re doing

**Comment by 6a6d74** [comment]
TC may comment on the technical mechanisms ... as part of design authority / architectural oversight

**Comment by 6a6d74** [comment]
At the SC meeting on 9-Oct, Mattéo queried the responsibility for electing the SC chair and vice-chair. 

[Article 13.5](http://openwis.github.io/openwis-documentation/articles/13-steering-committee.html#article-13.5)

> The chairperson (“SC Chair”) and vice-Chairperson (“SC Vice-Chair”) of the Steering Committee shall be elected from amongst the Delegates on a simple majority by a vote of the Steering Committee. Each Delegate shall have one vote.

**Comment by 6a6d74** [comment]
Minutes (extracted from item §3 of [SC meeting, October 2017](http://openwis.github.io/openwis-documentation/minutes/2017-10-09-OpenWIS-Steering-Committee-2017-Oct.html)):

> **Clarification of organisational roles within OpenWIS Association**
> JT - The main topic for discussion today is the TC work plan, but I want to cover the organisational roles first because I think it will be relevant to that discussion later. If you recall, during the March meeting we decided that the roles of the PMC/TC/SC didn’t reflect how responsibilities should be assigned once the Association began working on multiple projects. This was covered in item 13.3.1 of the March minutes and there were some actions, resolutions and supporting documents related to this:
> Action-SC-2017-14 Improve processes for managing new projects “In light of the discussion around new projects during SC-MAR2017 (eg: FMI’s smartmet) and the uncertainties this has surfaced around the roles of PMC/TC/SC, review the Articles, Internal Rules and Technical Rules and propose any improvements.”
> Action-SC-2016-14 Add new risks to Risk Register “Add a risk to the Risk Register stating that the Articles/Rules of the Association do not adequately define the architecture role of the TC (Article 14.1)”
> Note: Resolution-AM-2016-09 approving “edits to describe governance for multiple projects”
> See OpenWIS Project Governance Rules Supplement PMC structure diagram
> JT - We went through the rule changes we would like at the March SC and the action was placed on me to update the way the organisational structures are described.
> JT - As a result I propose update to Internal Rules Title 7 based on responsibilities outlined here
> MDA - I’m not sure that the SC can choose the SC Chair and Vice-chair.
> JT - It might look odd but I checked the rules and that’s what they say. I’ve looked back through previous meetings and that’s how we’ve always done it - the SC appoints them. The Board is responsible for policy changes, managing risks and deciding the purpose of the Association. The SC is responsible for ensuring the Association operates correctly according to it’s own rules and processes.
> MDA - Yes, ok.
> JT - We may need to change article 14 relating to the TC. The TC provides technical oversight and operates technical infrastructure for the Association.
> MDA - So the PMC is the same as the SC but for a project.
> JT - Yes, the PMC sets what the project does, what milestones it works to etc. The SC holds the PMC to account, checks that it is doing what it said it would.
> MDA - That makes sense, but there is nothing in PMC that points to SC; you have TC acting as technical board, PMC in charge of each project, with a link to the TC but not to the SC.
> RGr - TC/PMC are combined for OpenWIS-Core and we have to shift tasks from TC to PMC, so the description of the TC role is new.
> JT - Yes, the TC maintains repositories, release processes etc. What we have been getting so far from the TC is a PMC report for OpenWIS-Core, so we’re confused about the roles. This change will increase autonomy for the PMC. Previously we’ve had a few days at TC deliberating the work plan then we’ve discussed it again at the SC. This change makes the PMC responsible for the work plan.
> RGr - With multiple projects we will discuss each at SC; if SC believe a project isn’t going well, how do we control that?
> JT - The PMC says what the release criteria are, then the SC will hold them to account if they don’t deliver that.
> RGr - So we need a report from the PMC to the SC, on say, a yearly basis.
> JT - Good idea; SC can then endorse the proposed milestones and quality criteria.
> JT - The TC could also use that to comment on the technical approach as part of its architectural oversight.
> JT - Ok, I’ve added those points into the issue
> JT - Anyone not happy with the issue as it now stands? Ok, hearing nothing, I’ll complete that action to make those updates and then we can vote on the new rules at the next SC. We need to be clear about these new roles before the next Annual Meeting.

**Comment by jude2018** [comment]
Back in December 2017, the SC recommended some governance changes to the Board for their approval. Unfortunately, I did not proceed to ask the Board to approve by correspondence – and hence, the “Internal Rules” have not been updated. 

Changes to describe amended governance arrangements: https://github.com/OpenWIS/openwis-documentation/pull/340
Recommended to the Board by SC, Dec 2017 … RESOLUTION-SC-2017-14:Resolution: vote: 5-0 in favour - Rule change on project governance is recommended.

As we approach the next Annual Meeting, I think it is useful to remind ourselves of the respective roles of PMC, TC, SC and Board – as described in the updated governance. Being clear on this will help each of the separate meetings being held in a couple of weeks proceed more smoothly, and avoid the repetition that we’ve seen in previous Annual Meetings.

The main thing to be aware of is the ”supplemental note” is added to the Internal Rules describing the respective responsibilities:

https://github.com/OpenWIS/openwis-documentation/blob/96eb5ce7e6a1f4c8cce4fa55fdcfb9d0a4bef524/_rules2/2017-12-06-OpenWIS-Governance-Roles-Responsibilities.md

This supplemental note will be added to the OpenWIS Website once Pull Request 340 is authorised – but this requires Board approval. There are a few other changes too; but it’s worth reviewing this file.

Also, I attach a Governance Summary presentation that I previously compiled.

Best regards, Jeremy 

SC Chair and Board Vice-Chair

**Comment by jude2018** [comment]
[OpenWIS Association governance.pptx](https://github.com/OpenWIS/openwis-documentation/files/2009677/OpenWIS.Association.governance.pptx)

**Comment by rogers492** [comment]
Closed by merger of #340
