### ISSUE TITLE
Action-SC-2017-19 Submit completed CLA forms

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#190]
Complete the CLA form(s) for all contributors to OpenWIS-Core within your organisation and send scans to Paul Rogers.  Paul to insert the scans into the documentation repository.

This action is on SC delegates: Kari, Sungsoo, Mikko, Weiqing, Loic, Remy, Jeremy, Paul.

**Comment by wqu-bom** [comment]
I presume this is requred after the CLA formulation is finalised. We do not have the final version of CLA yet(?)

**Comment by rogers492** [comment]
@wqu-bom correct - I'll send a reminder when its ready.

**Comment by rogers492** [comment]
The whole process of refining our CLA mgt is covered by a bunch of actions: #202 #201 #200 #190 #189 #156 #155 #98

**Comment by jude2018** [comment]
Please also see the related issue - https://github.com/OpenWIS/openwis-documentation/issues/456

**Comment by jude2018** [comment]
Close and #342 is tracking the CLAs due
