### ISSUE TITLE
Action-SC-2017-32 FOSS4G

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#203]
Kari Sheets: There is a range of sponsorship/contribution/attendance options for FOSS4G
- Consider whether someone from NWS should/could attend FOSS4G 2017 in Boston 
- Propose how the Association might sponsor/contribute/attend FOSS4G 2018.

**Comment by rogers492** [comment]
FOSS4G 2018 is planned for Dar es Salaam, Tanzania:
27, 28 AUGUST 2018 : WORKSHOPS
29, 30, 31 AUGUST 2018 : THREE DAY MAIN CONFERENCE
1, 2 SEPTEMBER 2018 : CODE SPRINTS AND COMMUNITY EVENTS

**Comment by rogers492** [comment]
[FOSS4G](http://2018.foss4g.org/)

**Comment by solson-nws** [comment]
Recommending we don't attend FOSS4G as PR move and close this ticket
