### ISSUE TITLE
Action-SC-2017-34 Promotion at WMO Exec Council 2018

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#205]
Matteo Dell'Aqua - Propose (in Jan 2018) what we might do to promote the work of the Association on WIS 2.0 at the EC 2018.

Remy, are you able to put something into Matteo's diary?

**Comment by rogers492** [comment]
@6a6d74  Is this different from our CBS TECO activities or does that lead into this?

**Comment by 6a6d74** [comment]
@remygiraud noted the side-meeting planned for the Cache in the Cloud at EC-70, Friday 22 June.

PRs of GISCs are invited to commit to participate in the Cache in the Cloud project and to determine the appropriate funding mechanism.

No formal funding commitment at EC-70; this will come via a formal letter from WMO Secretariat following agreement.

At CBS-TECO the difficulties arose around determining the funding mechanism and whether or not it was affordable based on an equal share (e.g. CHF20k / year for 3-years)

SC Delegates are asked to support their PRs gain commitment for Cache in the Cloud during this side event.
