### ISSUE TITLE
Action-SC-2017-36 Review the Community Manager role

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#207]
Loic Le Gallou - Review the Community Manager role and propose who, from among the SC/TC delegates, might perform which community tasks.

The original role description written by @6a6d74 is here: http://openwis.github.io/openwis-documentation/assets/ATT-OWIS-SC-2016-3_Community_Mgr.DOC

Remy, Loic isn't on GitHub so assigned to you.  If Loic gets an account you can reassign, but I thought you might contribute to this action anyway. thanks, Paul

**Comment by rogers492** [comment]
@6a6d74 @remy-gibault Are we still wanting a Community Manager?

**Comment by 6a6d74** [comment]
Reviewing this, I think it that a Community Manager might be a project-specific activity? In which case a PMC could submit a request for funding to support such a role.

Also, note the disparity between the "Community Manager" role description I wrote (based on typical characteristics) and the original request which was more like a Technical Lead.

**Comment by 6a6d74** [comment]
Discussed at SC-2018.

For the time being SC agree there is no requirement for the community manager.

Closing this issue.
