### ISSUE TITLE
Action-BM-2017-03 Draft Risk Register for Association

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#227]
Draft a Risk Register for the Association.  Get it reviewed by the SC in June 2017 and the Board in July 2017.  Once approved, publish on the website (or link to it from the website).

The draft can initially contain dummy risks.  However, prior to review it should be populated with real risks generated by this SC activity: #191

**Comment by rogers492** [comment]
Since **Risks** are just _potential_ **Issues**, I suggest we use the Issue tracking built into GitHub to track Risks. This could be done as follows:
1. Add a GitHub Issue to the openwis-documentation repository for each Risk: the title would start RISK-NNNNNN-title.
2. Add a detailed description of the Risk in the initial comment, using structured sentences.
3. Add labels.
4. Add Impact and Probability and Score.
5. Compare Score to Risk Appetite for Association and assign risk RAG accordingly.
6. Add Issue to GitHub project column based on RAG (may also be columns for NEW, CLOSED etc?)
7. Assign risk owners. 
8. Assign to milestone for next risk review or risk action.
9. Label with meeting that is tracking eg: PMC/TC/SC/BM. Label with RISK.

**Comment by rogers492** [comment]
Add link to Risk Log from website.

**Comment by rogers492** [comment]
Initial list of risks:
Insufficient funds to operate the Association.
Insufficient people to operate the Association.
Insufficient project activity.
Projects fail to deliver.
Fails to keep up with important technology trends.
Fails to stay relevant to WMO.
Fails to attract new members.
Fails to demonstrate a reusable collaborative framework.
Fails to gain a reputation for quality software.
Fails to engage with open source community.
Fails to reach new user communities.

**Comment by rogers492** [comment]
From Emma:
Hi Paul

You asked previously for contributions regarding possible financial risks to the Association. The main financially relevant risks I can think of are:

•        Compliance/Legal risk – this is around meeting aisbl requirements in Belgium (e.g. filings etc.) with the impact being reputational damage, additional scrutiny, monetary implications (fines); the mitigation to this is having the specialist support/advisors the Association has identified in Belgium to date
•        Funding risk – Association has insufficient funds to operate

These may have already been captured/identified elsewhere.

Kind regards
Emma

Emma Edwards CA        Business Accountant

**Comment by rogers492** [comment]
Suggested PROBABILITY scale:

|chance of occuring|description|% probability|
|---|---|---|
|Very Low| Unlikely |<5%|
|Low|Possible| 5-30%|
|Medium|Likely over time |30-50%|
|High| Likely| 50-75%|
|Very High|Likely and Imminent|>75%|

**Comment by rogers492** [comment]
Suggested IMPACTS assessments:

|Financial|€k|
|---|---|
|Very Low|<25|
|Low|25-50|
|Medium|50-75|
|High|75-100|
|Very High|>100|

|Reputation| |
|---|---|
|Very Low|A few unhappy members/partners/contributors|
|Low|Several unhappy members/partners/contributors|
|Medium|Loss of potential members/partners/contributors|
|High|Loss of existing members/partners/contributors|
|Very High|Loss of credibility with WMO|

|Goals| |
|---|---|
|Very Low|Minor impact on goals|
|Low|Significant impact on one goal|
|Medium|Significant impact on more than one goal|
|High|Failure to achieve one goal|
|Very High|Failure to achieve more than one goal|

**Comment by rogers492** [comment]
Suggested Probability/Impact matrix:


|prob\impact |VL|L|M|H|VH|
|---|---|---|---|---|---|
|VL|G|G|G|G|G|
|L|G|G|A|A|A|
|M|G|A|A|R|R|
|H|G|A|R|R|R|
|VH|G|A|R|R|R|

**Comment by rogers492** [comment]
Where RAG status is: R=RED, A=AMBER, G=GREEN.

RED = Immediate action required to mitigate, avert or otherwise manage the risk.
AMBER = Plan of action required for managing the risk in the future.
GREEN = Level of risk acceptable, no action required apart from monitoring.

**Comment by rogers492** [comment]
Having thought through how we will record and score risks, I have come up with a slightly simpler process in which the risk appetite, which is unlikely to change, is implied by the risk categories we manage ie: financial viability, reputation and goals.  Therefore, the process is now...

Since Risks are just potential Issues, I suggest we use the Issue tracking built into GitHub to track Risks. This could be done as follows:

1. Add a GitHub Issue to the openwis-documentation repository for each Risk: the title would start RISK-NNNNNN-title.
2. Add a detailed description of the Risk in the initial comment, using structured sentences.
3. Add estimated Impact and Probability (very low to very high) for Financial, reputation and goals.
4. Assign risk RAG accordingly.
5. Add Issue to GitHub project column based on RAG (may also be columns for NEW, CLOSED etc?)
6. Assign issue to risk owners.
7. Assign to milestone for next risk review or risk action.
8. Label with body that is tracking eg: PMC/TC/SC/BM. If a risk is escalated, then change the label to the body it was escalated to. Label with RISK.
9. Add risk review to the agenda of PMC/TC/SC meetings. 
10. When necessary, PMC and TC would escalate risks to SC. PMC and TC would also provide a risk summary report to the annual meeting for review by both the SC and the Board.
11. SC would escalate risks to Board whenever they require Board decisions or actions to manage.
12. In general, project risks will be managed by the PMC, broader technical risks will be managed by the TC, risks to the Association will be managed by the SC, the Board will only manage risks escalated from the SC, usually because they need Board level actions/decisions according to the articles/rules. However. the Board may assume management of any risk at it's sole discretion.

**Comment by rogers492** [comment]
Note: a project PMC doesn't have to use the risk register structure above - each project manages its risks as  agreed by the project.  However, the PMC will need to escalate any risks to the SC that are a threat to the Association. They may also transfer a technical risks that has wider implications than just the project, to the TC.

**Comment by rogers492** [comment]
Risk RAG is added as a label of the appropriate colour: RED, AMB, GREEN.

**Comment by rogers492** [comment]
Example [risk log](https://github.com/OpenWIS/openwis-documentation/projects/4)

**Comment by jude2018** [comment]
The process was discussed and ageed at the 2018 Annual SC meeting and agreed.  The status of the action was checked at the 2018 Board and agreed as complete.  Therefore, close.

**Comment by 6a6d74** [comment]
Risk management process information described above will be converted into a Rules Supplement by @jude2018
