### ISSUE TITLE
Issues (minor) with new excel2wis page

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#243]
Hi @cassie-stearns I merged your PR. There are a couple of minor issues with the excel2wis project page:
1. The project title; should it say excel2wis?
2. The Documentation section is empty - is this intended?
cheers,
Paul

**Comment by cassie-stearns** [comment]
1. I just missed the project title. I can correct that. 
2. Currently, I do not have any official documentation to provide links to in this section. I can comment it out until I get some, or I can leave it blank.

**Comment by mclaudon-mto** [comment]
Hi Cassie, 

the official documentation of the excel2wis is included in the official excel2wis repository : 
- the user manual : https://github.com/OpenWIS/excel2wis/blob/master/Excel2wisxml_manual.pdf 
- the developer manual : https://github.com/OpenWIS/excel2wis/blob/master/excel2wisxml_developer_manual.md 

Cheers,
Michaël

**Comment by cassie-stearns** [comment]
The corrections have been made.

**Comment by rogers492** [comment]
Closed by #259
