### ISSUE TITLE
Action-SC-2016-32 Check for Trademark fees

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#247]
Emma Edwards - Check with Michael Robbins for any fees related to Trademarks.

**Comment by rogers492** [comment]
Handed on to Stacey - just need to know if the Assoc should budget for any.

**Comment by Stacey-Squires** [comment]
Spoke with Michael Robbins, he believes the trademarks currently sit with MFI and can be assigned to the association free of charge. We need to confirm this and get them reassigned. 
If we need to file any new marks, the fees start at €850 (plus the Trade Mark Attorney’s fees).
Fees will also be due on renewal of the marks (every 10 years).

**Comment by rogers492** [comment]
Ok, thanks @Stacey-Squires 
@6a6d74 Do you want to request the transfer at the SC in Dec (add to the agenda)?

**Comment by 6a6d74** [comment]
@Stacey-Harvey, @jude2018 - please can we proceed with the transfer of trademarks? I guess this will require liaison with MFI? I can raise this at the SC meeting.

Perhaps we should open a new Action / Issue to cover the transfer of trademarks; I think we have answered the question about fees.

**Comment by jude2018** [comment]
Will open a new action

**Comment by Stacey-Harvey** [comment]
@6a6d74, @jude2018 

Information in advance of the SC.

MFI will need to transfer the trademarks, see below from Michael Robbins:

"As far as I am aware, the registered trademarks referred to in the Internal Rules are still held by MFI. These will need to be assigned to the AISBL (if they haven’t been already) and then the register will need to be updated with details of the new owner. I believe these are European trademarks (registered at OHIM), in which case the notification should be free"

**Comment by 6a6d74** [comment]
trademarks are defined here: http://openwis.github.io/openwis-documentation/rules/1-name-legal-status-and-trademarks.html#rule-1.6

**Comment by mvisa** [comment]
Seems the expire date is 2020: https://euipo.europa.eu/eSearch/#details/trademarks/009149345

**Comment by 6a6d74** [comment]
@remygiraud has discussed this issue with colleagues in Meteo France (they hold the trademark).

2 issues to resolve. First, transfer to OpenWIS Association. Second, to renew the trademark.

Approval for trademark transfer pending - but will not be an issue.

Cost to transfer will be EUR3326. Renewal fees to be advised.

Meteo France will incur the cost and invoice OpenWIS Association.

Following BREXIT, European trademarks no longer apply to UK. Decision needs to be made as to whether the trademark should be extended.

@remygiraud to check whether the trademark covers only Europe (where OpenWIS Association is based) - in which case there would not be a need to extend the trademark to the UK ... i.e. treat UK same as other international territories like USA and Australia.

**Comment by remygiraud** [comment]
I have received the contract to transfer the ownership from MF to Openwis. I asked Michaël to check. He confirmed he is OK with the text. Next step is to sign the transfer with someone from my top management at MF. Keep the issue opened until transfer. Hopefully during the next month or two.

**Comment by jude2018** [comment]
per SC on 16 Dec - the transfer of the 'OpenWIS' from MF to AISBL is complete. Therefore, AISBL is the full owner of OpenWIS trademark.  
@remygiraud to check renewal date.
MF have been helpful in the transgfer process. Therefore, may be need to pay MF for transfer of trademark get confirmion of duration for renewal.

**Comment by remygiraud** [comment]
Based on https://euipo.europa.eu/eSearch/#details/trademarks/009149345 the current registration ends up by mid 2020. I am going to take care of the renewal.

**Comment by jude2018** [comment]
Per SC on Dec 2019:
RGr - Finished transfer of OpenWiS. Therefore, AISBL is the full owner of the ‘OpenWIS’ trademark.
RGr - MF have been helpful and pay MF for transfer of trademark get confirmation of duration for renewal.
RGr – to check and confirm date of renewal.
@remygiraud - is there an update on this, please?

**Comment by jude2018** [comment]
SC Mar 2020 - complete and extended for 10 years (work done by MF).  There may be more work to done as a result of UK exit of the EU.
