### ISSUE TITLE
Action-TC-2017-25 Provide guidance on 'Concepts'

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#273]
To give everyone an idea of what sort of feedback we need to add to the requirements spreadsheet.

**Comment by NMichas** [comment]
_(Includes feedback from @tg4444)_

# Concepts for pilots
Partners are encouraged to submit concepts which may potentially lead to pilot implementations as part of implementation option “Option 1”. The aim of these pilots will be to demonstrate the added value of specific technologies and approaches to the future OpenWIS version. 

Such concepts may be added as new rows in the "Concepts" sheet of the requirements spreadsheet file. Each concept may have the following information:

- **Tile**: The title of the concept.
- **Requirements involved**: A list of existing requirements that this concept will affect, or empty if it is a completely new idea.
- **Concepts to demonstrate**: What the implementation of this concept will demonstrate.
- **Description**: A description of how the concept is expected to operate.
- **WIS 2.0 relevance (if applicable)**: Mention of the paragraph in the WIS 2.0 Strategy section that this concept relates to.

## Example concepts:

### Dynamic modules
**Tile**  
Dynamic modules

**Requirements involved**  
- REQ058 (Indexing)  
- REQ062 (Harvesting)  
- REQ090 (Harvesting)  
- REQ093 (Harvesting)  
- REQ120 (Harvesting)  
- REQ028 (Dissemination)  
- REQ029 (Dissemination)  
- REQ031 (Dissemination)  
- REQ035 (Dissemination)  
- REQ044 (Dissemination)  
- REQ093 (Dissemination)  
- REQ182 (Dissemination)  
- REQ183 (Dissemination)  
- REQ184 (Dissemination)  
- REQ185 (Dissemination)

**Concepts to demonstrate**  
- Modularity  
- Hot-deployment

**Description**  
Provide the ability to dynamically deploy/undeploy services and service-client modules, 
avoiding any application downtime. This technology will allow  on-the-fly modification of application features and provision of new services by utilising OSGi technology.

The envisaged pilots may include:  
1. Harvesting services and clients (e.g. add new harvesting protocols/versions)  
2. Data dissemination (e.g. add new dissemination methods)  
3. Indexing engines (e.g. support Solr, Lucene, or a custom indexing engine)

**WIS 2.0 relevance (if applicable)**  
_WIS 2.0 will offer mechanisms to increase collaborative development, maintenance
and support of services, promote the exchange of best practices and enable the uptake of new
technologies_

### Messaging-based notifications  
**Tile**  
Messaging-based notifications 

**Requirements involved**  
- _To be defined_

**Concepts to demonstrate**  
- Notifications

**Description**
Implementation of a mechanism that will allow the user to subscribe to delivery notifications of specific data. The user will subscribe to queues that will map to specific locations or data types (e.g. temperature data, humidity, cities, regions, etc.).

These notifications will be pushed to the user’s mobile/desktop/browser, and from there he will have the ability to view the metadata information and also download the data file to the device using a separate service.

**WIS 2.0 relevance (if applicable)**
_Retirement of traditional GTS message switching as the basis for operational, realtime
data exchange in favour of industry standard data distribution methods and
protocols such as secure file transfer and publish-subscribe messaging._

**Comment by mclaudon-mto** [comment]
Hello Nassos,
thanks for the guidance on 'Concepts'. 
Could you send us the link to WIS2.0 Strategy ? 
Thanks,
Michaël

**Comment by NMichas** [comment]
Hi Michaël,

Here's the link: [library.wmo.int/opac/doc_num.php?explnum_id=3505](library.wmo.int/opac/doc_num.php?explnum_id=3505).

The relevant section is on p.1031, Recommendation 35 (CBS-16).

**Comment by lmika-bom** [comment]
Hi @NMichas, I must say that the "Dynamic modules" looks like a great candidate for the concepts that I would like to see for the option "1.5".

**Comment by rogers492** [comment]
Expect these concepts to be incorporated into the roadmap.
