### ISSUE TITLE
Action-SC-2017-57 Reword the text of the TC Briefing to the SC

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#281]
@solson-nws Reword the text to make it clear that we are not suggesting that OpenWIS-Core is forked when a contributor takes it upon themselves to develop a new feature; that is, any contributions should advance the trunk.

**Comment by 6a6d74** [comment]
This particularly relates to the maintenance of OpenWIS 3.x

**Comment by solson-nws** [comment]
This work has been done.  Need to restructure this into website.  Refers to this URL:  https://github.com/OpenWIS/openwis/wiki/Making-Contributions
