### ISSUE TITLE
Action-SC-2017-58 Create a roadmap for OpenWIS-Core

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#282]
@solson-nws Create a roadmap from OpenWIS v3.14.8 in Jun 2017 to WIS 2.0 in 2025, or as much as can be defined.

**Comment by jude2018** [comment]
@benjaminsaclier to create a roadmap for OpenWIS core based on PMC discussion in Helsinki

**Comment by benjaminsaclier** [comment]
[Openwis-Product Roadmap Timeline-v1.0.xlsx](https://github.com/OpenWIS/openwis-documentation/files/2128139/Openwis-Product.Roadmap.Timeline-v1.0.xlsx)

**Comment by solson-nws** [comment]
This is done
