### ISSUE TITLE
Action-BM-2017-13 Check that UKMO could bill the Assoc for work

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#295]
1. Check with OpenWIS Treasurer/UKMO Finance that UKMO could invoice OpenWIS Association to recover any agreed costs, for example costs incurred by UKMO contractors doing work for OpenWIS Association.
2. Confirm any conditions, eg: need to run competitive procurement or other due diligence.

**Comment by jude2018** [comment]
No issues arising from annual meeting.  Also covered by existing rules supplement (i.e. http://openwis.github.io/openwis-documentation/rules2/2016-03-09-OpenWIS-Financial-Management.html).  Therefore, close.
