### ISSUE TITLE
Action-BM-2017-14 Define the mechanisms/rules for financial support of projects

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#296]
1. Work out the mechanics of how a project running under OpenWIS Association, be it incubation, mature or whatever, could be supported financially. 
2. How and under what conditions, would partners/members be reimbursed for any costs incurred by agreement with OpenWIS Association governance? 
3. Can the Assoc behave like a private company, or is each partner subject to their own public spending rules & regs?
3. Are Rule changes needed?

**Comment by rogers492** [comment]
See also #284

**Comment by jude2018** [comment]
Covered by #340 therefore close
