### ISSUE TITLE
OPP-1: Pub-Sub Notifications

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/openwis-documentation#299]
Pub-Sub Notifications
=========

## Description 
This pilot will demonstrate a queue-based push notification mechanism, as well as enhancements in the metadata itself that allow for enhanced subscription and search functionality.

When end-users subscribe to metadata they are registered in specific queues, and as soon as data is available for them, notifications are pushed from the server component towards the subscribed clients. These notifications will also provide a link for the ad-hoc download of the  data in question.

As an enhancement to this approach - and a possible proposal towards the WMO - the metadata itself is to be enhanced with location information.
This information is to be stored within new tags and attributes, and is expected to hold values for:
- Country: ISO ALPHA-3 Code
- Region: Free-text, multiple languages
- City: Free-text, multiple languages

This information will then be used by the application to improve both search and subscription functionality, by allowing a user to find metadata for groupings like:
- Southern Europe
- Southern France
- Northern Hemisphere

The above will be achieved by a component that will allow the user to define "groups" of location. For example, "Southern Europe" could be defined as Greece, Italy, France, Spain, Portugal. When searching or subscribing to Southern Europe, the user would effectively subscribe to the join of all metadata that fall within the above locations.

## Features 
- Message queues
- Subscriptions
- Search
- Enhanced metadata

## Technology
- RabbitMQ

## Complexity / Effort Estimation 
100 - 110 pdays.

## WIS 2.0 relevance
- 4.1.1 Changes in data supply patterns and user expectations over the past decade present new challenges that the current WIS struggles to meet. At the same time, changes in technology (e.g. cloud computing infrastructure, messaging, search engines, web services etc.) present new opportunities. 
- 4.1.8(g) Retirement of traditional GTS message switching as the basis for operational, realtime data exchange in favour of industry standard data distribution methods and protocols such as secure file transfer and publish-subscribe messaging;

**Comment by rogers492** [comment]
The outcome of the vote was that OPP-6: WIS Djibouti will be taken forward.
