### ISSUE TITLE
OPP-2: Modularity Demonstration: Security

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/openwis-documentation#300]
Modularity Demonstration: Security
=========

## Description
This pilot will demonstrate how applying an OSGi architecture can benefit the security implementation of future WIS systems.

OSGi (Open Service Gateway Initiative) is a Java framework for developing and deploying modular software programs and libraries. In short, it is ideal for creating well-defined and well-bounded components of an application, and OSGi containers typically provide features as hot-deployment, which allows a "live" modification of application features.

Using OSGi in the authentication/authorization layer of a web application will allow the system administrator to modify the authentication provider at will. It can be configured to use one of LDAP. Database, or SSO in the background, while this change will be transparent to the rest of the web application's API.

## Features 
- Modularity
- Authentication/authorization using Database
- Authentication/authorization using LDAP
- Authentication/authorization using SSO

## Technology
- Apache Karaf
- OpenAM

## Complexity / Effort Estimation 
50 - 60 pdays.

## WIS 2.0 relevance
- 4.1.8(h) Fault tolerant design of WIS 2.0 components and applications to deliver high quality of service even where underlying infrastructure cannot guarantee a level of service.

**Comment by rogers492** [comment]
The outcome of the vote was that OPP-6: WIS Djibouti will be taken forward.
