### ISSUE TITLE
OPP-3: Distributed Monitoring

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/openwis-documentation#301]
Distributed Monitoring
=========

## Description 
This pilot will demonstrate a way of remote monitoring of WIS installations (NCs, DCPCs, GISCs).
A set of predefined metrics will be pushed from each installation - in a hierarchical fashion - and collected in the parent nodes, where a number of reports will be auto-generated. These reports will be available for viewing through specific URLS.

An administrative component that will allow a measure of custom report creation will also be implemented, in order to showacse the ease of
customization of the proposed solution.

To simulate real-world usage, a number of such systems will be deployed using Docker containers that will communicate with each-other as described above.

## Features 
- Metrics generator module
- Monitoring module
- Report module
- Administrative module

## Technology
- MQTT
- Apache Camel
- InfluxDB
- Grafana
- Docker

## Effort Estimation 
90 - 110 pdays.

## WIS 2.0 relevance
- 4.1.8 (d)Use of analytics and user feedback to drive continued improvement of user experience

**Comment by rogers492** [comment]
The outcome of the vote was that OPP-6: WIS Djibouti will be taken forward.
