### ISSUE TITLE
OPP-4: Excel2WIS Electron

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/openwis-documentation#302]
Excel2WIS Electron
=========

## Description 
Excel2WIS is a tool that has been developed by Météo-France and allows the generation of large set of metadata WMO Core 1.3 profile issue from an Excel document. 

This pilot focuses on the creation of a user-friendly cross-platform desktop application that will replace Excel2WIS. This will be achieved using Electron, an open source library developed by GitHub for building cross-platform desktop applications with HTML, CSS, and JavaScript.

## Features
- Metadata Editor

## Technology
- Electron JS

## Complexity / Effort Estimation 
50 pdays

## WIS 2.0 relevance
- 3.3.1 NMHSs face continuing pressure on budgets. It is important to remove duplication of effort, to facilitate the use of existing solutions (such as commercial, open source or off the shelf systems), and to make the infrastructure more cost-effective through simplification.

**Comment by rogers492** [comment]
The outcome of the vote was that OPP-6: WIS Djibouti will be taken forward.
