### ISSUE TITLE
OPP-5: WIS Dashboard

### ISSUE THREAD

**Issue by tg4444** [OpenWIS/openwis-documentation#303]
WIS Dashboard
=========

## Description 
This pilot will demonstrate the idea of using predefined and custom widgets in order to increase productivity/efficiency.

A number of standard widgets will be created that will simulate functions such as reporting, logging, user management, etc., and users may add them to their dashboard in order to benefit from the offered functionality.

Furthermore, it will be possible for users to create and add their own custom widgets to the application.

## Features
- Widget management
- Widgets

## Complexity / Effort Estimation 
40 - 50 pdays.

## Technology
- Widget framework

## WIS 2.0 relevance
- 3.1.1 Effective use of information, including combining data from multiple societal benefit areas, is a factor of economic growth. It is increasingly important that information becomes available in a way that maximizes uptake and business opportunities.
- 4.1.6 The WIS 2.0 platform will support a change in user behaviour from downloading a copy of information for local processing to using services that process the information at its source. The WIS 2.0 platform will be complemented by a set of principles to encourage best-practice information assurance (data life cycle management) by the WMO community. This will support emergence of common approaches designed to provide users with a confidence about the quality of information utilizing user feedback mechanisms, to support continuous improvement, and to present a seamless user experience across Members’ services.

**Comment by rogers492** [comment]
The outcome of the vote was that OPP-6: WIS Djibouti will be taken forward.
