### ISSUE TITLE
Jboss WildFly 8.2.x OpenWIS DataService Support

### ISSUE THREAD

**Issue by mgiannoni** [OpenWIS/openwis-documentation#306]
1. change the application.xml in openwis-dataservice.ear:  <initialize-in-order>true</initialize-in-order> to  <initialize-in-order>false</initialize-in-order>.

2. change six enterprise beans' jndi lookup strings to use java:app namespace instead of ejb: namespace: DisseminationManagerTimerService, DisseminationStatusMonitor, PackedFeedingTimerService, SplittingTimerService, CacheIndex, and CacheManager.

3. change the dependency scope to "provided" in for "<groupId>io.openwis.dataservice.cache</groupId>  <artifactId>openwis-dataservice-cache-core</artifactId>    <version>${project.version}</version>" in the POM file:  openwis-dataservice/openwis-dataservice-cache/openwis-dataservice-cache-webapp/pom.xml

4. change an enterprise bean ExtractionTimerService from local view to remote: 
openwis-dataservice/openwis-dataservice-server/openwis-dataservice-server-ejb/src/main/java/org/openwis/datasource/server/service/impl/ExtractionTimerServiceImpl.java

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis#274
