### ISSUE TITLE
Upgrading Security Service to use OpenAM 3.x and OpenDJ 3.x

### ISSUE THREAD

**Issue by mgiannoni** [OpenWIS/openwis-documentation#308]
Update ForgeRock common libraries from 12.0.0 to 13.0.0:
1. openwis/pom.xml
Multiple changes in ForgeRock API javascript:
2. openwis-metadataportal/openwis-portal/src/main/webapp/saml2/jsp/

**Comment by rogers492** [comment]
This issue was moved to OpenWIS/openwis#272
