### ISSUE TITLE
Action-SC-2017-66 Provide slides on new governance structure

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#327]
@6a6d74 Provide slides on new governance structure to Matteo for visit to CMA.

**Comment by 6a6d74** [comment]
Slide deck created ... see attached

Complete

[OpenWIS Association governance.pptx](https://github.com/OpenWIS/openwis-documentation/files/1391069/OpenWIS.Association.governance.pptx)
