### ISSUE TITLE
Action-SC-2017-69 Show notifications of rain or similar service in TECO demo

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#330]
@6a6d74 In the narrative for the TECO demo, show notifications of rain or a similar service, as an example of how new services could be built on top of WIS 2.0.

**Comment by 6a6d74** [comment]
Complete. See narrative [here](https://github.com/OpenWIS/openwis-documentation/issues/309#issuecomment-336935051) in ISSUE #309
