### ISSUE TITLE
RISK-000001 Insufficient funds

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#333]
Because the OpenWIS association has spent too much money and has not received additional contributions, it now has insufficient funds to operate.

**Comment by rogers492** [comment]
|Probability|Financial impact|Reputation impact|Goals impact|
|---|---|---|---|
|VL|VL|H|VH|

**Comment by 6a6d74** [comment]
Review at SC-2018 (31-May-2018).

Content with current assessment. No additional mitigation required.

**Comment by jude2018** [comment]
SC March 2020 - No isues relating to funds at present.  Therefore close.

**Comment by jude2018** [comment]
Please note the related risk #335

**Comment by jude2018** [comment]
Note Board resolutions of 4 June re membership fees
