### ISSUE TITLE
RISK-000003 Under resourced

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#335]
Because too few people with the right skills are actively contributing to the work of the OpenWIS Association the Association fails to deliver on projects or meet its goals.

**Comment by rogers492** [comment]
|Probability|Financial impact|Reputation impact|Goals impact|
|---|---|---|---|
|M|VL|L|VH|

**Comment by 6a6d74** [comment]
Risk reviewed SC-2018.

Resourcing has been active topic of discussion during  SC-2018.

Mitigation: employ cash-reserve of Association to enable "study" project work to be contracted out to third parties.

Mitigation: work to get more active contribution from Member and Partner organisations; TC and SC delegates to work with their home organisation to better encourage in-kind contributions. We will also create a new Goal for the organisation to help focus activity in this regard.

With these mitigations in place, change rating Amber ... noting that the approach of using cash-reserves is not sustainable long-term.

**Comment by jude2018** [comment]
Per SC 16 Dec 19 - agreed that initial priority is to work on the CICD environment and AMQP workshop until March 2020 and keep the annual meeting in late May 2020.  This would reduce capacity issues in the short term.  However, the approach to middleware procurement and implications of adopting OpenCDMS are not yet fully known to assess the resourcing situation.

**Comment by jude2018** [comment]
Agreed to leave as AMBER as procurement resourcing is not clear for OpenWIS 3x middleware

**Comment by jude2018** [comment]
Per SCon 26 and 28 May 2020 - please note this action #588
