### ISSUE TITLE
Action-SC-2017-72 Finalize the CLA as-is and obtain signed copies from all contributors

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#342]
Finalize the CLA as-is and obtain signed copies from all current contributors

**Comment by jude2018** [comment]
https://github.com/OpenWIS/openwis-documentation/pull/386

**Comment by jude2018** [comment]
- Signed CLA received from KMA.
 - IMD informed of CLA process

**Comment by jude2018** [comment]
Also being tracked in TC - see #456

**Comment by wqu-bom** [comment]
BoM submitted on 1 May 2019

**Comment by 6a6d74** [comment]
see comment here about progress with NWS:

https://github.com/OpenWIS/openwis-documentation/issues/494#issuecomment-495215463

**Comment by jude2018** [comment]
Close as being tracked by #456
