### ISSUE TITLE
Action-SC-2017-73 Set up the bank account with a single signatory

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#343]
Set up the bank account with a single signatory - MDA

**Comment by rogers492** [comment]
Has this been done?

**Comment by jude2018** [comment]
@remygiraud @Stacey-Harvey - Hi both is complete or now superesed

**Comment by jude2018** [comment]
Hi @remygiraud and @Stacey-Harvey is there an update on this please?

**Comment by remygiraud** [comment]
Copy of an email sent to Openwis Board on 11/12/18

------
As you know, the money of the Association is currently managed by MFI as a temporary solution.

Matteo Dell'Acqua an I have been trying to open a bank account in Belgium with ING. 
To make a very long story short, opening and managing a bank account with ING for our Association is, I am now convinced, almost impossible. ING is asking for so many papers that will make our lives very difficult.

Luckily as the AISBL Openwis is exempted of VAT, we have no obligation to have a bank account in Belgium. This has been confirmed by our lawyers and by the tax man in Belgium.
Over the last few weeks, I have been working with MFI on both aspects : treasurer and bank account.

On both aspects, I have now a solution that needs your approval.

1. Treasurer
MFI has proposed that their accountant (Nathalie Dureisseix) acts as the Treasurer of our Association. During the Board meeting last year, we have agreed that Jude is our Project Manager and the MetOffice is compensated by a small fee for this task. We have been working with MFI along the same principle. MFI has estimated a charge of 1/2 day per month for day to day activities plus additional time when and if required. Based on previous experience (prepare board meeting, liaising with our tax adviser in Belgium,...) this extra activity will represent (probably) 6 to 8 days a year.
So, in total, it is a charge of (roughly) 14 days a year at 520€ a day. So 7280€ per year, rounded to 8k€ per year.

2. Bank Account
Considering our difficulties with ING, it appears to be much simpler and more efficient to continue with the management of our monies with MFI. MFI has proposed to create a dedicated bank account for the Association. They have asked for a name of this bank account. Not being too creative I suggest "AISBL Openwis" !
--------

I am still waiting from the Board members to approve both points.

**Comment by jude2018** [comment]
@remygiraud - have you received approval from the Board members?

**Comment by 6a6d74** [comment]
Bank account now set up by MFI with Societe Generale. Thank you Nathalie!!
