### ISSUE TITLE
Action-SC-2017-74 Move the funds from the MFI account to the ING account

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#344]
MDA - Move the funds from the MFI account to the ING account

**Comment by jude2018** [comment]
@remygiraud and @Stacey-Harvey is there an update on this please?

**Comment by Stacey-Harvey** [comment]
This is dependent on action SC-2017-74 regarding whether we need the ING account which @remygiraud is exploring

**Comment by remygiraud** [comment]
Considering  SC-2017-74, this action (if the solution presented in  SC-2017-74 is approved) can be closed.

**Comment by remygiraud** [comment]
Account with MFI proposal being endorsed by SC. Action closed.
