### ISSUE TITLE
Action-SC-2017-76 Travel to ING Brussels for face-to-face meeting

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#346]
Travel to ING Brussels for face-to-face meeting and become signatories of the Association bank account

**Comment by rogers492** [comment]
Any update on when this might happen?

**Comment by Stacey-Harvey** [comment]
Jeremy please can you come back to me with some preferred dates? It will probably be easier for me to move things around in my diary.

**Comment by 6a6d74** [comment]
@Stacey-Harvey apologies for my delay! I'll email you with some proposals.

**Comment by jude2018** [comment]
@remygiraud and @Stacey-Harvey is there any update please? :-)

**Comment by Stacey-Harvey** [comment]
This is dependent on action SC-2017-74 regarding whether we need the ING account which @remygiraud is exploring

**Comment by 6a6d74** [comment]
Closing this action. ING account no longer required.
