### ISSUE TITLE
Action-SC-2017-81 Initiate discussion on Risks to Association

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#351]
Either start a conversation on risks to the Association by email, or put the topic at the start of the next SC meeting, or both.

**Comment by jude2018** [comment]
Added [SC](https://github.com/OpenWIS/openwis-documentation/issues/383) and [Board](https://github.com/OpenWIS/openwis-documentation/issues/381) agendas for 2018 Annual Meeting. Therefore close.
