### ISSUE TITLE
Action-TC-2018-02 Inc a combined TC/PMC brainstorm session in Annual Meeting agenda

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#357]
Inc a combined TC/PMC brainstorm session in Annual Meeting agenda, to work on the future roadmap for OpenWIS

**Comment by jude2018** [comment]
Hi @solson-nws , Shall we discuss this as part of the items you are thinking of in the scrum (after the scrum is over) on Tuesday 1 May 2018 as Paul and I will both be present (both of us are not avilable on Thursday 3rd May)?

**Comment by jude2018** [comment]
Can this be closed now. @solson-nws ?

**Comment by rogers492** [comment]
Meeting complete.
