### ISSUE TITLE
Action-TC-2018-03 Check arrangements for Annual Meeting

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#358]
Ask FMI for info on:
1. Date and duration of meeting
2. Location
3. Facilities - just one meeting room or break-out rooms too?

**Comment by rogers492** [comment]
Emailed Mikko and Mikko on 1st Feb 2018.

**Comment by mvisa** [comment]
Hi,

as for the duration I think we need input from others. I suppose it would be the "standard" 4 days (2 x TC + 2 x SC) ? What about the board meeting?

**Comment by rogers492** [comment]
here goes our initial proposition:

-	16th – 20th April (2 x TC, 2 x SC, Board)
-	Location FMI premises in Helsinki (20min from airport)
-	One meeting room preliminary reserved (max. capacity 30)

How does this sound for you?

BR,
Mikko & Mikko

**Comment by woollattd** [comment]
It my sons 13th Birthday that week, so I'd prefer any other. :-) 
before or after

**Comment by rogers492** [comment]
Meeting arrangements confirmed by Mikko Partio at TC meeting Feb 2018:
1. Meeting arranged for week beginning Monday 28th May 2018.
2. Location is: FMI, Helsinki, Finland.
3. One room with wi-fi has been booked.
4. Format: PMC-OpenWIS; TC; SC; Board Meeting.

**Comment by rogers492** [comment]
Hi @mvisa Would you be able to send an official letter of invitation, some members will need that soon to start booking their trip.

Also, do you have any recommendations for hotels that are convenient for the meeting location?

thanks,
Paul

**Comment by mvisa** [comment]
Hi, we have an internal planning meeting tomorrow. So, tomorrow afternoon or thursday I'll send more details including hotel recommendations (basically any hotel in the city center will do).

BR,
 Mikko

**Comment by rogers492** [comment]
From @mvisa :+1: 
As for practical information, it will probably be much the same as the info for EGOWS 2016 meeting, which can be found here: https://agora.fmi.fi/display/EGOWS16/Accommodation+and+Getting+to+FMI . Hotels mentioned here are selected based on location, but basically any hotel in the city center will get you to FMI in 30 minutes or so.

 BR,
Mikko

**Comment by remygiraud** [comment]
Any news on the invitation letter? 
Thanks,
Rémy

**Comment by jude2018** [comment]
Hi @mvisa,

I have over from Paul and will be attending the Annual Meeting.  

I envisage that Stacey Harvey , who is the Accountant for OpenWIS Associatin will use WebEx or tele-conference to present the financial position, Annual Accounts of the OpenWIS Assoication, and discuss the budget.

In this regard, will the room have a speakerphone with the ability to diall a local number for a tele-conference call as a backup to WebEx?

 Best regards
Jude

**Comment by mvisa** [comment]
Hi, yes we can arrange a speakerphone with that availability however then you will apparently lose ability to share the screen.

BR,
 Mikko

**Comment by mvisa** [comment]
On Wednesday at 1PM we have to opportunity to make a short visit to our weather offices.

**Comment by jude2018** [comment]
Thanks Mikko.

This will be as a backup only,

Best regards

Jude


Jude Anthonisz  Senior Project Manager
Met Office FitzRoy Road Exeter Devon EX1 3PB United Kingdom
Tel: +44 (0)7824 414579
Email: jude.anthonisz@metoffice.gov.uk<mailto:jude.anthonisz@metoffice.gov.uk> Website: www.metoffice.gov.uk<http://www.metoffice.gov.uk/>

**Comment by jude2018** [comment]
All,

Jeremy and I are beginning to make travel arrangements and woud like to know which hotels are being booked by everyone (we will try to be at the same one, if possible)

**Comment by jude2018** [comment]
Hello my colleauges,
I submitted the attedance on the on-line registration for OpenWIS meeting.
I'll make it to join the meeting alone in full days as a delegate of KMA entrusted by my director, SI Ryong LEE, a board representative.
 
Thanks,
Sungsoo
 
====== Watching the Sky Friendly, Serving the People Faithfully ======
DO, Sungsoo ( 都 性 秀 )
Information & Communication Technology Division
Korea Meteorological Administration
 
Tel : +82-2-2181-0424
Cel : +82-10-2855-3357
E-mail : ssdo@kma.go.kr
61 Yeoeuidaebang-ro 16-gil Dongjak-gu
Seoul, Republic of KOREA

**Comment by rogers492** [comment]
Meeting complete.
