### ISSUE TITLE
Action-TC-2018-08 Check out whether there is a phone app for MQTT subs

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#365]
Check out whether there is a phone app for MQTT subscriptions, that we could use in the demo.

**Comment by rogers492** [comment]
Remy Giraud is checking this out.

**Comment by remygiraud** [comment]
Over the weekend, I have made some tests using my MQTT server at home.
With two apps available for free on the Play Store: MQTT Client and tasker you can:
- subscribe to a topic (after having configured the MQTT Broker) using MQTT Client
- do whatever you want when the message is received. You can eg have a popup on the screen of your phone.
MQTT Client provides a plugin for tasker. Then in tasker plenty of actions are available when receiving a message. Tasker is not the easiest tool to use, but, it is very powerful

**Comment by rogers492** [comment]
Done.
