### ISSUE TITLE
Proposed Agenda for 2018 Annual Meeting

### ISSUE THREAD

**Issue by rogers492** [OpenWIS/openwis-documentation#368]
## Agenda format version 1 - check foot of issue for latest version.

Meeting hosted by Finish Meteorological Institute (FMI), Helsinki, Finland; 28th May to 1st June 2018 (5 days)

| day | early morning | late morning | lunch | early afternoon | late afternoon | evening |
| - | - | - | -| - | - | - |
| Mon   | Welcome | OpenWIS-Core Project Management Committee | TBD | OpenWIS-Core Project Management Committee | OpenWIS-Core Project Management Committee | free |
| Tue |OpenWIS-Core Project Management Committee | OpenWIS-Core Project Management Committee | TBD | OpenWIS-Core Project Management Committee | OpenWIS-Core Project Management Committee | free |
| Wed | Technical Committee | Technical Committee | TBD | Steering Committee | Steering Committee | free |
| Thu | Steering Committee | Steering Committee | TBD | Board Meeting | Board Meeting | free |
| Fri | Board Meeting | Board Meeting | TBD | Travel | Travel | Travel |

**Comment by rogers492** [comment]
World clock times for the start of each session:

| Place| early morning | late morning | lunch | early afternoon | late afternoon | evening |
| --- | --- | --- | --- | --- | --- | --- |
| Helsinki | 09:00 | 11:00 | 13:00 | 14:00 | 16:00 | 18:00 |
| Washington | **02:00** | **04:00** | **06:00** | 07:00 | 09:00 | 11:00 |
| Exeter | 07:00 | 09:00 | 11:00 | 12:00 | 14:00 | 16:00 |
| Toulouse | 08:00 | 10:00 | 12:00 | 13:00 | 15:00 | 17:00 |
| Athens | 09:00 | 11:00 | 13:00 | 14:00 | 16:00 | 18:00 |
| Seoul | 15:00 | 17:00 | 19:00 | **20:00** | **22:00** | **00:00** |
| Melbourne | 16:00 | 18:00 | **20:00** | **21:00** | **23:00** | **01:00** |

**Comment by remygiraud** [comment]
Paul,
Thank you for putting this together. For this session we will split the work of the "old" TC in PMC and "new" TC. I agree we will need most of the technical effort on the PMC side (Monday/Tuesday) on this agenda. Do you think just a half day is sufficient for TC? We should have report from Openwis Core PMC and more importantly discuss new potential projects (eg openweather?). Otherwise, fine with this proposal.
Rémy

**Comment by mvisa** [comment]
FYI: dinner will be organized by FMI for tuesday evening.

**Comment by rogers492** [comment]
Ok thanks @remygiraud and @mvisa I'll post an updated agenda.

**Comment by rogers492** [comment]
## Agenda format version 2 - check foot of issue for latest version.

Meeting hosted by Finish Meteorological Institute (FMI), Helsinki, Finland; 28th May to 1st June 2018 (5 days)

| day | early morning | late morning | lunch | early afternoon | late afternoon | evening |
| - | - | - | -| - | - | - |
| Mon   | Welcome | OpenWIS-Core Project Management Committee | TBD | OpenWIS-Core Project Management Committee | OpenWIS-Core Project Management Committee | free |
| Tue |OpenWIS-Core Project Management Committee | OpenWIS-Core Project Management Committee | TBD | Technical Committee | Technical Committee | FMI dinner |
| Wed | Technical Committee | Technical Committee | TBD | Steering Committee | Steering Committee | free |
| Thu | Steering Committee | Steering Committee | TBD | Board Meeting | Board Meeting | free |
| Fri | Board Meeting | Board Meeting | TBD | Travel | Travel | Travel |

**Comment by jude2018** [comment]
## Proposed detailed Agenda

Meeting hosted by Finish Meteorological Institute (FMI), Helsinki, Finland; 28th May to 1st June 2018 (5 days)

| day | early morning | late morning | lunch | early afternoon | late afternoon | evening |
| - | - | - | -| - | - | - |
| Mon   | Welcome | OpenWIS-Core Project Management Committee | TBD | OpenWIS-Core Project Management Committee | OpenWIS-Core Project Management Committee | free |
| Tue |OpenWIS-Core Project Management Committee | OpenWIS-Core Project Management Committee | TBD | Technical Committee | Technical Committee | FMI dinner |
| Wed | Technical Committee | Technical Committee | TBD | Steering Committee | Steering Committee | free |
| Thu | Steering Committee | Steering Committee | TBD | [Board Meeting](https://github.com/OpenWIS/openwis-documentation/issues/378) | [Board Meeting](https://github.com/OpenWIS/openwis-documentation/issues/379) | free |
| Fri | [Board Meeting](https://github.com/OpenWIS/openwis-documentation/issues/380) | [Board Meeting](https://github.com/OpenWIS/openwis-documentation/issues/381) | TBD | Travel | Travel | Travel |

**Comment by rogers492** [comment]
Meeting complete.
