### ISSUE TITLE
Update website - Add a link to WIS2 implementation strategy from GitHub to the website

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#373]
[CBS-TECO-2018-Inf-5(1)-WIS2-Implementation-Approach_draft1.pdf](https://github.com/OpenWIS/openwis-documentation/files/1964167/CBS-TECO-2018-Inf-5.1.-WIS2-Implementation-Approach_draft1.pdf)
[ECOMET-item2.4-WIS-jtandy-v1.pptx](https://github.com/OpenWIS/openwis-documentation/files/1964168/ECOMET-item2.4-WIS-jtandy-v1.pptx)
[WIS-2.0-Strategy_en.pdf](https://github.com/OpenWIS/openwis-documentation/files/1964169/WIS-2.0-Strategy_en.pdf)

**Comment by rogers492** [comment]
Hi @jude2018 Are you able to clarify exactly where the links should be (on which website page)?

**Comment by jude2018** [comment]
@6a6d74 Is there a specific existing place/page on the existing web site where you think this should go?

**Comment by rogers492** [comment]
@6a6d74 @jude2018 Any update on where these links go?

**Comment by rogers492** [comment]
@6a6d74 @jude2018 If I get no response by cop 1/8/2018 I will add a new section on **strategy** to this page and put the links there: http://openwis.github.io/openwis-documentation/metrics/

**Comment by rogers492** [comment]
Closed by #483
