### ISSUE TITLE
Agenda - OpenWIS Technical Committee 2018 May

### ISSUE THREAD

**Issue by solson-nws** [OpenWIS/openwis-documentation#375]
Topics

1.  Review of CBS Teco and WIS 2.0 demo
2.  Progress report from ED
3.  Preparing for Annual OpenWIS TC Meeting in Helsinki.  
     a.  Structure change (What's envisioned day to day)
     b.  Draft topics for consideration and feedback.  Looking at soliciting feedback by May 18th.
     c.  The potential for surveys and need for help
4.  Forum web page (discourse)
5.  Open Discussion

**Comment by rogers492** [comment]
Meeting complete.
