### ISSUE TITLE
Agenda for 2018 Annual Meeting

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#396]
## Detailed Agenda

Meeting hosted by Finish Meteorological Institute (FMI), Helsinki, Finland; 28th May to 1st June 2018 (5 days)

| day | early morning 09:00 to 11:00| late morning 11:00 to 13:00| lunch | early afternoon 14:00 to 16:00| late afternoon 16:00 to 18:00| evening |
| - | - | - | -| - | - | - |
| Mon   | Welcome | [OpenWIS-Core Project Management Committee](https://github.com/OpenWIS/openwis-documentation/issues/399#issue-325337303) | TBD | [OpenWIS-Core Project Management Committee](https://github.com/OpenWIS/openwis-documentation/issues/399#issuecomment-391028102) | [OpenWIS-Core Project Management Committee](https://github.com/OpenWIS/openwis-documentation/issues/399#issuecomment-391028968) | free |
| Tue |[OpenWIS-Core Project Management Committee](https://github.com/OpenWIS/openwis-documentation/issues/399#issuecomment-391029758) | [OpenWIS-Core Project Management Committee](https://github.com/OpenWIS/openwis-documentation/issues/399#issuecomment-391031974) | TBD | [Technical Committee](https://github.com/OpenWIS/openwis-documentation/issues/400#issue-325350844) | [Technical Committee](https://github.com/OpenWIS/openwis-documentation/issues/400#issuecomment-391037758) | FMI dinner |
| Wed | [Technical Committee](https://github.com/OpenWIS/openwis-documentation/issues/400#issuecomment-391038276) | [Technical Committee](https://github.com/OpenWIS/openwis-documentation/issues/400#issuecomment-391038607) | TBD | [Steering Committee](https://github.com/OpenWIS/openwis-documentation/issues/397) | [Steering Committee](https://github.com/OpenWIS/openwis-documentation/issues/397#issuecomment-390923106) | free |
| Thu | [Steering Committee](https://github.com/OpenWIS/openwis-documentation/issues/397#issuecomment-390924418) | [Steering Committee](https://github.com/OpenWIS/openwis-documentation/issues/397#issuecomment-390924862) | TBD | [Board Meeting](https://github.com/OpenWIS/openwis-documentation/issues/398) | [Board Meeting](https://github.com/OpenWIS/openwis-documentation/issues/398#issuecomment-390958932) | free |
| Fri | [Board Meeting](https://github.com/OpenWIS/openwis-documentation/issues/398#issuecomment-390959678) | [Board Meeting](https://github.com/OpenWIS/openwis-documentation/issues/398#issuecomment-390959925) | TBD | Travel | Travel | Travel |

**Comment by mvisa** [comment]
As of this moment, the registered participants are: 

Do Sungsoo (KMA)
Stephan Siemen (ECMWF)
David Podeur (MF)
Benjamin Saclier (MF)
Steve Olson (NOAA)
Remy Gibault (MFI)
Jude Anthonisz (UKMO)
Remy Giraud (MF)
Jeremy Tandy (UKMO)
Mikko Visa (FMI)
Mikko Partio (FMI)

**Comment by jude2018** [comment]
>Frequenty Asked Questions (FAQs)

_1.  Joing the meeting remotely__

Participation links to webex as soon as we have all participants.

__2.  What's_ a nominal times for folks arrive at FMI?_  

I think this is up to us, would 9:00 be ok time to start?

_3.  What are the options for lunch break?  Is there a central cafeteria that we should use?  Are there restaurants close by?_

We have two restaurants in the building, they provide lunch between 11:00 and 13:30. Unfortunately there are not so much other viable restaurants close by our location.

_4.  Although we haven't accounted for it in the schedule, are there planned break times for coffee, bathroom breaks, etc?_

Yes, we have scheduled two coffee + snacks breaks at 10:30 and afternoon at 14:30.

_5.  Will the conference facilities we plan to use have a white board to support strategic discussions?_ 

Not sure, will check this. At least movable flap board can be arranged

_6.  Will the conference facilities have a project or a TV that a laptop can be connected to via HDMI (will a HDMI be available?)_
 
A projector with VGA/HDMI yes.

_7.  Is it possible to have a large bunch of ‘Post-It’ notes and marker pens (for the PMC worksops)_

Yes will arrange this

_8.  What do we need to enter the FMI building and who do we ask for?_

The service desk knows about the meeting and you will get a visitor card. We will also probably have one or two people in the morning directing OpenWIS people to the right room (same floor as entrance, just a few steps). No need for ID. 

_9.  How do we get access to Wifi?_

Wifi password will be provided in the meeting room.

**Comment by rogers492** [comment]
Meeting complete.
