### ISSUE TITLE
Agenda 2018 - Board Meeting

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#398]
>Slot 1 - 31st May 2018 14:00 to 16:00

1. Welcome and introductions 
2. Approval of agenda 
3. Declaration of delegates 
4. [Approval of previous minutes](http://openwis.github.io/openwis-documentation/minutes/2017-07-18-Agenda-OpenWIS-Board-Meeting-2017-July.html) 
5. [Outstanding actions](https://github.com/OpenWIS/openwis-documentation/issues?q=is%3Aissue+is%3Aopen+label%3A%22Board+Meeting%22+milestone%3A%22Before+Annual+Meeting+2018%22) 
6. OpenWIS Association Membership
    6.1 Status update - designation of current Partners
    6.2 Approve new Partners recommended by the SC
    6.3 Fees, subscriptions and contributions to become strategic or associate partner 
7. Election of Managing Directors 
8. Reports and recommendations from the SC 
   8.1 Review governance and compliance status escalated by the SC.

**Comment by jude2018** [comment]
>Slot 1 - 31st May 2018 14:00 to 1600

1. Welcome and introductions 
2. Approval of agenda 
3. Declaration of delegates 
4. [Approval of previous minutes](http://openwis.github.io/openwis-documentation/minutes/2017-07-18-Agenda-OpenWIS-Board-Meeting-2017-July.html) 
5. [Outstanding actions](https://github.com/OpenWIS/openwis-documentation/issues?q=is%3Aissue+is%3Aopen+label%3A%22Board+Meeting%22+milestone%3A%22Before+Annual+Meeting+2018%22) 
6. OpenWIS Association Membership
    6.1 Status update - designation of current Partners
    6.2 Approve new Partners recommended by the SC
    6.3 Fees, subscriptions and contributions to become strategic or associate partner 
7. Election of Managing Directors 
8. Reports and recommendations from the SC 
   8.1 Review governance and compliance status escalated by the SC.

**Comment by jude2018** [comment]
>Slot 3 - 1st June 2018 09:00 to 11:00
9. Annual accounts from 2017 (Treasurer) 
10. Review the budget set by the SC Chair.
11. Approve the 2018: annual budget, budget amendments and extraordinary expenditure; and reserve     fund (see Rule R10.7) , set membership fees
12. Financial controls for the OpenWIS Association  
12.1 Review SC recommendations to meet Belgian Requirements (suggest adding after ‘Taxation’ section) 
12.2 Review Benefit in Kind received by the Association (suggest adding after ‘Staff Costs’ section) 
13. Review and agree mitigation of OpenWIS Association risks, including those escalated by the SC.

**Comment by jude2018** [comment]
>Slot 4 - 1st June 2018 11:00 to 13:00

14. Review and agree mitigation of OpenWIS Association risks, including those escalated by the SC (continued)
15. Approve of changes to Internal Rules (see Rule A12.17) 
16. Any other business 
17. Confirm the host of next meeting 
18. Close

**Comment by rogers492** [comment]
Meeting complete.

**Comment by jude2018** [comment]
Hello my colleauges,
I submitted the attedance on the on-line registration for OpenWIS meeting.
I'll make it to join the meeting alone in full days as a delegate of KMA entrusted by my director, SI Ryong LEE, a board representative.
 
Thanks,
Sungsoo
 
====== Watching the Sky Friendly, Serving the People Faithfully ======
DO, Sungsoo ( 都 性 秀 )
Information & Communication Technology Division
Korea Meteorological Administration
 
Tel : +82-2-2181-0424
Cel : +82-10-2855-3357
E-mail : ssdo@kma.go.kr
61 Yeoeuidaebang-ro 16-gil Dongjak-gu
Seoul, Republic of KOREA

**Comment by jude2018** [comment]
From: Patrick Benichou <benichoup@mfi.fr> 
Sent: 30 May 2018 17:55
To: Rémy Giraud <remy.giraud@meteo.fr>
Cc: Loic Le Gallou <loic.legallou@mfi.fr>; gibault remy <gibaultr@mfi.fr>; openwis-sc@meteo.fr
Subject: [openwis-sc] Proxy for OpenWIS Board Meeting on May31-June01, 2018 to Remy Gibault, MFI

Dear Remy,


By the present email, I hereby authorize M. Rémy Gibault, MFI Head of Data Management systems, to represent Meteo France International in the meeting of the Board of Openwis Association which will be held on May31 and June 01, 2018  

Best regards

**Comment by jude2018** [comment]
[LETTRE NEW BOARD MEMBER FOR METEO-FRANCE IN OPENWIS AISBL.pdf](https://github.com/OpenWIS/openwis-documentation/files/2076251/LETTRE.NEW.BOARD.MEMBER.FOR.METEO-FRANCE.IN.OPENWIS.AISBL.pdf)
