### ISSUE TITLE
Action-SC-2018-1 Propose how to validate project proposals

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#401]
Discuss further how project like this proposal could operate in the future, taking into account the need to balance flexibility for internal development and the need for OpenWIS Association validation.

**Comment by jude2018** [comment]
@remygiraud and @6a6d74 - I have created a draft Charter. Any validation critera could be included in this template. https://github.com/OpenWIS/openwis-documentation/issues/499

**Comment by jude2018** [comment]
Please note the proposal below for creating a project from @benjaminsaclier via the TC (to be discussed at the SC in January 2019):

### This document describes the different steps of a project creation.
---------------------------------------------------------
Set up and submit a project proposal
---------------------------------------------------------
Formulating your proposals on a project charter document using the following template. Please note that the project charter is a minimal require document, feel free to add any others useful documents in your proposal.
Submit your proposal to the following email : contact@openwis.io, please add in the email subject the term : "Project proposal : name_of_your_project"

---------------------------------------------------------
Review of the project charter
---------------------------------------------------------
The openwis steering committee will review your proposal in a delay of one month.
The SC will determine if there is sufficient support from Members and Partners for the project and wheter the project is compatible with the purpose of the OpenWIS Association (provide link to purpose of Openwis Association)

After the review, you will receive an email which inform if the project has been approved or rejected or asking you to provide additional details 

---------------------------------------------------------
Constituting the task force
---------------------------------------------------------
The Openwis technical committee appoint mentor to PMC and allocate technical resources (if required) to the project.
The project Management Committee establish the project teams and contributors sign the "CLA" (provide link to the CLA).

---------------------------------------------------------
Minimum requirements
---------------------------------------------------------
A least the following elements will be create for the project :

    a GitHub repository to host project information, including documentation
    a license indicating how users can reuse code / software /documentation ...
    a README /project charter file

**Comment by benjaminsaclier** [comment]
**Decision/Action required**

1. The SC is asked to approve the text above ( _This document describes the different steps of a project creation._).
2. The SC is asked to approve the insertion of this text in Openwis project governance web page : http://openwis.github.io/openwis-documentation/rules2/2017-12-06-OpenWIS-Project-Governance.html
3. The SC is asked to approve the modification of Openwis web site "Projects" menu by adding new item : "Submit a proposal" which link to the Openwis project governance web page (to facilitate the navigation).

**Comment by jude2018** [comment]
Per SC 11 Jan 19 SC - @benjaminsaclier to merge the additional text with the existing text in  Project Governance riles supplement using a new branch and submit via  Pull Request in Github for approval

**Comment by jude2018** [comment]
Pull Request (https://github.com/OpenWIS/openwis-documentation/pull/520) awaiting approval by @6a6d74 and once approved can be closed.

**Comment by jude2018** [comment]
@6a6d74 - please approve this Pull Request

**Comment by 6a6d74** [comment]
Done.
