### ISSUE TITLE
Action-BM-2018-2 Introduction to IMD

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#403]
New president to introduce themselves to IMD.

**Comment by 6a6d74** [comment]
Ref. Remy's email to Dr Singh, (Thursday, 19 July, 2018)

> Dear Dr Singh,
> Thank you for signing the Agreement and joining the Openwis Association.
> At the last Board of the Openwis Association, I was elected as the new Chair of the Association.
> You may have heard that Matteo left Meteo-France and is now working at ECMWF on their relocation project.
> Therefore, he had to stand down from his Chair duties.
> Be assured that this won't change the future relationship between IMD and our Association.
> As the new Chair, I will signed the Agreement and send you back a copy as requested.
> I wish IMD a very warm welcome!!
> Best regards,
> Rémy
>

**Comment by jude2018** [comment]
Per SC meeting on 9 August 2018 - this issue is to be closed
