### ISSUE TITLE
Action-SC-2018-6 Create a risk management rules supplement

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#410]
Create a Risk management rules supplement based on ISSUE #227 https://github.com/OpenWIS/openwis-documentation/issues/227; and using the KANBAN board (Risk Log Project) https://github.com/OpenWIS/openwis-documentation/projects/4 … dashboard for Association-level risks. This would be be published alongside the other rules supplements at: http://openwis.github.io/openwis-documentation/rules2/

**Comment by rogers492** [comment]
Found myself with a spare half-hour so did this one. Closed by #429

**Comment by jude2018** [comment]
The SC agreed to review entire risk log twice-yearly.  If a risk (existing or new new) requires urgent attention this would be done ex-committee.
