### ISSUE TITLE
Action-SC-2018-7 set up a register of obligations to the Belgian Authorities

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#411]

**Comment by 6a6d74** [comment]
Document received from Vincent Corbeel - in French! 

Given that Treasurer and Board Chairman both speak french and all the legal stuff needs to be done in French, there's no point in translating at this time.

Remy will work through the list of compliance issues with Nathalie.

**Comment by 6a6d74** [comment]
@remygiraud - please attach Vincent Corbeel's document here.

**Comment by remygiraud** [comment]
Here is the document. In French. Sorry...

[20191217_AISBL_Openwis_Obligations_annuelles_taxes_documents.pdf](https://github.com/OpenWIS/openwis-documentation/files/3972877/20191217_AISBL_Openwis_Obligations_annuelles_taxes_documents.pdf)

**Comment by jude2018** [comment]
@remygiraud - just wondering whether this needs translation into English or will it be Ok to stay in French as both yourself and Nathalie will understand it?

**Comment by jude2018** [comment]
Per Sc of 16 Dec - agreed that having the French version is sufficient.  Therefore close.

**Comment by jude2018** [comment]
SC Mar 2020 - Legal advice received that the Association needs to follow procurement rules of a public body.

**Comment by jude2018** [comment]
Please also see #247
