### ISSUE TITLE
Action-SC-2018-8 update the risk log

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#412]
Update the risk log, determining owners for each risk and actions for the mitigations

**Comment by jude2018** [comment]
The risks were reviewed and updated as part of the 9 August 2018 SC meeting.

**Comment by 6a6d74** [comment]
Risk log to be reviewed during SC meeting in October 2019

**Comment by jude2018** [comment]
Close as being tracked by #555
