### ISSUE TITLE
Action-SC-2018-9 raise an invoice of 10,000 Euros for ECMWF Associate Partner fees

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#413]
Raise an invoice of 10,000 Euros for ECMWF Associate Partner fees for 2017 expenditure. The SC RESOLUTION was that these funds could paid into the ING bank.

**Comment by jude2018** [comment]
Please note the information estasblished in 2018 Board Meeting #415

**Comment by Stacey-Harvey** [comment]
I have today emailed @StephanSiemen to request details of where the invoice needs to be addressed and then sent to

**Comment by Stacey-Harvey** [comment]
@StephanSiemen has come back to me with the details. Have requested the remaining bank details which I need before I can send the invoice (IBAN and SWIFT).

**Comment by jude2018** [comment]
The SC meeting on 9  August 2018 agreed that the 10k Euros is the correct amount to be invoiced to ECMWF as ECMWF actually joined in 2018 and to close this issue

**Comment by jude2018** [comment]
The SC meeting on 9 August 2018 agreed that the invoice should be paid into the MFI bank account as the position with the ING bank is being progressed

**Comment by jude2018** [comment]
@Stacey-Harvey - can this be closed now ?

**Comment by Stacey-Harvey** [comment]
Yes this invoice has been sent and paid
