### ISSUE TITLE
Action-SC-2018-13 schedule SC meetings quarterly  

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#418]
Schedule quarterly tele-conferences and cancel if there is nothing important to discuss.

**Comment by jude2018** [comment]
Please see #419 for proposed agenda topics for the July 2018 SC

**Comment by 6a6d74** [comment]
Next meeting proposed for October 2018.

@jude2018 to identify specific date.

**Comment by jude2018** [comment]
Unable to schedule meeting in October 2018.  Next meeting scheduled for Janaury 2019

**Comment by jude2018** [comment]
We are proposing to have the annual meeting in either March or April 2019.  

So, as we have have made decisions/recommendations to the Board on key areas (i.e. new Treasurer, budget for 2019, approval of some Project Charters, bank account and GDPR), I propose that unless there is something urgent, that we have the next SC meeting as part of the annual meeting.

**Decision required** - SC to decide on this proposal or suggest alternatives 
@6a6d74 @remygiraud @wqu-bom @Stacey-Harvey @SungsooDO 

•	Loïc Le Gallou (LG), Météo France International (MFI)
•

**Comment by remygiraud** [comment]
Agreed. We need to define the week of the meeting though.

**Comment by jude2018** [comment]
I suggest the week starting Monday 13 May 2019 (assuming that everyone is OK with the annual meeting meeting being in that week)

**Comment by jude2018** [comment]
All have agreed that the annual meeting should be in wc 20 May 2019. Therefore close
