### ISSUE TITLE
Action-SC-2018-15 next annual meeting

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#420]
For the next face to face meeting NWS is the next host.  

Check whether hosting is possible.  Kari will report back at the next SC (teleconference in July 2018).  The SC are aiming for March 2018.

**Comment by 6a6d74** [comment]
@solson-nws talking with his International Relations team today. Expecting the meeting to be hosted at the Silver Spring facility - not College Park where the developer conference was held.

Aiming for a meeting in March / April 2019 - pending confirmation of when the conferencing facilities are available.

**Comment by jude2018** [comment]
Per SC 9Aug18 - NWS is identifying the most suitable venue and a series of available dates in March and April 2019.

@solson-nws will communuicate the available dates establish the most suitable datefor attendees, via a poll, by mid-September 2018

**Comment by solson-nws** [comment]
I have two proposed dates for next annual meeting:

Week of March 25th
Week of April 1st

Please comment on availability for both weeks
Steve

**Comment by jude2018** [comment]
@remygiraud  and others - the reason for scheduling the meeting in either April or May 2019 was for it to be near to the end of the current OpenWIS Association financial year

**Comment by jude2018** [comment]
Just noticed that Easter in 2019 during one of the proposed time-slots for the annual meeting

**Comment by jude2018** [comment]
_Context_

- It is not clear when NWS it will be possible to communicate with Steve or Kari given the current situation.  Therefore we are not in a position to confirm the date of the annual or the venue.

- The proposed dates or March or April 2019 look difficult due to coinciding with WMO meetings.

_Options_

Some options:
1. Wait until we hear from Steve or Kari and then schedule the date for the annual meeting.
2. Identify suitable dates for the annual meeting in May 2019 and an alternative hosting location as contingency by early February 2019.
3.  Identify suitable dates in May 2019 and confirm an alternatice hosting location by early February 2019.

_Recommendation to the SC_
My proposal is that we go for option 2 to give some and time opportunity for NWS to be able to respond.

**Decision required by SC** - Agree with the recommendation or suggest an alternative.

**Comment by remygiraud** [comment]
I would suggest to block a week late May. And then, wait for NWS to come back to us (before mid-February) if the week is fine and otherwise propose a back up location. So, something between 2 and 3!

**Comment by jude2018** [comment]
So, in terms of blocking a week, I sugguest either the week starting 13 or 20 May 2019 to avoid bank holidays.

**Comment by SungsooDO** [comment]
Agreed. The suggested either week in May is OK for KMA.

**Comment by jude2018** [comment]
I have had confirmation from all partners that the week starting 20 May is OK for everyone.  @solson-nws has also confirmed the venue, please see below on 1 February 2019:

> Good Morning Jeremy, Remy, Jude and Benjamin:
> 
> I've arranged NWS conference rooms in SSMC3 (Building 3) Silver Spring, Maryland for May 20-24th.  Please let me know if this works, and I'll send the broadcast announcement out to TC, SC members.  There may be options to have lunch catered.  I'll look into that.  Otherwise, there are plenty of local options available.  
> 
> Also, because I was able to find conference rooms in Building 3, these are located in an area outside of security, so we don't have security forms to fill out this go around.
> 
> Let me know if you have any questions and if this time works for you
> 
> Many thanks!
> 
> Stevfe__
> 
>

**Comment by mvisa** [comment]
So is it safe to plan the trip assuming the meeting starts on Monday or was there still uncertainty about this?

**Comment by jude2018** [comment]
Hi all,

Following today's PMC meeing, the high level agenda for the annual meeting is as follows:

- Monday 20th May 2019 - PMC
- Tuesdsy 21st May  2019 - TC
- Wednedsay 22nd May 2019 - SC
- Thursday 23rd May 2019 - Board
- Friday 24th May 2019 - Travel

**Comment by solson-nws** [comment]
Closing this issue.  Annual meeting set for week of May 20-24, 2019 in Silver Spring, MD in SSMC3
