### ISSUE TITLE
Action-SC-2018-18 place VAT documents in DropBox for Business

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#424]
Once the DropBox for Business service is in place for secure storage of Contributor Licences, place the VAT related documentation in this DropBox repository.

**Comment by jude2018** [comment]
@remygiraud @Stacey-Harvey - could you please confirm whether we need a DropBox service just VAT documents?

Context - the intention was to store completed CLA forms in DropBox (see #465), however, there is already a process in place to securely store completed CLA forms securely in github (see #457)

**Comment by 6a6d74** [comment]
@jude2018 - is there an update on this issue ahead of the SC meeting next week? Thank you.

**Comment by jude2018** [comment]
Per SC 9 AUgust 2018 - agreed that once the legal position on the European legilislation regarding personal information (GDPR) https://github.com/OpenWIS/openwis-documentation/issues/459 is known it will be possible establish whether a secure form of storage (such as DropBox) is needed for storage of VAT, CLAs https://github.com/OpenWIS/openwis-documentation/issues/465, or other information stored by the OpenWIS Association.  

This legal advise from the Met Office is expected at the end of August 2018.

**Comment by 6a6d74** [comment]
SC May-2019 assigned action to Loic to purchase the Dropbox for business account.

**Comment by jude2018** [comment]
Closing this issue as replaced by #550
