### ISSUE TITLE
Action-SC-2018-20 add ECMWF to the website

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#426]
i.e this page - http://openwis.github.io/openwis-documentation/structure/members.html

**Comment by rogers492** [comment]
And while adding ECMWF, add the new section for 'Associate Partners'.

**Comment by rogers492** [comment]
ECMWF website branding currently uses white lettering on a black background - so I assume this is the logo to use on the partners page.

![ecmwf](https://user-images.githubusercontent.com/2955702/41659236-9ba04db4-7490-11e8-8a57-5e3d993efe3d.png)

**Comment by rogers492** [comment]
The name of the centre on the website is spelled with a hyphen and then capital R for the word range, thus:
European Centre for Medium-Range Weather Forecasts.

**Comment by rogers492** [comment]
Closed by #478
