### ISSUE TITLE
Action-SC-2018-22 change the membership web page

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#428]
The page title of the membership page of the website need to be altered the Page Title ‘OpenWIS Members and Partners’; the Sub Heading is ‘members’ instead of ‘core founders’; and a new sub-heading added to say  ‘Associate partners’, i.e. on this page -  http://openwis.github.io/openwis-documentation/structure/members.html)

**Comment by rogers492** [comment]
Closed by #437 (Assoc Partners change moved to Issue #426)
