### ISSUE TITLE
Action-SC-2018-23 update the “responsibilities” rule supplement and the “Project Initiation” PowerPoint slide

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#430]
From a recap of #185 and the [MS PowerPoint slides](https://github.com/OpenWIS/openwis-documentation/files/2025875/OpenWIS.Association.governance.pptx),“responsibilities” rule supplement and the “Project Initiation” PowerPoint slide by amending the wording for membership of PMC; remove word “initially” and append a statement “membership may evolve over time”; also change “participating” to “sponsoring” is needed.

**Comment by 6a6d74** [comment]
retrospectively closing.
