### ISSUE TITLE
Action-SC-2018-24 update the “responsibilities” rule supplement and the “Project Operation” PowerPoint slide

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#431]
From a recap of #185 and the [MS PowerPoint slides](https://github.com/OpenWIS/openwis-documentation/files/2025875/OpenWIS.Association.governance.pptx) amends to reflect:

The approval of [software] releases by a Project is optional - it will depend on the release regime agreed with the SC during the initiation of the Project; e.g. self-assessment by PMC.

“Project Operation” slide currently only describes software releases; OpenWIS Projects may be “study” activities - use “project deliverables” in place of “software package(s)” and amend TC responsibility regarding “validation of technical design and implementation” etc.

Also see #430

**Comment by 6a6d74** [comment]
retrospectively closing.
