### ISSUE TITLE
Action-SC-2018-32 create project charter for AMQP

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#440]

**Comment by remygiraud** [comment]
**Background**
During its 2018 session, the Steerin Committee agreed to launch a study on AMQP and its potential use with WIS2.

Therefore, a draft Project Charter is attached for the the SC to consider.

**Comment by jude2018** [comment]
Draft Project Charter for approval at the SC in Aug 18
[20180808_AMQP_ProjectCharter_DRAFT.docx](https://github.com/OpenWIS/openwis-documentation/files/2270915/20180808_AMQP_ProjectCharter_DRAFT.docx)

**Comment by remygiraud** [comment]
Following the SC meeting on Aug. 8th, a DRAFT2 is published. Please check whether you are in agreement with the Project charter and willing to join.

[20180809_AMQP_ProjectCharter_DRAFT2.docx](https://github.com/OpenWIS/openwis-documentation/files/2274339/20180809_AMQP_ProjectCharter_DRAFT2.docx)

**Comment by remygiraud** [comment]
I will send that DRAFT2 to DWD and Canada to check whether they are interested in participating.

**Comment by jude2018** [comment]
Hi @remygiraud @benjaminsaclier - I suggest we use this method to track the project -https://github.com/OpenWIS/openwis-documentation/projects/1?

**Comment by jude2018** [comment]
Per 11 Jan 19 SC - Project Charter approved by SC

**Comment by jude2018** [comment]
Per 11 Jan 19 SC - JA to convert the AMQP Charter document and publish under a 'projects' tab on the OpenWIS website.  Also see #499

**Comment by jude2018** [comment]
**Project Charter for AMQP**

***Aim***

**Comment by jude2018** [comment]
Markdown version of Charter now available for publishing on OpenWIS Association website

**Comment by 6a6d74** [comment]
Project is operating under the agreed charter.
