### ISSUE TITLE
Action-SC-2018-34 review and update goals and metrics

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#442]
The SC suggested the following new goals:

1. OpenWIS Association to influence and inform the design of WIS2. A metric is required.

2. Increase the number of OpenWIS Association partners. A proposed metric for this goal - have a clear value offering for the WMO community.

3.  Encourage active contribution from all Members and Partners. Suggested metrics and mechanisms:
- Metric moving toward more equitable contributions; balanced in-kind contributions.
- Metric: see the accounts
- Metric: technical contributions on GitHub
- Mechanism: to share insight within OpenWIS Association Members and Partners gained by each organisation from their own works (e.g. in OGC, WMO Expert Teams, INSPIRE MIG etc.)

**Comment by jude2018** [comment]
Are we happy to use these suggested goals and metrics (discussed at the last annual meeting in Helskinki (i.e. in May 2018)?

**Comment by remygiraud** [comment]
OK and to be reviewed during the next face 2 face.

**Comment by 6a6d74** [comment]
Action deferred until SC meeting in October 2019.

**Comment by jude2018** [comment]
Per SC 16 Dec 19 - Agreed that the 3 goals proposed at the last annual meeting are still relevant and work on CICD, Middleware and AMQP reflect metrics for goals 1 and 3.  Goal 2 is also relevant and agreement in principle to OpenCDMS could once confirmed form relevant metrics. 

Therefore close.
