### ISSUE TITLE
Action-BM-2018-5 send latest correspondence to new president

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#443]
CMA - Latest position not known.  There is an outstanding action to send CMA copies of the Articles of Association and Internal rules.  

MSC -   Latest position is not known.  

Mattéo to send all correspondence to new president (i.e. Rémy Giraud)

**Comment by remygiraud** [comment]
CMA: I will send the link to the documents to Li Xiang. Hopefully, with the TT-eWIS meeting in Beijing we will be able to move forward with CMA.
With DWD and EC (Canada), I am waiting for the Project Charter on AMQP to be approved to contact them as it might be good candidate for cooperation with them. The idea being for them to "taste" what working together may mean without effectively joining the association.

**Comment by jude2018** [comment]
@remygiraud - any update on this Rémy?

**Comment by 6a6d74** [comment]
Remy has received as much correspondence as he will get.
