### ISSUE TITLE
Action-TC-2018-13 re-align web site pages on technical rules and development process

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#449]
review web wite to ensure that the interactions between the technical rules, code of conduct, and development processes are easy to understand.

**Comment by solson-nws** [comment]
Please see attached MS Word
[Restructure location of OpenWIS webpage content.docx](https://github.com/OpenWIS/openwis-documentation/files/2340531/Restructure.location.of.OpenWIS.webpage.content.docx)
 document for proposed webpage redesign ideas

**Comment by solson-nws** [comment]
Steve will generate a pull request, and update webpage location/information.  There is still time to comment.  Steve will commit changes just before November TC meeting.  We will examine changes at the November TC meeting.

**Comment by solson-nws** [comment]
@solson-nws :  Move TR pieces to openwis-core.  Need to add statement that all projects define a set of technical rules and specifications they will adhere to and refer back to Openwis-core.

**Comment by jude2018** [comment]
Close as @solson-nws has updated the web site
