### ISSUE TITLE
Action-TC-2018-18 ensure that release management documentation is accessible

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#454]
Existing release management documentation in the Wikki which needs to be acceesible, so consider linking or publishing on the website. 

Note #449

**Comment by tg4444** [comment]
The tool you can use is [GREN](https://github-tools.github.io/github-release-notes/).

Its main focus is to provide release management for github projects. It does so by creating a release (and the related notes), based on one of the following:
- The issues closed in the time between two repository tags were created
- The commits performed in the time between two repository tags were created
- If issues are marked with milestones, release notes for a specific milestone can be created (more fine-grained control than by depending on dates)

Please note that by using the `release` command, you will actually be doing a release on github.
If you are only interested in the release notes though, you can generate a change-log file locally by using the `changelog` command, like this :

```
gren changelog --generate --override --changelog-filename=CHANGELOG.md --tags=all
```

The above will create a `CHANGELOG.md` file with release notes based on `the issues closed between the dates the tags were created` (default behavior), for `all` tags (specified by `--tags=all`)

You can find more information at [this](https://github-tools.github.io/github-release-notes/examples.html) page

**Comment by solson-nws** [comment]
@jude2018 @woollattd  Do we know if this has been incorporated yet?  Or is this something we still need to do?  Or did ED not only document how to do it, but actually implement it?

Steve

**Comment by jude2018** [comment]
@solson-nws and @jude2018 to investiagte on finding is already available.

@woollattd to document what has been done before.

**Comment by solson-nws** [comment]
@solson-nws @jude2018 @benjaminsaclier  --> Cross link this with #529

**Comment by jude2018** [comment]
Review after  CICD work is complete

**Comment by solson-nws** [comment]
Upon completion of CI/CD training, the openwis-documentation wiki webpage will be updated with new links to documentaiton for the rrelease process.  Recommend closing this issue after this work is completed.

**Comment by jude2018** [comment]
Per TC of 18 May 2020 - With regard to _'Project design authority, standards compliance, and release management: status, review and recommendations'_ @solson-nws to provide an update a future TC on a description of a better workflow and guidance for all contributors.

**Comment by jude2018** [comment]
@solson-nws and @benjaminsaclier any update on this ?

**Comment by jude2018** [comment]
23 Nov 2020 - Look to close this alongside closure of #581 @solson-nws @benjaminsaclier

**Comment by solson-nws** [comment]
Here is the final updates to development and release Guidance.  With this finalized doc, will close this ticket.  Will discuss at January TC meeting and then update in gh-pages.  Closing this ticket.
[OpenWIS Development Process Final.docx](https://github.com/OpenWIS/openwis-documentation/files/5704722/OpenWIS.Development.Process.Final.docx)
