### ISSUE TITLE
Action-TC-2018-19 create a web page that shows a repeatable process

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#455]
A means of clarifying where and how development and technical quality is considered in the development and project life cycle. This will be a 3-column table, in a new web page:

- measure
- List of references
- where and how quality is measured

Note #449

**Comment by solson-nws** [comment]
The repeatable process should be end to end.  

Nominally, here are the elements open for discussion:

**Project Charter Template:**  https://docs.google.com/document/d/1CYmh3VtfiuorOV12_eXE-VJ8me2kfa1jNfeGiaJi-YQ

**Approval Process:**  Jeremy Diagram (PMC -->  TC  --> SC for approval)

**Allocation of Resources:**  creation of github area/issue/etc, formation of team, identification of lead,, kanban board

**Development Process:**  [](https://openwis.github.io/openwis/)

**Release Management:**  [](https://github.com/OpenWIS/openwis-deploy/wiki)  **and** newer CI/CD:  [](https://github.com/OpenWIS/openwis-deploy/wiki/OpenWIS-CI-CD)

**Issue Tracking:**  github issues

**Reporting:** : [](https://github.com/OpenWIS/openwis-deploy/wiki/OpenWIS-Cloudbees-Testing-Configuration)

Tracking Quality:  Based on [](https://github.com/OpenWIS/openwis-documentation/issues/395)

**Comment by jude2018** [comment]
Cannot access Google docs

**Comment by jude2018** [comment]
Per Technical Committee of September 2018 - @solson-nws to Ato create a demo for approval by TC and SC

**Comment by solson-nws** [comment]
@solson-nws  --> No objection.  Add to website as breakout section and close issue.

**Comment by 6a6d74** [comment]
> Approval Process: Jeremy Diagram (PMC --> TC --> SC for approval)

See [**OpenWIS® Project Governance** rule supplement](http://openwis.github.io/openwis-documentation/rules2/2017-12-06-OpenWIS-Project-Governance.html)

"Initiation of new Projects" and "Governance for Project deliverables and releases" both have flowchart diagrams: [Here](http://openwis.github.io/openwis-documentation/assets/OpenWIS_Association_governance-project_initiation.pdf) and [here](http://openwis.github.io/openwis-documentation/assets/OpenWIS_Association_governance-project_operation_(software_release_cycle).pdf) respectively.

**Comment by jude2018** [comment]
Agreed to close
