### ISSUE TITLE
Action-TC-2018-19 Ensure that all oustanding CLAs are completed

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#456]
Need for all oustsnding CLAs to be completed within 2 months (i.e. by end July 2018).

**Comment by jude2018** [comment]
@solson-nws - please ensure this is on the next TC agenda (please note - @benjaminsaclier)

**Comment by jude2018** [comment]
Please see the relates issue -https://github.com/OpenWIS/openwis-documentation/issues/190

**Comment by jude2018** [comment]
@solson-nws has chased MFI @remy-gibault and ECMWF @StephanSiemen

**Comment by jude2018** [comment]
CLA fro,m FMI received and uploaded to github on 7 Jan 18

**Comment by jude2018** [comment]
CLA for UK Met Office uploaded (including past contributors)

**Comment by jude2018** [comment]
@remy-gibault , @solson-nws , @klsheets @StephanSiemen @kuldeep-sri @wqu-bom - please upload CLAs for your respective organisations (ensuring all contributors, including those have made contributions in the past are also listed in your CLA).

**Comment by jude2018** [comment]
CLA from IMD received and uploaded @kuldeep-sri

**Comment by jude2018** [comment]
A reminder to upload CLAs for your respective organisations (please include inidividuals who have contributed in the past) @remy-gibault , @solson-nws , @klsheets @StephanSiemen @wqu-bom

**Comment by StephanSiemen** [comment]
@jude2018, ECMWF one has been uploaded

**Comment by jude2018** [comment]
@remy-gibault please add Nathalie Nathalie Dureisseiux @dureisseixn to MFI's CLA before you upload it.

**Comment by jude2018** [comment]
So, just NWS, MFI and BoMs CLAs need to be uploaded.

**Comment by jude2018** [comment]
@solson-nws @wqu-bom and @remy-gibault - could you please update a completed CLA for your organisations?

**Comment by jude2018** [comment]
@wqu-bom - thanks for submitting BoMs CLA

@remy-gibault  and @solson-nws - please note that CLA uploads are needed for NWS and MFI

**Comment by jude2018** [comment]
From: Kari Sheets - NOAA Federal <kari.sheets@noaa.gov> 
Sent: 21 May 2019 17:38
To: Tandy, Jeremy <jeremy.tandy@metoffice.gov.uk>; Fred Branski - NOAA Federal <fred.branski@noaa.gov>; Steve Olson <steve.r.olson@noaa.gov>; Rémy Giraud <remy.giraud@meteo.fr>; Anthonisz, Jude <jude.anthonisz@metoffice.gov.uk>
Subject: Action Items from CLA tag-up

Action 1 - do a comparison of CLA v2 and v3
Action 2 - Send CLA version 1 to NOAA legal
Action 3 - Review feedback from NOAA legal with SC (Jeremy et a)
Action 4 - Review feedback with UKMet legal

Action 5- get a copy of the strategic partnership agreement where NWS joined the consortium

Fred on point for the US at this point.

Kari


-- 
Kari Sheets, PMP
Integrated Dissemination Program - Geographic Information Systems  
NOAA National Weather Service
U.S. Department of Commerce
301-836-2368

**Comment by jude2018** [comment]
Per TC on 21 May - @loiclg to upload CLA for MFI

**Comment by jude2018** [comment]
@loiclg @remy-gibault - Have you been able to upload MFI's CLA?

@solson-nws - is there an update on the NWS CLA?

**Comment by jude2018** [comment]
@solson-nws and @klsheets - any update please ?

**Comment by jude2018** [comment]
Per TC of 19 May - @6a6d74  and Fred Branski (NWS) to co-ordinate a discussion between UKMO and NWS Legal teams to reach agreement on wording within the CLA to enable NWS to sign the CLA..

**Comment by Steve-Palmer** [comment]
New issue #601 opened which will influence the agreement on wording coordinated by @6a6d74 and Fred Branski (NWS).

**Comment by jude2018** [comment]
Per SC of 29 Sep and Board of 1 Oct - Agreed to complete this by the early December 2020 SC.  Please note that the SC and Board acceptable the proposes changes in #601

**Comment by jude2018** [comment]
Close as monitored by #494
