### ISSUE TITLE
Action-TC-2018-20 check CLA process with paul rogers

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#457]
online form - what is the process? (i.e. how does it sent out? who signs it? and how is it stored?)

Also see #465

**Comment by rogers492** [comment]
@jude2018 The CLA is Annex A to the Internal Rules, so is at the foot of this page: http://openwis.github.io/openwis-documentation/rules/

If you follow the link and read right through you will see various links that take you to explanations of the various parts of the CLA process and tell you where things are stored etc.

**Comment by jude2018** [comment]
@solson-nws - please see this and feedback whether this negates need for dropbox service as the signed CLAs are stored in Github
@remy-gibault - please note before setting up any email accounts

**Comment by jude2018** [comment]
@solson-nws - the actual process is here - http://openwis.github.io/openwis-documentation/static/CLA/CLAprocess.html

**Comment by jude2018** [comment]
Per SC 9 August 2018 - agreed that once the legal position on the European legilislation regarding personal information (GDPR) #459 is known it will be possible establish whether a secure form of storage (such as DropBox) is needed for storage of VAT, CLAs #465, or other information stored by the OpenWIS Association.

This legal advise from the Met Office is expected at the end of August 2018.

**Comment by jude2018** [comment]
TC on 12 Sep 18 agreed that this action can close as the current CLA process has been clarified.  It was acknolwegded the use of Dropbox or other changes to the CLA process could arise as a result of asessing the GDPR implications
