### ISSUE TITLE
Action-PMC-2018-1 establish implications from GDPR legislation

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#459]
For example the use of LDAP search to manage email lists.  This brings about the wider question about managing personal data (for European Union countrues at least).  So, clarity is needed what compliance is necessary.  This will inform any action necessary regarding manageing personal data in OpenWIS.

**Comment by jude2018** [comment]
Initial discussion with Legal team in Met Office.  Follow up meeting scheduled for 23 August 2018

**Comment by jude2018** [comment]
An update from consultation with Met Office legal:

The General Data Protection Regulation (GDPR) is a regulation in EU law on data protection applicable to the European Union and the European Economic area, and, as such, applies to Open Wis, a not for profit organisation incorporated in Belgium.

Belgium has recently implemented a new national data protection law following the implementation of the GDPR (similar to the UK Data Protection Act 2018).  Met Office Legal provide further information with regard to any applicable derogations from the GDPR.

A summary of the areas that need to be considered by the OpenWIS Association are:

1.      What personal data is processed (personal data being defined under the GDPR as “any information 
         relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person 
         is one who can be identified, directly or indirectly, in particular by reference to an identifier such as     
         a name, an identification number, location data, an online identifier or to one or more factors 
         specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that     
         natural person”)?

2      Does any of the above processing include information about children (under the age of 13)?

3.	How is personal data collected and is a notice provided to individuals at the time of data collection 
        detailing how their personal data will be used?

4.	How would you action a request from an individual exercising their rights under the GDPR, for 
        example, what information is held about them, deletion of their data, correction of their data?  Who 
        would action these requests?

5.	What retention periods apply to the processing of personal data?  Do you have a process for 
       deleting personal data no longer required?

6.	What technical/security measures do you have in place to protect personal data from being 
        compromised?

7.	Are there any third party processors involved? 

8.	The OpenWIS Associations should consider the implementation of a process for data breach 
        recording and reporting.

9.	Who will take responsibility for data protection compliance?


I will continue to work with Met Office Legal to provide answers to the questions raised to get a recommendation on what specific actions we (i.e. th eOpenWIS Association) need to take.

**Comment by jude2018** [comment]
1) items for CLA; names and email addresses of of representatives for each participating organisations in correspondecne and meeting minutes that are on the OpenWIS Association web site, Github repository and forum (Discourse).

2) Not intentionally. May need explicit procedures to be developed.  UK Legal to check position for Belgium regarding the age.

3) Procedures are referred to here for joining the OpenWIS Association- http://openwis.github.io/openwis-documentation/structure/governance.html.  Procedures for the CLA are here - http://openwis.github.io/openwis-documentation/static/CLA/CLAform.html.  The aspect that needs to be added to the website is a statement of personal data will be used once collected, retained and removed.

4) A process for dealing with requests needs to be added along who will deal with requests to ensure that responses are dealt within one calendar month.

5) Need to check arrangements for the duratrion of particiapting organisation and for other contributors.

6) Github is used for storing personal data. UK Legal to check position regarding Github. Need to establish regaring Discourse from @solson-nws.

7) Github and Discourse

8) This is to be developed along side procedures referred to in no.4, above.

9) Assumed that a designated individual will be identified that will ensure compliance and carry out tasks for no.s 4 and 8.
 
I will continue to work Met Office Legal on these items

**Comment by jude2018** [comment]
Definitions, for information and context: 

A data controller is a person, company, or other body that determines the purpose and means of personal data processing (this can be determined alone, or jointly with another person/company/body).

A data processor is a person or organisation who deals with personal data as instructed by the controller for specific purposes and services offered to the controller that involve personal data processing.

**Comment by jude2018** [comment]
2) Not intentionally. **_Decision required - the Association needs to decide whether to accept members who are aged 13 or below and ensure if under 13 that a procedure is in place._**

3) Procedures are referred to here for joining the OpenWIS Association- http://openwis.github.io/openwis-documentation/structure/governance.html.  Procedures for the CLA are here - http://openwis.github.io/openwis-documentation/static/CLA/CLAform.html.  **_The aspect that needs to be added to the website is a statement of personal data will be used once collected, retained and removed._**

4) A process for dealing with requests needs to be added along who will deal with requests to ensure that responses are dealt within one calendar month. **_Requirment - The Association needs to understand who the contact point will be., along with complaints procedure in a Privacy Notice._**

5) Need to check arrangements for the duratrion of particiapting organisation and for other contributors. Requirement.

6) Github is used for storing personal data. UK Legal to check position regarding Github. Need to establish regaring Discourse from @solson-nws.

7) Github and Discourse
.  
8) This is to be developed along side procedures referred to in no.4, above.

9) Assumed that a designated individual will be identified that will ensure compliance and carry out tasks for no.s 4 and 8.
 
I will continue to work Met Office Legal on these items

**Comment by jude2018** [comment]
**3) Procedures are referred to here for joining the OpenWIS Association**- http://openwis.github.io/openwis-documentation/structure/governance.html.  Procedures for the CLA are here - http://openwis.github.io/openwis-documentation/static/CLA/CLAform.html.  **_The aspect that needs to be added to the website is a statement of personal data will be used once collected, retained and removed._**

**Comment by jude2018** [comment]
4) A process for dealing with requests needs to be added along who will deal with requests to ensure that responses are dealt within one calendar month. **_Requirment - The Association needs to understand who the contact point will be., along with complaints procedure in a Privacy Notice._**

**Comment by jude2018** [comment]
**5) Need to check arrangements for the duratrion of particiapting organisation and for other contributors.**

**Comment by jude2018** [comment]
6) Github is used for storing personal data. UK Legal to check position regarding Github. Need to establish regaring Discourse from @solson-nws.

**Comment by jude2018** [comment]
**7) Github and Discourse**

**Comment by jude2018** [comment]
**8) This is to be developed along side procedures referred to in no.4, above.**

**Comment by jude2018** [comment]
9) Assumed that a designated individual will be identified that will ensure compliance and carry out tasks for no.s 4 and 8.

**Comment by jude2018** [comment]
**Summary task list for the Association, based on the above:**

1. Confirm all categories of personal information (i.e. in addition to listed in point 1, above) that are being processed by or on behalf of the organisation and the purposes for which the proecessing is taking place.

2. Confirm identity of all organisations processing information on behelf of the Association? (Should these organisation continue to process or should processing continue to be shared?)

3. Establish retention periods for all categories of personal information identified.

4. Establish accountabilities and responsibilities for personal data compliance.

5. Write Privacy Notice and accompanying policies (such as Data Breach Reporing policy, Retention policy, Compliants procedure, and Charter for dealing wirh personal data requests).  The highest priority is the Privacy Notice with minimum information from supporting policies and Charters (e.g. How do I make a complaint? or a request for my personal information?)

Suggested sequential tasks and time-scale:

1. - Complete the first 3 task in 1 calendar month.
2. - Confirm accountabilities and repsonsibilities in 2 weeks.
3. - Draft, approve, and publish Privacy Notice in 1 month.
4. - Draft, approve, and publish Privacy Notice in 2 months, following publication of ther Privacy Notice.

**Comment by jude2018** [comment]
**DECISION REQUIRED**
The SC is asked to assign resources to enable the tasks to be completed, to ensure compliance with the GDPR legislation requirements on an ongoing basis.

**Comment by jude2018** [comment]
- [ ] 1. Complete the first 3 task in 1 calendar month. This is to be co-ordinated by  @jude2018 in conultation with SC members of the OpenWIS Association.
- [ ] 2. Confirm accountabilities and responsibilities in 2 weeks.  This is to be co-ordinated by @jude2018, in consultation with Steering Committee (SC) members of the OpenWIS Association and with guidance from Met Office Legal, as required. 
- [ ] 3. Draft, approve, and publish Privacy Notice in 1 month. This is to be co-oridnated by @jude2018 with support from Met Office Legal in drafting and approval by SC.
- [ ] 4.Draft, approve, and publish Privacy Notice in 2 months, following publication of the Privacy Notice.
- [ ] 5. Review policies and practise every 2-3 years. This is to be done as part of the OpenWIS Association Internal rules.
*

**Comment by jude2018** [comment]
Draft list of personal informattion sent to OpenWIS SC for review and addition by 7 March 2019

**Comment by jude2018** [comment]
Feedback on draft list received from BoM, MF and KMA.  Draft Privacy Statement being created

**Comment by jude2018** [comment]
Version for approval by Board, following review by SC and Met Office Legal (tracked changes shown)

[OpenWIS.GDPR.v0.8.DRAFT.docx](https://github.com/OpenWIS/openwis-documentation/files/3211623/OpenWIS.GDPR.v0.8.DRAFT.docx)

**Comment by 6a6d74** [comment]
Privacy policy agreed by SC during SC May-2019. Keeping action open until all of the related logistics (ie publishing new Internal Rules and adding the privacy policy to the web site) have been completed.

**Comment by jude2018** [comment]
Action agreed at the SC on 23 May - 

Email address alias (i.e. data-privacy-manager@openwis.io)  and re-directs to be Vice Chair and Secretariat are needed enable monitoring and responding to queries received. So. @loiclg to set up the email alias and @remygiraud to create a redirection distribution list with Jude and Jeremy’s email addresses.

**Comment by jude2018** [comment]
Action agreed at the SC on 23 May -

The Privacy policy needs to be published on the OpernWIS Association website in markdown format and publish as HTML under the ‘association’ tab once confirmed by UK Legal (i.e. v0.8).  Therefore, @solson-nws  to action.

**Comment by jude2018** [comment]
Action agreed at the SC on 23 May -
@remygiraud to check with the Notaries on whether the Privacy Policy (v0.8) needs to be published anywhere elese.

**Comment by jude2018** [comment]
Action agreed at the SC on 23 May - 
@jude2018 to publish to the new Internal Rule on the OpenWIS Association web site

**Comment by jude2018** [comment]
Markdown version of the Privacy Policy with the email address set-up by Méteo France is here - #568

**Comment by jude2018** [comment]
Privacy policy published and Internal ruiles also updated.  Therefore close.

Privacy Policy is here - http://openwis.github.io/openwis-documentation/articles/privacy_policy.html

Update to Internal Rules is here - http://openwis.github.io/openwis-documentation/articles/13-steering-committee.html
