### ISSUE TITLE
Action-PMC-2018-4 assess the end of life position of openwis3 components

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#462]

**Comment by solson-nws** [comment]
We have created a google doc for EOL dates.  It can be found here:  https://docs.google.com/document/d/1RGcVdRG3kmdhOz4rFsBOGx6aLhoRcwxXy5AbbzTh7YI/edit#heading=h.12569f45ww39

Currently, it's not shared out, but I'll update when this is ready for review.

Thanks!

Steve

**Comment by jude2018** [comment]
Cannot access Google Docs

**Comment by zhangz555** [comment]
On 7/12/18 scrum meeting, we held a discussion on the topic of "OpenWIS 3 EOL Dates for Software Stack". Please contribute your remarks/comments after reviewing the document. For those of you who
do not have access to the doc, it can be found as attachment here in doc and pdf formats.  
[OpenWIS 3 EOL Dates for Software Stack Survey.pdf](https://github.com/OpenWIS/openwis-documentation/files/2188846/OpenWIS.3.EOL.Dates.for.Software.Stack.Survey.pdf)
[OpenWIS 3 EOL Dates for Software Stack Survey.docx](https://github.com/OpenWIS/openwis-documentation/files/2188848/OpenWIS.3.EOL.Dates.for.Software.Stack.Survey.docx)

**Comment by solson-nws** [comment]
Looking to see if anyone has had a chance to review this document.  Looking for any feedback.  If there are no issues, I'll move this to closed at the TC meeting.
Thanks!

Steve

**Comment by zhangz555** [comment]
In one recent email, Remy Gibault analyzed and generated a list of the current End of Life for components inside OpenWIS 3.14, which is shown as below: 
◦JDK 1.7.0  => end of  support 2019 (oracle version)
◦Tomcat 7 => supported (but currently in version 9)
◦JBoss AS 7 .1 => EOL 2023
◦OpenDJ 2.6 => outdated; at least version 4 would be necessary to go to 2020
◦OpenAM 12 => outdated ; at least version 13 would be necessary to go to 2020
◦Postgres 9.2 => EOL 2017
◦Apache Solr 1.4.1 (not updated) => outdated

We provided our suggestions for upgrades and evaluations on Level of Effort, presented in a google doc as here: https://docs.google.com/document/d/1WmFZ5lbdNYmlQgbFWldJzWB_LFMgPX0ulUSymD3ciPU/edit?ts=5c560264

**Comment by solson-nws** [comment]
@zhangz555  @benjaminsaclier to assess level of effort (man months) to upgrade all middleware components

**Comment by solson-nws** [comment]
@solson-nws will close this ticket once these LOE are added

**Comment by zhangz555** [comment]
doc "Level of Effort to address EOL components in OpenWIS 3.14" is updated. https://docs.google.com/document/d/1WmFZ5lbdNYmlQgbFWldJzWB_LFMgPX0ulUSymD3ciPU/edit?ts=5c560264

**Comment by solson-nws** [comment]
These EOL risks are captured.  Closing this issue.  We can cross reference certain aspects of this list with maintenance releases that address these EOL risks.
