### ISSUE TITLE
Action-PMC-2018-5 check and test cent os7

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#463]
Per PMC in Helsinki - as part maintaining open3 there is a need to test and check Cent OS7 and report back

**Comment by solson-nws** [comment]
@SungsooDO , @benjaminsaclier :  Do either of you have updates on the CentOS7 check?  Hoping to update this before the TC meeting later in September

**Comment by SungsooDO** [comment]
Done to test and check CentOS7 for the latest version of OpenWIS(3.14.8)
All major functions of portal successfully work and couldn't find any problem.
Please find the following attachment.
[Action-PMC-2018-5 Check and test CentOS7(#463).docx](https://github.com/OpenWIS/openwis-documentation/files/2843652/Action-PMC-2018-5.Check.and.test.CentOS7.463.docx)

**Comment by benjaminsaclier** [comment]
For Meteo France we plan to upgrade GISC under CentOS7 before the end of 2019.

**Comment by solson-nws** [comment]
@solson-nws proposes to close.  Agreed by Jude and Benjamin.  Benjamin will still independently assess MF implementation of their GISC with CentOS 7 planned for later this year.
