### ISSUE TITLE
Action-PMC-2018-6 develop guidance on openwis3

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#464]
Per PMC in Helsinki based on; evaluating gaps in existing documentation #460 , review of technical rules #455, and enhancing setup and installation documentation #461  - create guidance to enable maintenance (via a PMC).

**Comment by jude2018** [comment]
Some dependency on OpenWIS 3x but can progress.  Priority of Technical Committee is the CICD environment. So, deferred until CICD work is complete in early March 2020.

**Comment by solson-nws** [comment]
Will close once #454  is completed.

**Comment by solson-nws** [comment]
Benjamin and I have updated the OpenWIS Developer and release guidance document.  Closing this ticket.  Final document was shared with TC email list on December 6th.
