### ISSUE TITLE
Action-TC-2018-23 alter code of conduct rules on the website

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#466]
Alter the first paragraph of the Code of Conduct for initial reporting of poor conduct to TC Chair and for TC Chair to raise issues conduct to SC, requesting resolution if required.

**Comment by solson-nws** [comment]
Code of Conduct link:  http://openwis.github.io/openwis-documentation/conduct/

First paragraph now states:  Please report unacceptable behavior to the OpenWIS Community Manager via email. Your report should include the date, time and place of the incident, who was involved and a description of what happened. All such issues shall be taken very seriously and dealt with as soon as possible by the Chair or Vice-chair of the OpenWIS Steering Committee, depending on who is most readily available. Your identity will be disclosed to no-one else.

Suggested modifications to first paragraph:  Please report unacceptable behavior to the OpenWIS Technical Committee Chair via email (same link as before).  The report should include the date, time and place of the incident, who was involved and a description of what happened.  The Technical Committee Chair will attempt to resolve all issues internally.  However, issues needing elevation will be reported to the Steering Committee Chair for resolution.  All such issues shall be taken very seriously and dealt with as soon as possible.  Your identity will be disclosed to no-one else.

**Comment by rogers492** [comment]
Closed by #478
