### ISSUE TITLE
Action-TC-2018-24 set up forum using discourse

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#468]
Set up focum using the structure under #157

**Comment by solson-nws** [comment]
@remy-gibault :  There is an email thread this one.  Just adding to github.

One of my questions was basically to understand who maintained the DNS records for openwis.io.  I understand that perhaps you may have initially set openwis.io.  If so, can we have you do the following so we can start our discourse instance:

On the DNS settings for openwis.io , you need to create a new CNAME record for a subdomain called forum. That record needs to point to openwis.hosted-by-discourse.com  

We want to be able to advertise the use of forum.openwis.iio for our discourse instance.

**Comment by jude2018** [comment]
Per Technical Committee of Sep 18  @solson-nws to contact @remy-gibault

**Comment by solson-nws** [comment]
@solson-nws will close this issue.  forum.openwis.io is up and fully functional.  @cassie-stearns  @mgiannoni @solson-nws will populate forum based on the templlate instance we stood up.  That can serve as an entry point for the forum.  This can be adjusted in time. Suggest we review this during the Annual Meeting in May 2019.
