### ISSUE TITLE
Action-SC-2018-35 create project charter for future of metadata formats

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#469]

**Comment by jude2018** [comment]
Suggested method for tracking the work -https://github.com/OpenWIS/openwis-documentation/projects/1?

**Comment by jude2018** [comment]
@6a6d74 Is there scope for this work to be done by a third party?  If so, I can speak to Met Office Procurement.

**Comment by solson-nws** [comment]
@jeremytandy  @jude2018 :  Can someone upload the Metadata Project Template.  I've onboarded the AMQP, Security and schema.org WIS2 pilot studies.  Just need to get the metadata code in github and the webpage.  Thanks!  Steve

**Comment by solson-nws** [comment]
Workshop on making spatial data discoverable through mainstream search engines - Call for abstracts
https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/Workshop+on+making+spatial+data+discoverable+through+mainstream+search+engines+-+Call+for+abstracts

This could describe a path forward for schema.org and metadata

**Comment by 6a6d74** [comment]
SC May-2019 agreed that this project would not be pursued at this time.
