### ISSUE TITLE
RISK-000006 Disruption from on-boarding new Partners

### ISSUE THREAD

**Issue by 6a6d74** [OpenWIS/openwis-documentation#492]
The effort to bring new Partners up to speed with OpenWIS processes and the existing software projects distracts the Association from effectively pursuing its goals.

**Comment by 6a6d74** [comment]
|Probability|Financial impact|Reputation impact|Goals impact|
|---|---|---|---|
|L|VL|VL|L|

**Comment by 6a6d74** [comment]
IMD are in the process of being on-boarded. No disruption evident as yet. 

Furthermore, OpenWIS Core PMC is focusing on documentation to support build and development activity.

**Comment by jude2018** [comment]
Agreed to close risk and no specific action is believed to be needed.
