### ISSUE TITLE
RISK-000010 OpenWIS Association fails to remain relevant to WMO

### ISSUE THREAD

**Issue by 6a6d74** [OpenWIS/openwis-documentation#496]
The activities of the OpenWIS Association are poorly aligned with the goals of WMO. Consequently, the Association fails to remain relevant to WMO and Members and Partners lose interest. 

See also RISK-000005 Association becomes irrelevant (#491)

**Comment by 6a6d74** [comment]
|Probability|Financial impact|Reputation impact|Goals impact|
|---|---|---|---|
|VL|L|H|VH|

**Comment by 6a6d74** [comment]
Risk discussed at SC-2018.

Mitigation activities include influencing the evolution and design of WIS 2.0 - to be achieved by contributing to the work of WMO Expert Teams / Task Teams.

**Comment by jude2018** [comment]
Work on AMQP is maintaing relavance. Also WMO reform is in progress.  The COVID19 situation may meant that WMO meetings have been postponed to October 2020.  So, more time to respond.  Also JTand RGr are heavily involved the WMO reform, so will have latest position in WMO as it unfolds.

**Comment by jude2018** [comment]
Per SC on26 and 28 May 2020 - please note these actions #553 and #559
