### ISSUE TITLE
OpenWIS 3.x - Governance for maintaining operational software until 2024

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#497]
**Background**
OpenWIS version 3 has been in development since 2012 and various versions of it are installed and in operational use by partners of the OpenWIS Association.  With a 2025 implementation date for WIS 2.0, OpenWIS 3 must continue to function and remain supported until 2024.

**Context**
To date OpenWIS 3.x development has been managed as an active development project.  The annual TC and SC meetings in May 2018 agreed that OpenWIS 3.x should be considered as being in maintenance mode.  However, there are a number of software fixes and life cycle upgrades of technology components that need to be considered, which needs some form of governance.

Therefore, a draft Project Charter is attached for the the SC to consider as means of governing the mainatence of OpenWIS 3.x to ensure operational continuity.  Please note that this Charter needs to discussed at the TC for further refinement and confirmation of resources.

[OpenWIS 3 Charter v0.2 DRAFT.docx](https://github.com/OpenWIS/openwis-documentation/files/2266976/OpenWIS.3.Charter.v0.2.DRAFT.docx)

**Decision/Action required**
The SC is asked to consider whether this Charter is a suitable governance arrangement for maintenance of OpenWIS 3.x for operational continuity until 2024.

**Comment by jude2018** [comment]
Agreed at SC on 9 August 2018 that there are 3 options: manage as a development project, with some governance proportionate to work plan and milestones, or reactively by creating a specific PMC for each item of work on OpenWIS 3.x.

The SC agreed that approach for this to be discussesd at the next TC, which hopefully will be during August 2018, allowing for feedback to SC on the final version of the Charter by end August 2018.  

@solson-nws - please ensure this is on the TC agenda.

**Comment by jude2018** [comment]
@solson-nws - please note for next TC meeting -https://github.com/OpenWIS/openwis-documentation/issues/452

**Comment by jude2018** [comment]
Following from the discussion regarding the Project Lead for OpenWIS 3x maintenance on the first session of the TC on 9Sep18, I attach a draft Charter (based on my proposed new template) for discussion and completion by the next session of the TC session in late September or early October 2018.

@solson-nws and @benjaminsaclier - please take a look and or change from your perspective (please attach an updated version to this issue)

Jude 
[Project  Charter - OpenWIS3x maintenance v0.1.docx](https://github.com/OpenWIS/openwis-documentation/files/2383058/Project.Charter.-.OpenWIS3x.maintenance.v0.1.docx)

**Comment by benjaminsaclier** [comment]
Hi Steve, 

Ok for me, just correct a year on doc (2014->2024) 

Benjamin 

----- Météo-France ----- 
Direction des Systèmes d'Information 
Subdivision Télécommunications 
42, av. G. Coriolis 31057 Toulouse Cedex 1 
tel: +33 561078152 gsm: +33 777802701 fax: +33 561078109 
Email: benjamin.saclier@meteo.fr 


De: "jude2018" <notifications@github.com> 
À: "OpenWIS/openwis-documentation" <openwis-documentation@noreply.github.com> 
Cc: "benjaminsaclier" <benjamin.saclier@meteo.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 14 Septembre 2018 13:02:50 
Objet: Re: [OpenWIS/openwis-documentation] OpenWIS 3.x - Governance for maintaining operational software until 2024 (#497) 



Following from the discussion regarding the Project Lead for OpenWIS 3x maintenance on the first session of the TC on 9Sep18, I attach a draft Charter (based on my proposed new template) for discussion and completion by the next session of the TC session in late September or early October 2018. 

[ https://github.com/solson-nws | @solson-nws ] and [ https://github.com/benjaminsaclier | @benjaminsaclier ] - please take a look and or change from your perspective (please attach an updated version to this issue) 

Jude 
[ https://github.com/OpenWIS/openwis-documentation/files/2383058/Project.Charter.-.OpenWIS3x.maintenance.v0.1.docx | Project  Charter - OpenWIS3x maintenance v0.1.docx ]

**Comment by jude2018** [comment]
Thanks @benjaminsaclier .  Do you have view on the milestones and configuration management sections?

Jude

**Comment by benjaminsaclier** [comment]
For information we start to work (with minimal effort) to include "GDPR" on Openwis interface. 

The purpose is when you auto-register have an obligation (function would be activate or not) to read a document (licence, information...) and accept or not. The account would be create only if the user accept. 

Objective is to push it on github for Q1 2019 

We can add it in the project charter ? 

Benjamin 



----- Météo-France ----- 
Direction des Systèmes d'Information 
Subdivision Télécommunications 
42, av. G. Coriolis 31057 Toulouse Cedex 1 
tel: +33 561078152 gsm: +33 777802701 fax: +33 561078109 
Email: benjamin.saclier@meteo.fr 


De: "SACLIER Benjamin" <benjamin.saclier@meteo.fr> 
À: "OpenWIS/openwis-documentation" <reply@reply.github.com> 
Cc: "OpenWIS/openwis-documentation" <openwis-documentation@noreply.github.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 14 Septembre 2018 15:41:32 
Objet: Re: [OpenWIS/openwis-documentation] OpenWIS 3.x - Governance for maintaining operational software until 2024 (#497) 

Hi Steve, 

Ok for me, just correct a year on doc (2014->2024) 

Benjamin 

----- Météo-France ----- 
Direction des Systèmes d'Information 
Subdivision Télécommunications 
42, av. G. Coriolis 31057 Toulouse Cedex 1 
tel: +33 561078152 gsm: +33 777802701 fax: +33 561078109 
Email: benjamin.saclier@meteo.fr 


De: "jude2018" <notifications@github.com> 
À: "OpenWIS/openwis-documentation" <openwis-documentation@noreply.github.com> 
Cc: "benjaminsaclier" <benjamin.saclier@meteo.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Vendredi 14 Septembre 2018 13:02:50 
Objet: Re: [OpenWIS/openwis-documentation] OpenWIS 3.x - Governance for maintaining operational software until 2024 (#497) 



Following from the discussion regarding the Project Lead for OpenWIS 3x maintenance on the first session of the TC on 9Sep18, I attach a draft Charter (based on my proposed new template) for discussion and completion by the next session of the TC session in late September or early October 2018. 

[ https://github.com/solson-nws | @solson-nws ] and [ https://github.com/benjaminsaclier | @benjaminsaclier ] - please take a look and or change from your perspective (please attach an updated version to this issue) 

Jude 
[ https://github.com/OpenWIS/openwis-documentation/files/2383058/Project.Charter.-.OpenWIS3x.maintenance.v0.1.docx | Project  Charter - OpenWIS3x maintenance v0.1.docx ]

**Comment by jude2018** [comment]
@benjaminsaclier - This could be a ticket (i.e. issue) that is raised, prioritised and potentially (i.e. if the PMC agrees) included as a milestone in the Charter.

**Comment by jude2018** [comment]
Per TC in September 2018 agreed the approach to Project Leadershop for OpenWIS 3x - see #452.  Therefore, this should be incorporated into the Project Charter for OpenWIS 3x using the Project Charter template

**Comment by jude2018** [comment]
@solson-nws @jude2018 and @benjaminsaclier to discuss a revised Project Charter in early November 2018 as the same time as #454 and #515

**Comment by jude2018** [comment]
@benjaminsaclier and @solson-nws .  Are there any further updates needed on this version of the Charter ?  (I've updated it to remoce the typo mentioned by @benjaminsaclier above)
[Project.Charter.-.OpenWIS3x.maintenance.v0.2.docx](https://github.com/OpenWIS/openwis-documentation/files/2695611/Project.Charter.-.OpenWIS3x.maintenance.v0.2.docx)
 


 I have not included the GDPR item as it probably needs to be treated separately to OpenWIS 3x as GDPR is more to with the OpenWIS Association than OpenWIS 3x (see #459).

**Comment by benjaminsaclier** [comment]
**Decision/Action required**

    The SC is asked to approve the Openwis 3.x project charter v0.2

**Comment by jude2018** [comment]
Per SC 11 Jan 19 - @benjaminsaclier and @jude2018 to convert this Project Charter to Markdown format and publish on the OpenWIS web site.

Please also see https://github.com/OpenWIS/openwis-documentation/issues/440#issuecomment-455596435

**Comment by jude2018** [comment]
Per SC on 11 Jan 19 = This Charter was approved

**Comment by jude2018** [comment]
@benjaminsaclier and @solson-nws, I suggest that this closed once the Markdown version is published on the web-ite

**Comment by jude2018** [comment]
Project Milestone | Begin Date | End Date
-- | -- | --
Deliverable 1 milestones :
Project   start |   |  
  |   |  
  |   |  
  |   |  
Deliverable 2 milestones :
  |   |  
  |   |  
 
  |   |  
  |   |  
Project   Closure |   |

**Comment by jude2018** [comment]
@benjaminsaclier and @solson-nws - I have created the Mardkdown version which is ready for publication on the web site once you are able to let me know:

1. The version of OpenWIS 3x that will be covrered in the Charter in the 'scope' section

1. The milestones that are rerelevant.  I think this will come from the roadmap of technology components that will be end of life.

1.  Any specific/particular configuration manegement that you intend to use.

**Comment by jude2018** [comment]
@solson-nws and @benjaminsaclier - any update please?

**Comment by jude2018** [comment]
@benjaminsaclier @solson-nws if there is no update, @solson-nws could you please publish on the OpenWIS Association website as part of updates that you have planned for the 'Projects' menu?

**Comment by 6a6d74** [comment]
Charter agreed for maintenance of OpenWIS Core 3.x

Closing issue.
