### ISSUE TITLE
PROJECT CHARTER: schema.org investigation

### ISSUE THREAD

**Issue by 6a6d74** [OpenWIS/openwis-documentation#498]
**Start date**: September 2018
**End date**: March 2019
**Lead organisation**: Met Office

**Scope**
The WMO Information System (WIS) enables discovery of authoritative meteorological and hydrological data and supports the collection of data and its exchange between WMO Centres and their users. It is operated and governed according to rules (“technical regulations”) defined by WMO, published in the Manual on WIS (WMO-No. 1060).

The data and products available across WMO are described by metadata records published in the WIS Catalogue. WIS Tech Spec 1 ‘Uploading of metadata for data and products’ (WMO No. 1060 Part IV) requires that metadata records comply with the WMO Core Metadata Profile of ISO 19115, as specified in WMO-No. 1060 Part V.

Search within the WIS Catalogue is based on terms from SRU (ISO 23950:1998) using a combination of text, date/time and geographic location:

* Text-based searches shall include: subject, abstract, title, author, keywords, format, identifier, type and coordination reference system
* Date/time-based searches shall include: creation date, modification date, publication date, beginning date and end date
* Geographic searches shall include a geographic bounding box

The WIS 2.0 vision recognises that weather, water and climate data and information must be made more easily discoverable and accessible to meet many of WMOs strategic objectives and enable WMO to effectively contribute to the UN global agendas. 

While the functions of WIS are likely to remain largely unchanged within WIS 2.0, the move to WIS 2.0 embodies a fundamental shift in the approach used for data sharing: from data-oriented GTS distribution to service-oriented access via the Web.

With the move to the Web, a different approach is required to support discoverability of data and products – where prospective users can discover data and products via commercial search engines (Google, Bing, Yahoo, Yandex etc.).

The [W3C Spatial Data on the Web Best Practice 2 ‘Make your spatial data indexable by search engines’](https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines) describes this approach in further detail.
schema.org is a collaborative, W3C community activity with a mission to create, maintain, and promote schemas for structured data on the Internet, on web pages, in email messages, and beyond. Schema.org has support from all the main search engine providers. 

This investigation will examine how schema.org vocabularies can be used to create structured metadata that is indexable by search engines for weather, water and climate datasets and products published through WIS.

Furthermore, this investigation will review the commonly available mechanisms that enable users to discover weather, water and climate data using date/time and geographic searches.

This investigation should build on existing work commissioned by Geonovum via their GEO4WEB Testbed. Topic 4 of the Testbed examined how schema.org could contribute to effective publication of spatial data on the Web. The GEO4WEB Topic 4 report is found [here](https://github.com/geo4web-testbed/topic4/blob/master/spatial-data-on-the-web-using-sdi-report.pdf).
  
**Deliverables**
This project will provide a report detailing the findings of the investigation.

**Participation**
_TBD_

**Comment by 6a6d74** [comment]
See also #439

**Comment by 6a6d74** [comment]
Comments from the SC teleconference 9-August:

1. flesh out the deliverables
1. add a section for **Additional Information**; include high level information on anticipated tender process
1. also include information on the funding mechanism - e.g. in kind, or OpenWIS finances ... in this case the Project will be funded from OpenWIS budget
1. Met Office will lead this activity; all Members/Partners expected to review documents (etc.) but nothing further
1. we need some consistency in how the project charters are presented/structured - see Issue #499

**Comment by 6a6d74** [comment]
@jude2018 - once you've developed the project charter template, please can we work together to update this charter?

**Comment by jude2018** [comment]
@6a6d74 - I suggest we use this approach to track the work once the charter template is available -https://github.com/OpenWIS/openwis-documentation/projects/1?

**Comment by jude2018** [comment]
@6a6d74 Is there scope for work in this Charter to be done by a third party ? If so, I can speak with Met Office Procurement

**Comment by jude2018** [comment]
Please also see #503

**Comment by 6a6d74** [comment]
SC 2019 agreed not to progress this project. See minutes for reference to INSPIRE workshop where this topic will be covered.
