### ISSUE TITLE
ACTION SC-2018-36 Develop template for Project Charters

### ISSUE THREAD

**Issue by 6a6d74** [OpenWIS/openwis-documentation#499]
During the SC teleconference 9-Aug, we reviewed several Project Charters, each of which had an inconsistent structure & formatting.

Please develop a template for Project Charters containing the required (& optional) headings.

**Comment by jude2018** [comment]
Please note the already agreed and established method for managing shared tasks which could be used in conjunction with the the Project Charter template -https://github.com/OpenWIS/openwis-documentation/projects/1?

**Comment by jude2018** [comment]
see #501

**Comment by jude2018** [comment]
Draft Project Charter template for discussion at the TC on 12 September 2018.
[Project  Charter v0.2 DRAFT.docx](https://github.com/OpenWIS/openwis-documentation/files/2371066/Project.Charter.v0.2.DRAFT.docx)

**Comment by Stacey-Harvey** [comment]
I note that the project charter now includes a section for source of funding - I can see that it specifically asks for a cost estimate or a breakdown of this which could include internal resource and external costs. I am not sure if this is put together in a different document but it would also be useful to see in order to make a decision about the project.

**Comment by jude2018** [comment]
Hi all,

A key agenda item for the 11 January 2019 SC will be the agreement of the Project Charters for the WIS2 studies and OpenWISx work.

To make this process smooth, please feedback on the proposed draft Project Charter template (#499), to make it possible for all new Charters to be created and approved in consistent way.

It would help everyone completing Charters to as much time as possible to create the new Charters, so quick feedback on the Charter is needed.

With this in mind, could you please feedback by 14 December 2018?

Best regards

Jude

Jude Anthonisz Senior Project Manager
Met Office FitzRoy Road Exeter Devon EX1 3PB United Kingdom
Tel: +44 (0)7824 414579
Email: jude.anthonisz@metoffice.gov.uk Website: www.metoffice.gov.uk

From: Anthonisz, Jude
Sent: 15 November 2018 13:13
To: '"openwis-sc@meteo.fr"' openwis-sc@meteo.fr
Subject: RE: OpenWIS Project Charter - revised template

Hi all,

A reminder to feedback on the Project Charter.

Best regards

Jude

Jude Anthonisz Senior Project Manager
Met Office FitzRoy Road Exeter Devon EX1 3PB United Kingdom
Tel: +44 (0)7824 414579
Email: jude.anthonisz@metoffice.gov.uk Website: www.metoffice.gov.uk

From: Anthonisz, Jude
Sent: 12 October 2018 13:55
To: "openwis-sc@meteo.fr" openwis-sc@meteo.fr
Subject: OpenWIS Project Charter - revised template

Hi all,

Please review and feedback on the proposed amended Project Charter template, which is here - #499

Once this is agreed, it will enable the required the following proposed Charters to be completed in the revised Project Charter format:
• #438
• #439
• #440
• #441
• #469

Best regards

Jude

Jude Anthonisz Senior Project Manager
Met Office FitzRoy Road Exeter Devon EX1 3PB United Kingdom
Tel: +44 (0)7824 414579
Email: jude.anthonisz@metoffice.gov.uk Website: www.metoffice.gov.uk

**Comment by jude2018** [comment]
Per SC 11 January 2019 - Publish project charter template in Markdown and ensure that the template is accessible on the OpenWIS Association web site

**Comment by jude2018** [comment]
PROJECT CHARTER MARKDOWN CREATION ONLY

# Project Charter for _please insert name of project here_
## Aim
_Please provide a short description of the aim and relevant problem(s) that will be solved by completing this project._

## Scope
 _Firstly, please describe or list what this project will include/do_
_Secondly, please describe or list the relevant things this project will not include/do_

## Deliverables 
_Please list the specific things that this project deliver that is part of the included scope and the date by when each deliverable will complete.  
Please Indicate which deliverables that ‘must’ be delivered in order for the aim to be achieved and which deliverables are optional (if any)._

## Sponsor and funding source
_Pleasde state the name of the sponsor, the organisation represented by the sponsor and the source of funding for this project._

## Milestones & Schedule
_Please list the milestones that will be needed to achieve each of the deliverables that are included within the scope of this project._

Project Milestone | Begin Date | End Date
-- | -- | --
Deliverable 1 milestones :
Project   start |   |  
  |   |  
  |   |  
  |   |  
Deliverable 2 milestones :
  |   |  
  |   |  
 
  |   |  
  |   |  
Project   Closure |   |  


## Roles and Responsibilities
_Please list the people to involve in this project; what their role in the project is; and what they will deliver (relate this to a milestone where relevant)_


Resource Name | Organization | Role | What this person will be do in relation to a    milestone | Time period resource needed for
-- | -- | -- | -- | --
XXX | YYY |   |   | TBD
  |   |   |   |  
  |   |   |   |  

## Communication and Reporting
State the communication and reporting arrangements for interactions with:
•	The Project Team 
•	PMC 
•	Define interactions with TC and SC
•	Final report/briefing on pilot study findings and recommendations

## Configuration Management Process
State how any of artefacts needed for each of the deliverables will be managed, referring to the relevant rules and rules supplements of the OpenWIS Association.

**Comment by jude2018** [comment]
Close as Charter template published to web site, i.e. here - http://openwis.github.io/openwis-documentation/howto/2019-02-08-OpenWIS-Project-Charter-template.html
