### ISSUE TITLE
ACTION SC-2018-40 Identify procurement support required for all study Project Charters

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#503]

**Comment by jude2018** [comment]
This can be progress as #502 progresses, which is now envisaged to be in September 2018

**Comment by jude2018** [comment]
Some Charters (i..e #469 Metadata format, #441 Trust model; and #439 Schema.org) may require procurement for work to be done by a third party

**Comment by jude2018** [comment]
To be discussed at PMC in annual meeting @solson-nws @benjaminsaclier

**Comment by 6a6d74** [comment]
Time expired. Only AMQP pilot project was progressed in 2018/19 and this did not require procurement support.
