### ISSUE TITLE
ACTION SC-2018-46 Confirm whether MFI can provide a Treasurer 

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#509]

**Comment by jude2018** [comment]
**Update from Rémy:**

Stacey,
MFI has just confirmed that they are ready to take over from you the treasurer position of the AISBL Openwis. Nathalie, in CC of this email will be taking care of this duty.
I still need to get formal approval from the Board on the offer from MFI, but, considering it is very reasonable I have no doubt that the board will approve this transition.
I suggest to start this handover the process ASAP, just in case you have to leave earlier than expected!
Can you liaise directly with Nathalie on the matter?
I will take care of the official aspect of this with the Belgian authorities.
Thank you and have a nice week-end,
Rémy

--
Rémy Giraud
DSI/ISI/D
Responsable du Département Infrastructure du SI
Head of IT Infrastructure Department
Météo-France, 42 Avenue Coriolis, 31057 Toulouse Cedex, France
Tél: +33561078173, Mob: +33779827985, Email: remy.giraud@meteo.fr

**Comment by jude2018** [comment]
@Stacey-Harvey - is there an update please?

**Comment by Stacey-Harvey** [comment]
Update as per Remy's email that Nathalie of MFI will take on the role of treasurer. The related cost needs to be approved by the Board and Remy has agreed to notify the Belgian Authorities. I will begin a handover with Nathalie shortly.

**Comment by jude2018** [comment]
@Stacey-Harvey can this be closed?

**Comment by Stacey-Harvey** [comment]
I would suggest it is closed once the board have approved – Remy has now requested board approval.

**Comment by jude2018** [comment]
@remygiraud Has the Board approved by email correspondence yet? (if so we can close this)

**Comment by 6a6d74** [comment]
MFI have confirmed. Closing issue
