### ISSUE TITLE
CloudBees sunset on 15 December 2018

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#515]
**Background**
The dev@CLOUD service will stop on December 15, 2018. 

**Impacts**
The impacts of this for existing software builds needs assessments.

**Options**

1. The Met Office has tried building OpenWis using travis-ci. On the whole, it works very well however JAVA7 is not supported.  So, it might be worth considering upgrading OpenWIS to java 8.

    The output of the build is here - https://travis-ci.com/OpenWIS/openwis

    Travis' security statement (as Travis makes use of AWS/Google in the USA) is here - https://docs.travis-ci.com/legal/security/

2. A replacement solution to CloudBees will incur a cost. 

3. Host a Jenkins instance on our own (Met Office) AWS infrastructure. This would incur a cost.

**Action needed**
TC to discuss and make a recommendation for the next step(s)

**Comment by jude2018** [comment]
@solson-nws - can we please add this to the agenda for the 12Oct18 session of the TC?

**Comment by solson-nws** [comment]
done

**Comment by solson-nws** [comment]
I have a few questions

1.  Are we talking about the openWIS software needing to be upgraded to Java 8?  If this is the case, release 3.14.8 or 3.14.9 already contains that upgrade.

2.  Are we talking about the fact the the cloud instance that cloudbees runs on needing a system software upgrade from Java7 to Java8?  If this is the case, is cloudbess on an existing Amazon Cloud Service instance?  If so, why can't a system administrator simply upgrade the version?
3.  If upgrading the cloud instance is not an option, then the team will need to consider and evaluate the 3 options you have listed here Jude.

Hope this makes sense

Steve

**Comment by solson-nws** [comment]
@jude2018 Action

**Comment by jude2018** [comment]
Initial repsonse from Release Engineering in the Met Office:
1.	Good stuff – resolved! 
2.	Jenkins runs on a solution provided by Cloudbees. In early December they are shutting this down entirely which means we will no longer have access to the current Jenkins instance at all. 
3.	As OpenWis is an OpenSource project, building on travis-ci.org would be free. CloudBees also have a replacement for the soon to be deprecated dev@CLOUD called CodeShip however the free tier is limited to 1 build at a time, 1 test pipeline and 100 builds. I’ll do some comparisons of the two to see which will be best.

**Comment by jude2018** [comment]
More information from Release Engineering in the Met Office:
•	CloudBees is hosted by Cloudbees themselves on their own servers (as a SaaS). So, there is no control over this, i.e. it is not possible to move it. I don’t think OpenWIS has built (apart from the nightly build) for sometime though so I doubt it’s massively urgent to find a replacement before it is switched off. 
•	See below – there are other solutions too but these are the top 3. I’ve had a play and TravisCI seems the best solution for what you need it for.

**Comment by OpenWIS-Association** [comment]
Anyone who is a named user on the OpenWIS GitHub user should have access to configure OpenWIS on TravisCI. https://travis-ci.org

**Comment by benjaminsaclier** [comment]
TC is agree to use Travis but expect a complete assessment of Openwis deploy and test on Travis.
Meteo-France will check if any resource is available for testing.

**Comment by solson-nws** [comment]
@jude2018 @benjaminsaclier :  Original Issue was to sunset.  This has happened.  We should create a new issue and crosslink to this that describes next steps with testing travis

**Comment by jude2018** [comment]
Makes sense to me.  Are you Ok with closing this one, creating a new issue and cross linking?

Jude

**Comment by solson-nws** [comment]
@solson-nws proposes a hackathon to understand/obtain institutional knowledge regarding the use of Travis in a CI environment for replacing cloudbees .  Suggest setting aside some time at the annual meeting for this exercise.  Outcomes from this would be that in kind resources can be used going forward, or that this results in a proposal to seek third party support as a proposal to SC.  Contributors are being ironed out.  @jude2018 @benjaminsaclier @solson-nws have action to assign/check on resources to participate in hackathon.  Hackathon must occur during the morning hours in Washington to support broader participation by founding members and strategic partners.

**Comment by solson-nws** [comment]
#515
