### ISSUE TITLE
OpenWIS code - security vulnerabilities

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#517]
The following security vulnerabilities have been alerted by Met Office Release Engineering for OpenWIS code held on github respositories:

[RE OpenWIS - Security vulnerabilities.pdf](https://github.com/OpenWIS/openwis-documentation/files/2585880/RE.OpenWIS.-.Security.vulnerabilities.pdf)

**Comment by jude2018** [comment]
per PMC meeting on 15Nov18- agreed to focus on critical issues that affect OpenWIS 3x to make best use of available resources.

**Comment by jude2018** [comment]
From Met Office Release Engineering:

- these vulnerabilities relate to OpenWIS code stored in OpenWIS Github repositories.
- The vulnerability relating to the Met Office system that is listed has been fixed.

**Comment by zhangz555** [comment]
I will summarize three vulnerabilities under this issue umbrella, so as to facilitate our talk and tracking.

1. OpenWIS/openwis:  org.apache.solr:solr-core (Needs to be >= 7.1.0). 
2.  OpenWIS/openwis:  org.apache.lucene:lucene-core (Needs to be >= 7.1.0).
3. OpenWIS/openwis:  commons-fileupload:commons-fileupload (Needs to be > 1.3.2).

The follow-up comments will be the status updates for each vulnerability.

**Comment by zhangz555** [comment]
For vulnerability 1, please check issue #300. https://github.com/OpenWIS/openwis/issues/300

**Comment by zhangz555** [comment]
For vulnerability 2, there are several projects are affected.

in project  defined as <modelVersion>4.0.0</modelVersion>    <groupId>org.geonetwork-opensource</groupId>    <artifactId>geonetwork</artifactId>    <packaging>pom</packaging>its modules    <modules>        <module>cachingxslt</module>        <module>jeeves</module>         <module>oaipmh</module>        <module>sde</module>        <module>openwis-portal-solr</module>    </modules> 

We can see its dependency management            <dependency>                <groupId>org.apache.lucene</groupId>                <artifactId>lucene-core</artifactId>                <version>2.9.2</version>            </dependency>

in project defined as <modelVersion>4.0.0</modelVersion>    <groupId>org.geonetwork-opensource</groupId>    <artifactId>geonetwork</artifactId>    <packaging>pom</packaging>its modules    <modules>        <module>cachingxslt</module>        <module>jeeves</module>         <module>oaipmh</module>        <module>sde</module>        <module>openwis-portal-solr</module>    </modules>,
we can see its dependency Management            <dependency>                <groupId>org.apache.lucene</groupId>                <artifactId>lucene-core</artifactId>                <version>2.9.2</version>            </dependency>

**Comment by zhangz555** [comment]
For vulnerability 3, there are several projects are affected.

in project     
```
<groupId>org.geonetwork-opensource</groupId>    
<artifactId>jeeves</artifactId>    
<packaging>jar</packaging>    
<name>Jeeves modules</name>    
<description>Jeeves project.</description>
```
its parent is     
```
<parent>        
<groupId>org.geonetwork-opensource</groupId>        
<artifactId>geonetwork</artifactId>        
<version>3.14.8-SNAPSHOT</version>        
<relativePath>../pom.xml</relativePath>    
</parent>      
```  
its dependency, we see 
```
<dependency>            
<groupId>commons-fileupload</groupId>         
<artifactId>commons-fileupload</artifactId>

```
in project 
```
<modelVersion>4.0.0</modelVersion>    
<groupId>org.geonetwork-opensource</groupId>    
<artifactId>geonetwork</artifactId>    
<packaging>pom</packaging> 
```
in its dependency Management, we see            
```
<dependency>                
<groupId>commons-fileupload</groupId>                
<artifactId>commons-fileupload</artifactId>                
<version>1.2.1</version>            
</dependency>
```

in   project  
```
<groupId>org.geonetwork-opensource</groupId>    
<artifactId>openwis-portal</artifactId>    
<packaging>war</packaging>    
<version>3.14.8-SNAPSHOT</version>    
<name>OpenWIS module</name>  
```      
we see dependency
```
<dependency>            
<groupId>commons-fileupload</groupId>            
<artifactId>commons-fileupload</artifactId>        
</dependency>
```
--

**Comment by benjaminsaclier** [comment]
@remy-gibault Hi Remy , do you have any recommendations for these vulnerabilities prioritization ?

**Comment by jude2018** [comment]
Agreed to close at Technical Interchange on 27Aug19 as these have been addressed by @zhangz555
