### ISSUE TITLE
Budget 2019 - send SC approved budget to Board

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#525]
Per SC of 11 Janaury 2019, the agreed budget for 2019 to be sent to Board members for approval

**Comment by Stacey-Harvey** [comment]
Budget sent to the Board members on 16th January 2019 to approve along with queries around the budget for project costs. Asked for responses to be sent to Nathalie as responsibilities now handed over.

**Comment by jude2018** [comment]
@dureisseixn Hi,  Have you had responses from members of the Board?  If not please chase for a response.

**Comment by dureisseixn** [comment]
Hi Jude

I have any reponses from members of the Board.
I will do a reminder email.

**Comment by jude2018** [comment]
Great ☺

**Comment by 6a6d74** [comment]
Action completed during handover of treasurer role from Met Office to MFI
