### ISSUE TITLE
GDPR status for OpenWIS 3x implementation in UK Met Office and Météo France

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#526]
Per SC on 11 Jan 19 - @jude2018 to establish from the MSS team in UK Met Office as to whether the GISC implementation of OpenWIS 3x has had a GDPR Assessment.  Similarly, @benjaminsaclier to establish the position in Météo France.

**Comment by jude2018** [comment]
Per discussion with MSS Team Leader in Met Office - a Privacy Impact Assessment has been undertaken.  Howvever, a GDPR assessmnet has not been undertaken and will be part of the backlog of of the work in the UK MSS team.

**Comment by jude2018** [comment]
@benjaminsaclier please update the situation for Méteo France regarding the GISC

**Comment by jude2018** [comment]
@benjaminsaclier -any update please?

**Comment by benjaminsaclier** [comment]
For MF we implemented a term acceptance validation during the Register process on Openwis : [](http://maccp-raq-int.meteo.fr/openwis-user-portal/srv/en/user.register.get)
At present time this is only available on our DCPC Copernicus . We plan to submit this update to github but first we should implement our modification on the last version of Openwis (actually we did it on v3.13)

**Comment by 6a6d74** [comment]
GISC implementations are not the concern of the OpenWIS Association with regard to data protection issues.

Closing issue
