### ISSUE TITLE
Investigate Travis-CI to replace Cloudbees

### ISSUE THREAD

**Issue by solson-nws** [OpenWIS/openwis-documentation#529]
@solson-nws proposes a hackathon to understand/obtain institutional knowledge regarding the use of Travis in a CI environment for replacing cloudbees . Suggest setting aside some time at the annual meeting for this exercise. Outcomes from this would be that in kind resources can be used going forward, or that this results in a proposal to seek third party support as a proposal to SC. Contributors are being ironed out. @jude2018 @benjaminsaclier @solson-nws have action to assign/check on resources to participate in hackathon. 

Hackathon must occur during the morning hours in Washington to support broader participation by founding members and strategic partners.

Suggest we prepare a cloud environment for testing

**Comment by jude2018** [comment]
Spoken to @adrian-wood and the outcomes are:

- Adrian can be available for this event.
- We need to work with Adrian to be prepare in some detail before the event itself (whis to be during wc 20 May 2019).
- The scope of the hackathon/ knowledge sharing session will be to: demon and facilitate knowledge exchnage on building an agreed version of OpenWIS 3.x.
- What we need to discuss what the hosting solution will be and who will make this available (this will be a thid party such as AWS).
- It will be good to confirm this scope as part of this thread to ensure that everyone is happy that Travis covers all the features expected of a CI environment and what features are to be part of the event.
- For information, Cloudbess costs were 300 USD per month.

Please note that @adrian-wood - can be available at part of the PMC session scheduled for 6 March 2018 to answer any Travis CI related queries or concerns.

**Comment by adrian-wood** [comment]
After our meeting today (during which the dependencies script was mentioned) I recreated my test branch from scratch and have now been able to successfully build it using Travis-CI

https://api.travis-ci.org/v3/job/502650706/log.txt

There are a number of actions here for improvement:

- This is using the travis-ci branch based on develop as 3.14.8-release did not include the Forgerock dependency script. 
- The building of the Forgerock dependencies occurs every time OpenWIS is built. Might be good to separate these out to a separate repository/build as these don't change often. 
- The log output is too long to display in Travis-CI itself. Have to view in the RAW view. https://api.travis-ci.org/v3/job/502650706/log.txt
- We can add some logic that automates the Maven Release Process if the branch is master. https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
- Need confirmation of the Unit tests that need to run as part of the build. Is this what needs to be run? https://github.com/OpenWIS/openwis/tree/master/openwis-factorytests

**Comment by jude2018** [comment]
Notes from the rehersal session on 3 April 2019:

- The **aim** is to build OpenWIS v3.14.8 on the travis-ci branch.

**Build location**
- https://docs.travis-ci.com/user/conditional-builds-stages-jobs/ 

**Configuration**:
- Maven v3 being used
- Java 8
- WIldfly 8
- Spring 4.15
- OpenAM 13
- OpenDJ 3 
 
**Build notes**
1.  'OpenDJ-SDK-public  'RPC fail' error message @adrian-wood to raise a ticket with Forgerock

1.  Long time to build. @adrian-wood to raise a ticket with Forgerock

1.  Error noted by NOAA by @zhangz555 
     [openwis@openwis-d3 opendj-sdk]$ git clone https://stash.forgerock.org/scm/opendj/opendj-sdk-    
     public.git Initialized empty Git repository in /home/openwis
     /openDJAndOpenAMCommunityInstallTest/opendj-sdk/opendj-sdk-public/.git/
     remote: Counting objects: 229678, done.
     remote: Compressing objects: 100% (39678/39678), done.
     ^Cceiving objects: 20% (46644/229678), 5.49 MiB | 14 KiB/s
     Initialized empty Git repository in /home/openwis/OpenWIS-4.0/open-dj-am-install-scripts/NWS-    
     open-dj-am-install/openDJAndOpenAMCommunityLibs/opendj-sdk/opendj-sdk-public/.git/
     remote: Counting objects: 229678, done.
     remote: Compressing objects: 100% (39678/39678), done.
     Receiving objects: 32% (75105/229678), 7.50 MiB | 3 KiB/s
     error: RPC failed; result=18, HTTP code = 200MiB | 14 KiB/s

1.  @adrian-wood to check whether the service can be run on a test environment within Travis or whether a separate enviornment is needed.

Agreed to investigate further in NOAA and UK Met Office (including getting feedback/response from Forgerock)

**Comment by adrian-wood** [comment]
As promised here is my update for the meeting on the 7th May. 

I have very little time to offer OpenWIS at the moment however (given I've not used Travis-CI much before) anyone who spends a bit of time reading the Travis-CI documents should know pretty much all I know. 

I think the next steps are documented in my previous comment above with the main two working out why it won't build with openam-public 13.0.0 but does with 12.0.0 and look to adding a conditional stage which maven releases (and pushes back the resulting artifacts to GitHub) if the branch is master. That means new maven released versions of OpenWIS can be created simply by merging changes to master.

**Comment by StephanSiemen** [comment]
FYI, at ECMWF, we use a self-hosted Atlassian Bamboo service to do CI testing. This integrates well with our JIRA and BitBucket. For our GitHub hosted open-source software packages (https://github.com/ecmwf), we use AppVeyor for Windows CI and TravisCI for MacOS & Linux testing. 

We are happy to share our experiences with TravisCI.

**Comment by davidpodeur** [comment]
Hi Adrian,
From Meteo France side we managed to get access to the openwis CI on travis-ci.org (we needed to enable travis-ci.org to access to the "private projects" through travis-ci**.com**).
Do you know how to get (i.e. download) the built itself once Travis has performed the compilation?

**Comment by solson-nws** [comment]
@adrian-wood : Hi Adrian,
From Meteo France side we managed to get access to the openwis CI on travis-ci.org (we needed to enable travis-ci.org to access to the "private projects" through travis-ci**.com**).
Do you know how to get (i.e. download) the built itself once Travis has performed the compilation?

**Comment by solson-nws** [comment]
@jude2018 @benjaminsaclier @StephanSiemen @solson-nws :  This issue has been superceded by #532.  Closing this issue.
