### ISSUE TITLE
Fix formatting of table for Internal Rule 6.4

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#531]
Per PMC on 20 May 2019- a fix to the markdown is needed for the table formatting here - http://openwis.github.io/openwis-documentation/rules/6-membership-and-partnership-fees-rights-privileges-and-obligations.html

**Comment by jude2018** [comment]
@solson-nws is this complete?

**Comment by solson-nws** [comment]
This is completed.  Closing issue

**Comment by solson-nws** [comment]
Yes, and I've closed the issue.

Steve
