### ISSUE TITLE
CI environment - establish AWS support is available. 

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#532]
Per PMC on 20  May 19 -  For the new CI environment after Cloudbees deprecation, a local resource or cloud-based resource or something that can be shared is required.  

To help the TC make a proposal to the SC,  knowing the potential support available from AWS is needed.

**Comment by solson-nws** [comment]
@solson-nws @StephanSiemen :  Working on the proposal.  Expect to have draft completed in early part of June for broader review.  Targetting a complete RFP by mid June.

**Comment by jude2018** [comment]
@6a6d74 @solson-nws - is there an update on this?

**Comment by solson-nws** [comment]
Closed.  ED is contractor supporting the build out of a new CI/CD environment, plus cloud instance for builds.
