### ISSUE TITLE
CI environment - support from MFI in defining requirements

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#533]
Per the PMC on 20 May 2019 - 

The new CI environment needs to be functional by end of September 2019. To enable this, a procurement exercise needs to done (SC will discuss the procurement approach on 22 May 2019).

The decison is that requirements of the CI environment needs to be documented by mid-June 2019.   The team tobe involved in this are ECMWF, NWS, MF and MFI.

Loic to check with @remy-gibault and feedback on what help MFI can provide.

**Comment by solson-nws** [comment]
@StephanSiemen  and @solson-nws are working on RFP as we speak.  Other action was for Loic to check with @remy-gibault and feedback on what help MFI can provide for defining requirements.

**Comment by jude2018** [comment]
@ PMC meeting agreed that @benjaminsaclier will find out from @loiclg the situatin in MFI re work with AKKA, i,e. scope of work, time-scales and costs
@solson-nws @StephanSiemen

**Comment by jude2018** [comment]
Please see #542 .  This can be closed.

**Comment by jude2018** [comment]
Procurement complete.  Therefore closed
