### ISSUE TITLE
Release process and installation guide documentation - co-ordinate update and testing

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#535]
Per PMC on 20 May 2019 - 

It was agreed that the team that would be involved in making the current process and documentation up to date would be NWS, ECMWF, MFI  SO to co-ordinate updating existing release process documentation.

**Comment by jude2018** [comment]
Also see #454

**Comment by solson-nws** [comment]
@StephanSiemen @benjaminsaclier @loiclg :  Let's set up a meeting for the week of July 29th to talk about what it will take to update our Release notes documentation, etc to the most recent OpenWIS version (3.14.8).  Please indicate your availability the week of July 29th.

Thanks!

Steve

**Comment by jude2018** [comment]
This is part of the RFP for the OpenWIS 3x middleware work.

**Comment by jude2018** [comment]
Clsoe as coverd by #461
