### ISSUE TITLE
OpenWIS 3x - assessment of options to replace OpenAM and OpenDJ

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#536]
Per PMC on 20 May 2019 - 

It was agreed that the dependency on Forgerock woud be removed from OpenWIS 3x. as part of making OpenWIS 3x simpler to maintain until end 2024 (to dicussed further/ratified at the TC and SC on 21 and 22 May) 2019).

However, there needs to be an asseement of how much simplicity can be achieved, so that the work involved, security and other implications understood. So, it was agreed that :

- NWS and MFI to explore options and that UKMO would validate the options.

- the scope of options would be SAML2.0. Direct LDAP integration, and in-container authentication (e.g. Tomcat or Apache)

**Comment by jude2018** [comment]
Agreement at PMC on 23 July that this will form dicussions about middleware that form the approach to be defined by @solson-nws

**Comment by jude2018** [comment]
Per Technical interchange on 27 AUgust 2019 - agreed that this issue will be tracked under #542

**Comment by solson-nws** [comment]
Closed.  This issue will be tracked under #542
