### ISSUE TITLE
OpenWIX 3x - Containerisation

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#537]
Per PMC on 20 May 2019 - 

MF have worked on this but have difficulties with OpenDJ, OpenAM and database.

Once the work on removing the dependency of OpenWIS 3x on Fogrerock is complete, this work can be re instated.  See also #536 

It was noted that the database and content will need to be deployed separately and connected – but this should be the only external not outside the container

**Comment by benjaminsaclier** [comment]
Please find in attachment the report of OpenWIS containerisation.
[akka_architecture_openwis_docker.pdf](https://github.com/OpenWIS/openwis-documentation/files/3202877/akka_architecture_openwis_docker.pdf)
[DCS-OpenMeteo-Docker-V1.2.pdf](https://github.com/OpenWIS/openwis-documentation/files/3202879/DCS-OpenMeteo-Docker-V1.2.pdf)

**Comment by jude2018** [comment]
Per Technical interchange on 27 AUgust 2019 - agreed that this issue will be tracked under #542

**Comment by solson-nws** [comment]
Closed.  This issue is being tracked under #542
