### ISSUE TITLE
OpenWIS 3x - software dependencies

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#538]
Per PMC on 20 May 2019 - 

Following a review of the analysis of dependencies undertaken so far by @zhangz555 , it was decided that:

- The principle of not needing to upgrade to the latest version.  To decide which version to update to, there is a need to assess whether a security issue exists and then only upgrade to the version that resolves a security issue. 
- UKMO woud review the security issues based on the analysis so far on OpenWIS v3.14.8.

- NWS, would establish which repos are current, based on the dependency list presented by @zhangz555 

- regularly update the dependency list.

**Comment by jude2018** [comment]
Per PMC on 23 July - Agreed that @solson-nws to be confirm as part of approach to progressing RFP on middleware

**Comment by jude2018** [comment]
Per Technical interchange on 27 AUgust 2019 - agreed that this issue will be tracked under #542

**Comment by solson-nws** [comment]
Close this issue.  Superceded by #542
