### ISSUE TITLE
OpenWIS 3x - options for maintaining licence free

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#542]
Per TC on 21 May 2019 - 

Agreed to recommend approach as agreed at the PMC to keep OpenWIS licence free as a proposal (also see #536 and #538 ).  This is to be recommended to the SC on 22 May 2019. 

The plan is:

- [ ] @solson-nws to provide estimates of all options of effort by end of August 2019 to TC.
- [ ] @loiclg and @solson-nws to present options and costs at the OpenWIS Developer Conference (Dev Con) on 23 to 25 September in Toulouse. 
- [ ] @solson-nws  and @benjaminsaclier gain approval by SC following TC endorsement.

**Comment by jude2018** [comment]
Challenges identified at Technical interchange on 27 August 2019:

1 - Resources for development and deployment
2. Ease of use (i.e. deployment and operation from an administrator perspective)
3. Need to keep focus on maintance and not new features (i.e. upgrade to geonetwork would be excluded).  Need to have a discussion on specific scope)
4. Simplification (both a challenge and a goal) - such as removing OpenDJ and OpenAM without significant development work and ease of use for operattional administration.
5.

**Comment by remy-gibault** [comment]
MFI Presentation:
[20190724 OpenWIS Middleware Upgrade Study V01 RG.docx](https://github.com/OpenWIS/openwis-documentation/files/3546776/20190724.OpenWIS.Middleware.Upgrade.Study.V01.RG.docx)

**Comment by jude2018** [comment]
Please note that UKMO have confirmed that it can run the procurement and the procurement framework #557

**Comment by solson-nws** [comment]
Potential CI/CD Team members for future OpenWIS Builds include:

**NWS:**  Steve Olson, Zhan Zhang, Marc Giannoni (@solson-nws @zhangz555 @mgiannoni )
**UK Met Office:**  TBD
**ECMWF:** Stephan Sieman (@StephanSiemen )
**MF:** David Podeur, Benjamin Saclier, Yves Goupil (@davidpodeur @benjaminsaclier @yvesgoupil )
**MFI:**  Remy Gibault (@remy-gibault )
**KMA:**  Sungsoo Do? (@SungsooDO )
**BOM:**  Anuruddha Abhayasinghe 
**FMI:** Mikko Visa, Mikko Partio (@mvisa @mpartio )
**IND:** Kuldeep Srivastava

This set of folks is _**nominally**_ who could participate in the training exercise for CI/CD.  We're looking for confirmation that: 1) you would like to participate as a member of CI/CD build team, and 2) That you intend to participate at the training session

Right now, we're anticipating the training to be in early March.  This is not firm yet!

**Comment by solson-nws** [comment]
Confirmed CI/CD team members:
**NWS:** Steve Olson, Zhan Zhang, Marc Giannoni (@solson-nws @zhangz555 @mgiannoni )
**ECMWF:** Stephan Sieman (@StephanSiemen )
**KMA:** Mr. Ryu (@JeyoungRyu )

**Comment by solson-nws** [comment]
UKMO = Jon Phillips and Duncan Jeffery

**Comment by solson-nws** [comment]
Confirmed CI/CD team members:
**NWS:** Steve Olson, Zhan Zhang, Marc Giannoni (@solson-nws @zhangz555 @mgiannoni )
**ECMWF:** Stephan Sieman (@StephanSiemen )
**KMA:** Mr. Ryu (@JeyoungRyu )
**UKMO** = Jon Phillips and Duncan Jeffery

**Comment by solson-nws** [comment]
**NWS:** Steve Olson, Zhan Zhang, Marc Giannoni (@solson-nws @zhangz555 @mgiannoni )
**ECMWF:** Stephan Sieman (@StephanSiemen )
**KMA:** Mr. Ryu (@JeyoungRyu )
**UKMO** = Jon Phillips and Duncan Jeffery
**MF:** Benjamin Saclier (@benjaminsaclier ) and Yves Goupil (@yvesgoupil )

**Comment by solson-nws** [comment]
**Confirmed CI/CD team members:**
_10 members_ on the team currently

**NWS:** 
    Steve Olson (github id: @solson-nws, email:  steve.r.olson@noaa.gov)
    Zhan Zhang (github id: @zhangz555, email:  zhan.j.zhang@noaa.gov)
    Marc Giannoni (github id: @mgiannoni, email:  marc.giannoni@noaa.gov)

**ECMWF:** 
    Stephan Sieman (github id: @StephanSiemen, email: stephan.siemen@ecmwf.int)

**KMA:** 
     Mr. Ryu (github id: @JeyoungRyu, email: mazelan95@gmail.com)

**UKMO:** 
     Jon Phillips (github id:   , email: jonathan.phillips@metoffice.gov.uk)
     Duncan Jeffery (github id:   , email: duncan.jeffery@metoffice.gov.uk )

**MF:** 
     Benjamin Saclier (github id:  @benjaminsaclier, email: benjamin.saclier@meteo.fr )
     Yves Goupil (github id:  @yvesgoupil, email:  yves.goupil@meteo.fr )

**BOM:**
     Anuruddha Abhayasinghe (githubid:   , email: anuruddha.abhayasinghe@bom.gov.au)

**Comment by jude2018** [comment]
See #578 re CICD work

Middleware RFP agreed by TC and SC - awaiting confirmation of procurement route

**Comment by solson-nws** [comment]
MF and NWS are examining Keycloak as potential replacement for security service implementations of OpenAM/OpenDJ.  Will revise middleware RFP based on findings and recommendations.  Once these actions and approved by TC, this ticket will be closed.

**Comment by jude2018** [comment]
Following PMC and TC meetings in May 2020.  This item ic closed and pcked up new speficit actions, i.e.: #584, #585, and #586
