### ISSUE TITLE
CI environment - decide whether to include infrastructure within RFP

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#543]
Per TC on 21 May - 
Agreed that from considering whether  to use an on-premise or cloud environment/infrastructure, that its best to evaluate whether a third party could build an environment as OpenWIS 3x is in maintenance development. 

So @StephanSiemen consider whether to incorporate into RFP or recommend a separate RFP

Also see #532, #533, #534

**Comment by jude2018** [comment]
Is there an update ? @benjaminsaclier @solson-nws @loiclg @StephanSiemen

**Comment by jude2018** [comment]
@solson-nws @benjaminsaclier @StephanSiemen - is this in hand or is discussion needed at the meeting re the RFP on 9 Sep?

**Comment by solson-nws** [comment]
A separate RFP was created for the software refactor work.  Closing this issue.
