### ISSUE TITLE
Forum - change description from 'OpenWIS Project' to 'OpenWIS Core'

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#547]
Per TC on 21 May - 

Make changes to the description of OpenWIS from 'OpenWIS Project' to 'OpenWIS Core'

Also see #545 #546 #548 and #549

**Comment by jude2018** [comment]
Lower priority as focus is on CICD and OpenWIS 3x middleware

**Comment by solson-nws** [comment]
closed
