### ISSUE TITLE
Annual meeting 2020

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#558]
Per Board meeting on 23 May, it was established that:

- provisional confirmation from BoM is available; 
- 4 days would be enough; and 
- dates should be  firmed up as soon as possible.

ACTION - @jude2018 to set up a telco with @remygiraud, @6a6d74, and @wqu-bom regarding the hosting and dates of the 2020 annual meeting AND appointment of @wqu-bom as the Vice Chair of the Board

**Comment by jude2018** [comment]
Per telco on 11 June @wqu-bom to confirm by end June 2019 on the preferred week in May 2020 for the next annual meeting and that approval has been gained for BoM to host the meeting

**Comment by jude2018** [comment]
Reminder sent by email to @wqu-bom today

**Comment by jude2018** [comment]
Response received from @wqu-bom that it can be assumed that BoM will host the annual meeting for the week starting 25 May 2020.
@remygiraud

**Comment by jude2018** [comment]
SC on 16 December 2019 verified via @wqu-bom that the meeting dates in Melbourne are 25-28 May 2020 (4 days)

**Comment by jude2018** [comment]
SC on 30 March 202- agreed that the annual SC and Board meetings would held virtually between 20 and 28 May 2020 due to the travel restrictions and isolation requirements of the COVID19 pandemic.

**Comment by solson-nws** [comment]
I polled the TC regarding availability of members for (2) 3-hr sessions.  Based on that poll, I have selected:

May 19th: 6:00 to 9:00 am eastern time for PMC portion
May 20th: 6:00 am to 9:00 am eastern time for TC portion
