### ISSUE TITLE
Prepation of annual accounts and Managing Director roles

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#559]
Per the Board meeting on 23 May - 

- It was agreed that the Treasurer role should not be restricted to a specific term. So, this needs to be discussed with the notaries as part of the discussion to changes to the Articles of Association - #553

Also, @remygiraud amd @dureisseixn to speak with Vincent Corbeel to prepare the annual accounts for 2018, including resignation and appointment of MDs (i.e. Treasurer and Vice Chair of the Board)

**Comment by remygiraud** [comment]
Done. Nathalie and I sent the draft paper work to Vincent. We are waiting for the publication.
