### ISSUE TITLE
OpenWIS 3x - options for maintaining licence free - indication of costs

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#564]
Per TC on 21 May -agreed to get costs from the work done by European Dynamics work as an indicator.

Also see #542

**Comment by jude2018** [comment]
Details requested from MO Procurement, awaiting information.

**Comment by jude2018** [comment]
Indicative costs available

**Comment by solson-nws** [comment]
@jude2018 :  Can you indicate the ED costs in this issue?

Thanks!

Steve

**Comment by jude2018** [comment]
Can issue it once the discussion with MO Procurement and @remygiraud takes place.  Note the commercial sensitivity, so it will be via DropBox

**Comment by jude2018** [comment]
Agreed to close issue at Technical Interchange on 27Aug19
