### ISSUE TITLE
OpenWIS 3x - options for maintaining licence free - Devcon preparation

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#565]
Per TC on 21 May 2019 , it was agreed that SO and BS Discuss other topics for DEVCON on 23-25 September 2019, in Toulouse.

**Comment by solson-nws** [comment]
@benjaminsaclier @jude2018 @solson-nws @StephanSiemen  agreed last week that the structure of September meetings at MF in Toulouse would be:

September 23 -- Training on CI/CD environment
September 24 -- Training on CI/CD environment
September 25 -- Completion of training and discussion on middleware options.  Presentations by LOIC and NWS on progress made.  Formulate blueprint and path forward and create a second RPF
September 26 -- WIS 2 and Message Queues discussion

**Comment by jude2018** [comment]
@solson-nws and @benjaminsaclier - following discussion with @remygiraud re procurement timesscales, meaning that a 'devon' should be in January or February 2020 and cancellation of the meeting re AMQP on the above - this issue has been re-opended

**Comment by jude2018** [comment]
Close as being covered by #578 and RFP for middleware complete
