### ISSUE TITLE
Establish Governance Structure for future OpenWIS builds using CI/CD 

### ISSUE THREAD

**Issue by solson-nws** [OpenWIS/openwis-documentation#581]
Good Morning All

During this morning's TC meeting, I took an action to create a github issue for establishing a Governance structure for future OpenWIS builds using our new CI/CD setup.   Much of the Governance structure has been somewhat vetted (2 TC meetings so far).  What's missing is the governance structure around releases.   Benjamin found a nice link in github that provides training on managing releases.  Four people (@mgiannoni @zhangz555 @yvesgoupil and @benjaminsaclier ) have been identified to take the training and comment on their thoughts for a repeatable release governance structure.  Others are also welcome to take the training and comment!  I ask that this exercise be completed by Friday March 27th, so we can discuss at the end of our CI/CD wrap up with ED.  My goal is to finalize the governance plan, and then allow a one week period for other TC members who have not had a chance to weigh in on the plan before we bring it to the TC for a vote.

Please use this ticket for all comments relative to the entire Governance Plan, with specific emphasis on the "release" portion.

Link to the github release management training:  https://lab.github.com/githubtraining/create-a-release-based-workflow

---------------------------------------------------------------------------------------
**Proposed Governance structure elements**

1. How often/when should the build team meet? Periodic?  As needed?
2. Who leads builds?  Is it a shared responsibility?  Or have an overall leader?
3. Define flow structure for how PMC would inform TC about future builds, the timing for build, etc, and how TC would inform SC before actual work
4. Develop policy for elements of a build plan.  Minimally, that should include:
- Characterization of build: maintenance, minor, major versions
- What’s being targeted for build (which github issues, etc)
- What aspects of code need updating
- What are the expected updates to code, if known
- What analysis has been done to show that independencies have been addressed
- What testing will be done to ensure code adjustments haven’t adversely affected the functionality of OpenWIS
- Who the recommended reviewers should be
- What documents need to be updated as part of this build (deployment, release notes, etc) with time estimates for completion
- Protect the master and development branch!
5.  Develop policy for peer review process.  Review process should contain:
- ad-hoc review from “pool” of reviewers.  Review of github issue(s).
- Automatic testing platform
- Conduct some unit testing
- Reviewers should use github tags to describe their findings from the review
- The lead should create a pull request if the review is positive
- Automatic deployment
6.  Develop policy for release time of build?  Does that differ depending on if maintenance, minor or major?  Release time assumes all associated documentation has been completed (deployment, release notes, updates to github issues, etc)

**Comment by solson-nws** [comment]
@benjaminsaclier  @mgiannoni  @zhangz555 :  Regarding item 6 in the Governance Structure for future OpenWIS builds, please comment on what you think is the appropriate level for the release policy based on the training module (https://lab.github.com/githubtraining/create-a-release-based-workflow).  Please try to comment by April 8th if at all possible.

Thanks!

Steve

**Comment by solson-nws** [comment]
**Action**:

@benjaminsaclier will update ticket to reflect mandatory, optional pieces.  Point was made to distinguish new, large projects, from smaller efforts.  As written, potentially too burdensome for the required effort.  Consider the scale.

@benjaminsaclier @jude2018  @zhangz555  @yvesgoupil  @mgiannoni @wqu-bom  :  Think of new title for this document that's more reflective of what we're trying to convey

**Comment by jude2018** [comment]
@solson-nws and @benjaminsaclier - do all the ED accounts in Github need to be removed ?

**Comment by jude2018** [comment]
Per TC on 19 May - @solson-nws to propose text for TC approval to mark the WIS2 repo as 'closed' and 'unsupported'

**Comment by jude2018** [comment]
Per TC of 19 May 2020, please also note this related action https://github.com/OpenWIS/openwis-documentation/issues/454#issuecomment-634661642

**Comment by jude2018** [comment]
@solson-nws and @benjaminsaclier - Is there an update on this ? Can this be closed?

**Comment by jude2018** [comment]
23 Nov 2020 - Sonar and Travis aspects to be added @benjaminsaclier @solson-nws and then closed

**Comment by solson-nws** [comment]
These aspects have been added.  Here is the revised doc:

[OpenWIS Development Process Final.docx](https://github.com/OpenWIS/openwis-documentation/files/5649111/OpenWIS.Development.Process.Final.docx)
