### ISSUE TITLE
WIS2 prep- ideas workshop

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#583]
Per TC 19 May 2020 - @solson-nws to set up a workshop to a time-scale and format agreed by the SC to gain ideas for potential work that would benefit WIS2

**Comment by jude2018** [comment]
Per SC on 26-28 May 2020 - a potential item for consideration is security models #441, depending on status and work plans of the WMO and ET and TT equivalents that are forming.

**Comment by jude2018** [comment]
@solson-nws - any update or progress on this ?

**Comment by solson-nws** [comment]
This activity has been overcome by other events.  Closing this ticket and will revisit in 2021
