### ISSUE TITLE
OpenWIS 3x - update Project Charter

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#584]
Per TC 19 May 2020 - update Charter to reflect plans and time-scale for evaluatting work done by MFI, Keycloak and Geonetwork

**Comment by jude2018** [comment]
Please note the closed issue #542

**Comment by jude2018** [comment]
Please also see #585 and #586

**Comment by jude2018** [comment]
@solson-nws and @benjaminsaclier is there an update on this ?

**Comment by solson-nws** [comment]
OpenWIS 3 Project Charter has been updated for Keycloak and Singapore Release.  This ticket can be closed.
