### ISSUE TITLE
OpenWIS 3x - Keycloak investigation Project Charter

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#585]
Per TC on 19 May 2020 - A Project Charter is required to cover this invesyigation that relates to maintenance of OpenWIS 3.x .

Please note the closed issue #542

**Comment by jude2018** [comment]
@solson-nws and @benjaminsaclier - is there an update on this ?

**Comment by zhangz555** [comment]
The keycloak investigation road map. Current status.
[To SC_ Keycloak Valve + API Approach.pdf](https://github.com/OpenWIS/openwis-documentation/files/5334920/To.SC_.Keycloak.Valve.%2B.API.Approach.pdf)

**Comment by solson-nws** [comment]
This can be closed.  Details of this work have now been merged into final version of middleware RFP.
