### ISSUE TITLE
OpenWIX 3.x - Geonetwork investigation Project Charter

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#586]
Per TC of 19 May 2020 - A Project Charter is required for the investigation.

**Comment by jude2018** [comment]
Please note the closed issue #542

**Comment by jude2018** [comment]
@benjaminsaclier and @solson-nws is there an update on this ?

**Comment by solson-nws** [comment]
Closing this out.  No actions taken as of yet.  Will revisit in 2021.
