### ISSUE TITLE
OpenWIS 3.x - procurement partners

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#590]
At the SC 28and 28 May 2020 it was agreed that BoM (@wqu-bom), NWS (@klsheets), and FMI (@mvisa ) would estalish whether prcouremet can be undertaken on behalf of the Assocation for the maintenance of OpenWIS 3.x

UKMO (@6a6d74 ) and MF @remygiraud ) have already established the position in their respective organisations.

Please note the previous work regarding procurement in this issue #557

**Comment by wqu-bom** [comment]
I had meeting today with our procurement lead. To summarise the outcome:
  - It is possible for BoM to carry out the procurement, and it's not as difficult as one think 
    (for 40K Euro),
  - It is also possible to have the procurement with specific vendor if it can be justified. AKKA seems
    to be the one in mind and given AKKA was the openWIS software vendor. Justification seems
    legitimate.
  - Need to seeking the management approval for the procurement, as there was no budget planned 
    for this procurement (although it will be reimbursed).   

I will make an offer to SC for BoM to take the procurement, pending on the approval (which is likely). I may hear from the management before the board meeting late this week. 

-

**Comment by jude2018** [comment]
Per Board on 4 June 2020 - @wqu-bom to confirm the procurement arrangements by September 2020

**Comment by jude2018** [comment]
Per Board on 4 June 2020 - @6a6d74 to check with Michael Robbins on whether the approach for BoM to undertake procurement on behalf of the Association is OK

**Comment by mvisa** [comment]
I also had a discussion about this and it should be possible. FMI currently has an agreement with two partners and via them it should be easy to do procurement. Using other vendors outside the agreement is possible, but this would be much more difficult and require new tenders. However, the current contract ends this year and from 2021 onwards we may have new partners. This shouldn't change the fact, that using them for OpenWIS should still be possible in case needed.

**Comment by jude2018** [comment]
@mvisa - Thanks for responding.  

This good for the Association as it gives options.  

Could you please state what information you (FMI) will need from the Association and when, to enable FMI to proceed? _(this will enable alignment of tasks already known by the TC and SC and make sure that any potential additional tasks or decisions can be made in good time)_

**Comment by mvisa** [comment]
Basically what is needed is a set of necessary skill sets required from the consultants and approx. estimate on how much work there is to be done and in what timeframe. About one month ahead of the need should be sufficient for our suppliers.

**Comment by jude2018** [comment]
Per SC of 29 Sep and Board on 1 Ocr, the following is agreed:

1. Latest legal advice states that only a public agency based in Europe could carry out procurment on behalf of the Association.

1. MF unable to undertake procurement at present.

1. Need to establish whether FMI, UKMO or Belgium can carry out procurement for the Association by early December 2020.

**ACTIONS**:

- [ ] @mvisa to establish whether FMI can undertake procurement, along with time-scales and process by end November 2020
- [ ] @6a6d74 and @jude2018 to establish whether UKMO can undertake procurement along with time-scales and process by end November 2020
- [ ] @remygiraud to establish whether Belhium can  an undertake procurement along with time-scales and process by end November 2020

**Comment by solson-nws** [comment]
**Revised Schedule for Middleware RFP**
  
     a.  Timing of Signapore release upload:  Mid December
     b.  Review of release with TC and independent testing:  January 29, 2021
     c.  Merging of Signapore branch with OpenWIS master branch:   February 26, 2021
     d.   Timing for determining agency to do procurement:  March 5, 2021
     e.   Timing of final middleware RFP:  March 12, 2021
     f.    Finalize documents with agency doing procurement:  March 26, 2021
     g.   Select winning contractor:  May 21, 2021
     h.   Kickoff meeting with winning contractor:  May 28, 2021

**Comment by jude2018** [comment]
Per SC on 7 December 2020:


- [ ] @mvisa to check with FMI whether it is possible to choose a supplier directly via either of FMIs framework contractors.

- [ ] @loiclg to explain approach to the developers of the Singapore code before end December 2020.

- [ ] @loiclg  to meet with FMIs farmework contractors (likely to be EWork), FMI and developers of the Singapore code and have terms in place by end January 2021.

**Comment by jude2018** [comment]
Related risks #592 and #593

**Comment by solson-nws** [comment]
Revised Schedule:

a. Timing of Singapore release upload: (Late December/Early January)  --> DONE
b. Review of release with TC and independent testing: (February 12, 2021)  -->  Issues with installation (NWS, MF, BOM) --> **New projected date: (April 30, 2021)**
c. Merging of Singapore branch with OpenWIS master branch: (February 26, 2021) --> **New projected date: (May 31, 2021)**
d. Timing for determining agency to do procurement: (March 5, 2021) --> **New projected date: (March 31, 2021)**
e. Timing of final middleware RFP: (March 12, 2021) --> **New projected date: (June 11, 2021)**
f. Finalize documents with agency doing procurement: (March 26, 2021) --> **New projected date: July 2, 2021)**
g. Select winning contractor: (May 21, 2021) --> **New projected date:  (July 23, 2021)**
h. Kickoff meeting with winning contractor: (May 28, 2021) --> **New projected date: (July 30, 2021)**

**Comment by loiclg** [comment]
Meeting with MFI, FMI, EWork, and developers of the Singapore code has been done on february 12.

The Singapore developers and EWork are discussing in detail about the best way to setup a possible contract. 
At this stage there is still some pending issues, ie reference country for the contract.

**Comment by jude2018** [comment]
Per SC on 19 May 2021:

- [ ] It was agreed that there should be a contract between FMI and the Assiciation.  @loiclg to draft a contract for FMI to agree and @remygiraud to sign/endorse.

- [ ] It was agreed that a payment schedule is necessary in all contracts to enable alignment of payements and ensure paymenets are made within financial year (I.e. the financial year is January to December). So,  @loiclg and @mvisa to hav a schdule of payments avaiable for the September 2021 Steering Commottee to enable finalisation.

- [ ] It was agreed that we need a process for accepting goods received (i.e. to ensure that the quality of code, its packaging and documentation is of adequate quality and the ability to build/re build and deploy from code to result in functrioning software via the CICD environment).  It would involve the TC Chair @davidpodeur and Vice Chair @solson-nws  accepting 'goods receipt'.  Acceptance criteria (to include all conditions of acceptance such and testing and validation) should be reflected in the RFP  @solson-nws to review RFP and ensure reflection in the RFP and the Association Teechnical rules and Acceptance Criteria in the RFP are aligned .
- [ ]  It was agreed that Association SC or Board level representation to be involved in contract development and acceptance arangements.  @loiclg to draft wording in the relevant contracts.

**Comment by jude2018** [comment]
20 Sep 2021 - Draft contract with payement schedule available from MFI (sent to FMI)

**Comment by JoeDavies90** [comment]
Documents signed by OpenWIS Ass. board chair Rémy Giraud and passed to FMI in January 2022

Agreement made by the SC via remote vote in May 2022 to proceed with the RFP through FMI using  Eworks framework. AKKA chosen to provide middleware solution.

**Comment by JoeDavies90** [comment]
As per the OpenWIS Board meeting on the 07/06/2022  - agreed to close as process in place should the need arise
