### ISSUE TITLE
Contributor License Agreement - add Creative Commons licensing for documentation etc.

### ISSUE THREAD

**Issue by Steve-Palmer** [OpenWIS/openwis-documentation#601]
The CLA http://openwis.github.io/openwis-documentation/rules/A-contributor-license-agreement.html Clause 2 currently refers to Open Source licenses. These are appropriate for software, but not for documentation, teaching and training materials. These would be better covered under a Creative Commons license, see https://creativecommons.org/licenses/ 

It is suggested (by Michael Robbins) that Clause 2 should be amended as follows (changes in **bold**):

Subject to the terms and conditions of this Agreement, You hereby grant to the OpenWIS Association AISBL and to recipients of software **and documentation** distributed by the OpenWIS Association AISBL a perpetual, worldwide, non-exclusive, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works under the terms of the license**(s)** specified for the OpenWIS® Project to which a Contribution is Submitted. Details of the license**(s)** specified for each OpenWIS® Project shall be located in the LICENSE file of the project’s repository within the OpenWIS GitHub organization. As stated in Rule 9.1 of the Internal Rules of the OpenWIS Association AISBL, the software license chosen for an OpenWIS® Project shall be one of the open source licenses from the list maintained by the Open Source Initiative (OSI) at: https://opensource.org/licenses/. **The licenses chosen for the documentation produced as part of an OpenWIS® Project shall be one of those approved by Creative Commons: https://creativecommons.org/share-your-work/** 
You agree and acknowledge that the OpenWIS Association AISBL and its licensees may sublicense and distribute your Contributions under any subsequent version of the license**(s)** specified for the OpenWIS® Project to which Your Contribution was made. Furthermore, You agree that, by approval of the OpenWIS Steering Committee, an OpenWIS® Project may change the license**(s)** (and this CLA) from time to time to an alternative open source license from the list maintained by the OSI **and/or Creative Commons** in order to suit the evolution of the Project. A history of approved CLAs is available.

Note - this links to issue #456

**Comment by 6a6d74** [comment]
The proposal to add text relating to the use of a Creative Commons for documentation assets was unanimously accepted by the OpenWIS Steering Committee today (29/Sep/2020) and will be recommended to the Board on Thursday (1/Oct/2020).

**Comment by jude2018** [comment]
Closed as Board approved and Pull Request actioned
