### ISSUE TITLE
Budget for 2021

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#611]
Per SC on 7 December 2020 - 

@loiclg to make a note to set aside 50k for OpenWIS 3.x middleware development.  For review in mid to late April 2021.

**Comment by jude2018** [comment]
Per SC on 19 May 2021 - @loiclg to aske @dureisseixn to move funds from the Association current account to the savings account (the exact value to be determined by Nathalie - Treasurer)

**Comment by JoeDavies90** [comment]
@loiclg & @dureisseixn are you both OK for me to close this open issue relating to the 2021 budget?

**Comment by JoeDavies90** [comment]
Budget and accounts agreed as per the OpenWIS Board meeting on the 07/06/2022
